// Bibliothèque de fiches ETF — contenu pré-rédigé, données stockées en dur, aucune donnée de
// marché en temps réel. Modifie librement un champ (isin, ter, positions, aum, distribution,
// pea, cto, location, whatIs, whyInteresting, whatToKnow, verdict, question) sans rien casser
// ailleurs.
//
// Audit "meilleurs ETF" du 25/08/2026 (même passe que le générateur de tweets ETF) : la fiche
// msci-world utilisait le CW8 (Amundi MSCI World, 0,38%) — remplacé par Amundi PEA Monde
// (MSCI World), 0,20%, cohérent avec la correction faite côté tweets ETF. Plusieurs autres
// fiches contenaient des ISIN erronés ou périmés (semiconducteurs, energie, blockchain,
// nucleaire, covered-call, sp500, nasdaq100, eurostoxx50, luxe), des TER inexacts (value,
// obligations-etat) ou des champs distribution inversés Capitalisant/Distribuant (eau,
// obligations-etat, high-yield), corrigés après vérification web (justETF, fiches émetteurs).
// La plupart des encours ont aussi été rafraîchis (souvent fortement sous-estimés). Voir
// l'historique git pour le détail fonds par fonds.
//
// lastVerified (ajouté le 14/09/2026, audit "outils") : date de la vérification la plus récente
// déjà documentée dans les commentaires de CHAQUE fiche (jamais une date ajoutée séparément à la
// main), affichée dans l'UI à côté de l'encours (cf. App.jsx) — l'encours étant le champ qui bouge
// le plus vite de toute la fiche. 25/08/2026 pour les 26 fiches de l'audit "meilleurs ETF" d'origine
// (aucune date plus récente documentée pour elles depuis) ; 08/09/2026 pour les 6 fiches de l'audit
// "densité" (msci-acwi, ftse-all-world, financieres, immobilier-reit, technologie, momentum) ;
// 10/09/2026 pour quality (TER/encours corrigés après l'audit croisé avec le Comparateur d'indices,
// une date plus récente que son propre ajout du 08/09/2026). Les 3 fiches obligataires qui n'avaient
// aucun commentaire daté (corp-bond-ig, high-yield-acc, em-local-bond) ont été revérifiées le même
// jour (14/09/2026, cf. leurs commentaires individuels) — les 36 fiches portent désormais une date.

export const CATEGORY_ORDER = [
    "Cœur de portefeuille",
    "Sectoriels classiques",
    "Thématiques émergentes",
    "Spatial",
    "Stratégiques",
    "Obligataires"
  ];

export const CATEGORY_EMOJI = {
    "Cœur de portefeuille": "🔵",
    "Sectoriels classiques": "🟢",
    "Thématiques émergentes": "🟠",
    "Spatial": "🚀",
    "Stratégiques": "🟣",
    "Obligataires": "⚪"
  };

export const ETFS = [
    // ---------- CŒUR DE PORTEFEUILLE ----------
    {
      id: "msci-world",
      category: "Cœur de portefeuille",
      name: "Amundi PEA Monde (MSCI World) UCITS ETF",
      tickers: ["DCAM"],
      isNew: true,
      isin: "FR001400U5Q4",
      ter: "0,20%",
      positions: "~1 500 positions",
      aum: "~1,37 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: true,
      cto: true,
      location: "France, réplication synthétique (swap)",
      whatIs: "Un seul ETF pour suivre environ 1 500 grandes et moyennes entreprises de 23 pays développés. « Monde » ne veut toutefois pas dire répartition égale : les États-Unis représentent environ 70 % de l’indice, et les géants technologiques y occupent une grande place.",
      whyInteresting: "Si tu veux une ligne principale sur ton PEA sans choisir toi-même tes pays et tes secteurs, c’est une solution simple. Sa réplication synthétique lui permet de suivre le MSCI World tout en restant éligible au PEA, avec 0,20 % de frais annuels.",
      whatToKnow: "Tu détiens beaucoup d’entreprises, mais ton résultat dépend fortement du marché américain. Il n’y a pas de petites capitalisations. Et si tu investis sur CTO, compare les frais : d’autres ETF World y coûtent moins cher.",
      verdict: "Une base simple pour un PEA de long terme, à condition d’être à l’aise avec son poids américain.",
      question: "Dans ton PEA, tu préfères un seul ETF World ou ajouter d’autres régions à côté ?"
    },
    {
      id: "sp500",
      category: "Cœur de portefeuille",
      name: "Amundi PEA S&P 500 UCITS ETF",
      tickers: ["PSP5"],
      isNew: false,
      isin: "FR0011871128",
      ter: "0,12%",
      positions: "500 positions",
      aum: "~1,15 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: true,
      cto: true,
      location: "France, réplication synthétique (swap)",
      whatIs: "Réplique le S&P 500, l'indice des 500 plus grandes capitalisations cotées aux États-Unis. Fortement pondéré tech : Apple, Nvidia, Microsoft, Amazon et Alphabet pèsent à eux cinq plus d'un quart de l'indice. 100% USA, tous secteurs représentés mais la tech domine largement.",
      whyInteresting: "Le benchmark le plus suivi au monde, avec une performance historique solide sur longue période. Version PEA-éligible grâce à la réplication synthétique — fiscalité avantageuse pour un investisseur français. Perf autour de +20% sur 1 an sur cette ligne.",
      whatToKnow: "100% USA donc risque de change EUR/USD non couvert. Concentration tech forte. Réplication synthétique : risque de contrepartie généralement bien collatéralisé, mais à comprendre avant d'investir. Aucune diversification internationale.",
      verdict: "Si tu veux concentrer ta poche actions sur les États-Unis tout en restant sur PEA, cet ETF va droit au but. Il ne t’apporte aucune exposition aux autres marchés.",
      question: "Tu détiens déjà un ETF World : ajouterais-tu aussi du S&P 500, sachant que les grandes valeurs américaines y sont déjà présentes ?"
    },
    {
      id: "nasdaq100",
      category: "Cœur de portefeuille",
      name: "Amundi PEA Nasdaq-100 UCITS ETF",
      tickers: ["PUST"],
      isNew: false,
      isin: "FR0011871110",
      ter: "0,30%",
      positions: "100 positions",
      aum: "~1,17 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: true,
      cto: true,
      location: "France, réplication synthétique (swap)",
      whatIs: "Réplique le Nasdaq-100, les 100 plus grosses valeurs non-financières cotées au Nasdaq. Ultra tech : Nvidia, Apple, Microsoft, Broadcom, Amazon en tête. Quasi aucune banque, aucune valeur pétrolière — un pari pur sur la croissance et la technologie américaine.",
      whyInteresting: "Exposition concentrée aux entreprises les plus innovantes de la cote US, moteur de la hausse boursière depuis plus d'une décennie. Perf forte portée par l'IA : au-delà de +25% sur 1 an sur les bons millésimes. PEA-éligible via la réplication synthétique.",
      whatToKnow: "Zéro diversification sectorielle réelle — c'est un pari tech assumé, pas un fonds \"large\". Volatilité plus élevée que le S&P 500. Risque de change non couvert. Correction sévère possible en cas de dégonflement des valorisations tech.",
      verdict: "Une exposition assumée aux grandes valeurs non financières du Nasdaq. À considérer pour accentuer ce biais, pas pour diversifier un portefeuille déjà chargé en tech.",
      question: "Si tu as déjà un ETF World ou S&P 500, quelle place laisserais-tu encore au Nasdaq-100 ?"
    },
    {
      id: "eurostoxx50",
      category: "Cœur de portefeuille",
      name: "Amundi Core EURO STOXX 50 UCITS ETF",
      tickers: ["C50"],
      isNew: false,
      isin: "LU1681047236",
      ter: "0,09%",
      positions: "50 positions",
      aum: "~4,02 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: true,
      cto: true,
      location: "Luxembourg, réplication physique intégrale",
      whatIs: "Réplique l'Euro Stoxx 50, les 50 plus grandes capitalisations de la zone euro. Top positions : LVMH, ASML, SAP, TotalEnergies, Siemens. Un mix de luxe, de tech européenne, d'énergie et d'industrie, très différent de la composition d'un indice américain.",
      whyInteresting: "Exposition pure à la zone euro, éligible PEA au meilleur prix du marché (0,09% de frais). Bon complément pour rééquilibrer un portefeuille trop USA-centré. Sensible aux cycles de taux de la BCE.",
      whatToKnow: "Seulement 50 titres : concentration forte sur quelques secteurs (luxe, banques, industrie). Croissance historiquement plus lente que le S&P 500 sur longue période. Peu d'exposition à la tech pure.",
      verdict: "Cinquante grandes sociétés de la zone euro à faible coût. Le nombre limité de lignes mérite d’être assumé.",
      question: "Pour ajouter de l’Europe, tu choisirais ces 50 grandes valeurs ou un indice européen plus large ?"
    },
    {
      id: "msci-em",
      category: "Cœur de portefeuille",
      name: "iShares Core MSCI EM IMI UCITS ETF",
      tickers: ["EMIM"],
      isNew: false,
      isin: "IE00BKM4GZ66",
      ter: "0,18%",
      positions: "~3 000 positions",
      aum: "~36,8 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée (échantillonnage)",
      whatIs: "Réplique le MSCI Emerging Markets IMI, environ 3 000 valeurs de pays émergents toutes tailles confondues. Chine, Taïwan, Inde et Corée du Sud en tête. Top positions : Taiwan Semiconductor, Tencent, Samsung, Alibaba — un mix de tech asiatique et de conglomérats locaux.",
      whyInteresting: "Diversification hors marchés développés, exposition à la croissance démographique et technologique de l'Asie émergente et de l'Inde. Valorisations globalement plus basses que sur les marchés américains, marge de rattrapage potentielle.",
      whatToKnow: "Forte dépendance à la Chine (risque géopolitique, gouvernance d'entreprise, régulation). Volatilité plus élevée que les marchés développés. Pas de PEA. Multiples devises non couvertes contre l'euro.",
      verdict: "Il ajoute les marchés émergents, y compris leurs petites capitalisations, à un portefeuille centré sur les pays développés. La diversification s’accompagne de risques propres à ces marchés.",
      question: "Tu préfères détenir les émergents séparément ou dans un ETF ACWI tout-en-un ?"
    },
    // Ajouté le 08/09/2026 (audit "densité", catégorie volontairement restreinte aux World/ACWI/
    // All-World à la demande de l'utilisateur). ISIN/TER/encours vérifiés via WebSearch (WebFetch
    // bloqué dans ce sandbox), croisés en 2e requête indépendante — écarts ≤1% sur le TER et les
    // positions, convergents. Encours : plusieurs chiffres selon la part/devise regardée (fonds
    // total vs part USD Acc spécifique) — retenu celui de la part précise listée ici (ISIN ci-
    // dessous), pas le total tous compartiments confondus, cohérent avec la convention du reste
    // du fichier (chaque fiche cite l'encours DE SA part, pas du fonds entier).
    {
      id: "msci-acwi",
      category: "Cœur de portefeuille",
      name: "iShares MSCI ACWI UCITS ETF USD (Acc)",
      tickers: ["SSAC"],
      isNew: true,
      isin: "IE00B6R52259",
      ter: "0,20%",
      positions: "~1 970 positions",
      aum: "~35 Md$",
      lastVerified: "08/09/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée (échantillonnage)",
      whatIs: "Réplique le MSCI ACWI (All Country World Index), qui combine environ 1 970 valeurs de pays développés ET de marchés émergents en une seule ligne — la version \"tout compris\" du MSCI World, émergents inclus. Top positions : Nvidia, Apple, Microsoft, Amazon, Alphabet — même dominance tech US que le World, avec un peu plus de diversification géographique.",
      whyInteresting: "Le seul indice qui capture développés + émergents sans avoir à gérer deux lignes séparées. Expose à la croissance émergente (Chine, Taïwan, Inde) sans complexifier le portefeuille avec une ligne dédiée.",
      whatToKnow: "Pas d'option PEA (plus de 25% hors zone euro et hors accord fiscal). Domination tech américaine quasi identique au MSCI World — l'ajout des émergents dilue peu la concentration US, qui reste autour de 65-70%. Frais (0,20%) légèrement plus élevés qu'un MSCI World seul.",
      verdict: "Un ETF mondial qui inclut aussi les pays émergents. Pratique si tu veux une seule ligne en CTO et ne souhaites pas fixer leur poids toi-même.",
      question: "Tu laisserais l’indice déterminer la place des émergents ou tu choisirais leur poids séparément ?"
    },
    // Sourcing : TER du VWCE recoupé en 3 requêtes successives, chiffres apparemment contradictoires
    // (0,14% / 0,19% / 0,22%) résolus comme une chronologie de baisses de frais Vanguard (0,22%
    // jusqu'en octobre 2025, 0,19% jusqu'au 28/07/2026, 0,14% depuis) et non comme une contradiction
    // — confirmé par un article daté nommant explicitement la baisse du 28/07/2026. Même situation
    // que l'écart PALAT/PLEM déjà rencontré ailleurs dans l'app : plusieurs valeurs valides à des
    // dates différentes, pas une erreur.
    {
      id: "ftse-all-world",
      category: "Cœur de portefeuille",
      name: "Vanguard FTSE All-World UCITS ETF (USD) Accumulating",
      tickers: ["VWCE"],
      isNew: true,
      isin: "IE00BK5BQT80",
      ter: "0,14%",
      positions: "~3 760 positions",
      aum: "~50,8 Md€",
      lastVerified: "08/09/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le FTSE All-World, l'indice le plus large des trois \"World\" du marché : environ 3 760 valeurs de pays développés et émergents, petites capitalisations comprises — contrairement au MSCI World ou au MSCI ACWI qui s'arrêtent aux grandes et moyennes capitalisations. Top positions : Nvidia, Apple, Microsoft, Amazon, Alphabet.",
      whyInteresting: "L'ETF \"un seul fonds pour tout\" le plus connu en Europe. Frais parmi les plus bas du marché pour ce niveau de diversification : 0,14% depuis la dernière baisse de Vanguard (28/07/2026, après 0,19% puis 0,22% les années précédentes).",
      whatToKnow: "Pas de version PEA (Vanguard ne propose aucun wrapper PEA sur ses ETF). Small caps incluses mais leur poids reste marginal — la performance reste tirée par les mêmes méga-caps que le World. Encours variable selon la part/devise regardée (~50,8 Md€ pour la seule part Acc USD listée ici).",
      verdict: "Une seule ligne pour mêler pays développés et émergents en CTO. Vérifie ce que tu possèdes déjà avant d’en ajouter une deuxième très proche.",
      question: "Si tu détenais déjà un MSCI World, remplacerais-tu cette ligne par un All-World ou ajouterais-tu les émergents à part ?"
    },

    // ---------- SECTORIELS CLASSIQUES ----------
    {
      id: "semiconducteurs",
      category: "Sectoriels classiques",
      name: "iShares MSCI Global Semiconductors UCITS ETF",
      tickers: ["SEMI"],
      isNew: false,
      isin: "IE000I8KRLL9",
      ter: "0,35%",
      positions: "~30 positions",
      aum: "~5,1 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le MSCI ACWI IMI Semiconductors & Semiconductor Equipment. Concentré sur les fabricants de puces et équipementiers mondiaux : Nvidia, TSMC, Broadcom, ASML, AMD en tête. C'est le maillon matériel de toute la chaîne de valeur IA.",
      whyInteresting: "Exposition directe au boom de l'IA côté infrastructure physique (GPU, fonderies, équipements de gravure). Performance explosive tirée par la demande en puces : largement au-dessus de +30% sur 1 an sur les bons millésimes.",
      whatToKnow: "Très concentré sur environ 30 titres, dépendant de quelques géants (Nvidia, TSMC). Secteur cyclique par nature (cycles de stocks des semi-conducteurs). Forte volatilité, pas de PEA.",
      verdict: "Il rassemble les fabricants de puces plutôt que de faire reposer toute cette conviction sur Nvidia. Le secteur reste très cyclique.",
      question: "Tu préfères répartir ton exposition aux puces entre plusieurs fabricants ou choisir une entreprise ?"
    },
    {
      id: "sante-biotech",
      category: "Sectoriels classiques",
      name: "iShares Nasdaq US Biotechnology UCITS ETF",
      tickers: ["BTEC"],
      isNew: false,
      isin: "IE00BYXG2H39",
      ter: "0,35%",
      positions: "~200 positions",
      aum: "~1,1 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le Nasdaq Biotechnology Index, environ 200 entreprises biotech et pharma cotées au Nasdaq. Top positions : Amgen, Gilead, Vertex, Regeneron — un mix de biotechs innovantes et de laboratoires déjà établis.",
      whyInteresting: "Exposition à l'innovation médicale (thérapies géniques, oncologie, maladies rares), secteur défensif par nature puisque la santé n'est pas une dépense discrétionnaire. Bonne diversification sectorielle par rapport à un portefeuille tech-centré.",
      whatToKnow: "Volatilité liée aux résultats d'essais cliniques et aux décisions de la FDA — des annonces qui font bouger une ligne de +/-20% en une séance. Sensible aux taux d'intérêt. Pas de PEA, cycles de développement longs.",
      verdict: "Une exposition ciblée aux biotechnologies américaines, avec des résultats très dépendants des essais cliniques et des autorisations.",
      question: "Pour investir dans la santé, tu choisirais la biotech ou un indice santé plus large ?"
    },
    {
      id: "energie",
      category: "Sectoriels classiques",
      name: "SPDR MSCI World Energy UCITS ETF",
      tickers: ["WNRG"],
      isNew: false,
      isin: "IE00BYTRR863",
      ter: "0,30%",
      positions: "~100 positions",
      aum: "~466 M€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique le MSCI World Energy, environ 100 entreprises mondiales du secteur pétrole, gaz et énergie. Top positions : ExxonMobil, Chevron, Shell, TotalEnergies — les grandes majors énergétiques occidentales.",
      whyInteresting: "Exposition aux majors de l'énergie fossile, avec des dividendes historiquement généreux sur ce secteur. Fonctionne souvent comme une couverture naturelle contre l'inflation énergétique et les tensions géopolitiques sur le pétrole.",
      whatToKnow: "Secteur cyclique, très dépendant du prix du baril. En décalage avec la transition énergétique (risque réglementaire à moyen terme). Concentré sur quelques majors. Pas de PEA.",
      verdict: "Pour ajouter les grandes sociétés énergétiques mondiales à ton portefeuille. Leur résultat reste lié au cycle des hydrocarbures.",
      question: "Tu vois cette ligne comme une exposition durable ou comme un pari sur le cycle du pétrole ?"
    },
    {
      id: "defense",
      category: "Sectoriels classiques",
      name: "VanEck Defense UCITS ETF",
      tickers: ["DFNS", "DFND"],
      isNew: false,
      isin: "IE000YYE6WK5",
      ter: "0,55%",
      positions: "~30 positions",
      aum: "~6,6 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le MarketVector Global Defense Index, un panier d'entreprises mondiales de défense et d'armement. Top positions : Palantir, RTX, Lockheed Martin, Rheinmetall, Thales — un mix USA-Europe centré sur les grands programmes militaires.",
      whyInteresting: "Thème porté par la hausse durable des budgets militaires (réarmement européen, tensions OTAN). Performance forte depuis le lancement, secteur peu corrélé aux cycles économiques classiques puisque les commandes sont publiques et pluriannuelles.",
      whatToKnow: "Question éthique à trancher soi-même avant d'investir. Concentré sur une trentaine de titres. Dépendant des budgets publics et de la géopolitique — un changement de doctrine peut peser lourd. Pas de PEA, frais élevés.",
      verdict: "Un accès diversifié aux entreprises de défense, avec une question à se poser avant les chiffres : est-ce compatible avec tes convictions ?",
      question: "La défense aurait-elle sa place dans ton portefeuille, même avec un poids limité ?"
    },
    {
      id: "cybersecurite",
      category: "Sectoriels classiques",
      name: "L&G Cyber Security UCITS ETF",
      tickers: ["ISPY"],
      isNew: false,
      isin: "IE00BYPLS672",
      ter: "0,69%",
      positions: "~30 positions",
      aum: "~3,2 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique l'ISE Cyber Security Select Index, une trentaine de pure players de la cybersécurité. Top positions : Palo Alto Networks, CrowdStrike, Fortinet, Cisco — les principaux fournisseurs de solutions de protection numérique.",
      whyInteresting: "Thème structurel porté par la hausse continue des cyberattaques et la digitalisation de tous les secteurs. Demande peu cyclique : les budgets cybersécurité sont rarement coupés, même en période de restriction budgétaire.",
      whatToKnow: "Concentré sur une trentaine de titres, valorisations tech souvent tendues. Frais parmi les plus élevés du segment thématique (0,69%). Pas de PEA.",
      verdict: "Il permet de suivre plusieurs entreprises de cybersécurité sans choisir un seul gagnant. Reste à vérifier le prix payé pour cette croissance attendue.",
      question: "Tu préfères une exposition dédiée à la cybersécurité ou la tech déjà présente dans ton ETF World ?"
    },
    {
      id: "eau",
      category: "Sectoriels classiques",
      name: "Amundi MSCI Water UCITS ETF (Dist)",
      tickers: ["WAT"],
      isNew: false,
      isin: "FR0010527275",
      ter: "0,60%",
      positions: "~30 positions",
      aum: "~1,56 Md€",
      lastVerified: "25/08/2026",
      distribution: "Distribuant",
      pea: false,
      cto: true,
      location: "France, réplication physique intégrale",
      whatIs: "Réplique le World Water Index, des entreprises liées au traitement, à la distribution et à la gestion de l'eau. Top positions : American Water Works, Veolia, Xylem, Ecolab — un mix d'utilities et d'équipementiers industriels.",
      whyInteresting: "Thème défensif porté par une ressource rare et non substituable, avec une demande structurellement croissante (urbanisation, stress hydrique, vieillissement des infrastructures).",
      whatToKnow: "Secteur peu volatil mais croissance plus lente qu'un thème tech. Forte pondération utilities/industrie, peu de tech pure. Frais élevés (0,60%) pour un profil aussi défensif. Pas de PEA.",
      verdict: "Une exposition aux entreprises liées à l’eau, qui ne revient pas à investir directement dans le prix de cette ressource.",
      question: "Dans un ETF eau, tu cherches surtout les services publics ou les technologies de traitement ?"
    },
    {
      id: "luxe",
      category: "Sectoriels classiques",
      name: "Amundi S&P Global Luxury UCITS ETF",
      tickers: ["GLUX"],
      isNew: false,
      isin: "LU1681048630",
      ter: "0,25%",
      positions: "~80 positions",
      aum: "~450 M€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Luxembourg, réplication physique optimisée",
      whatIs: "Réplique le S&P Global Luxury Index, des entreprises mondiales du luxe et des biens haut de gamme. Top positions : LVMH, Hermès, L'Oréal, Ferrari, Richemont — les grandes maisons de luxe européennes et quelques acteurs mondiaux.",
      whyInteresting: "Exposition à la classe moyenne mondiale montante et à la résilience de la demande ultra-riche. Des marques avec un fort pricing power, capables de répercuter l'inflation sans perdre leurs clients.",
      whatToKnow: "Très corrélé à la consommation chinoise — un ralentissement à Pékin se ressent immédiatement sur la ligne. Cyclique malgré l'image \"premium\". Valorisations élevées. Pas de PEA.",
      verdict: "Un panier de marques mondiales, mais quelques groupes pèsent lourd et leurs ventes restent sensibles aux consommateurs aisés.",
      question: "Tu ajouterais un ETF luxe si tu possèdes déjà ses principales valeurs dans un indice européen ?"
    },
    // Ajouté le 08/09/2026 (audit "densité", 3 secteurs GICS classiques manquants : financières,
    // immobilier coté, technologie large). ISIN/TER vérifiés et croisés en 2e requête indépendante
    // (écarts ≤0,1%, convergents). Encours (AUM) de l'iShares Property Yield (immobilier) a montré
    // 4 valeurs différentes selon les requêtes (46M / 972M / 1 034M / 1 730M) — écart bien plus large
    // qu'une simple différence de date : le premier chiffre (46M) et le dernier (1 730M) ont été
    // écartés comme non fiables (units/devises probablement mal lus par la recherche), retenu le
    // point médian des deux chiffres convergents (972M et 1 034M, écart 6% seulement) = ~1 003 M€,
    // arrondi à ~1 Md€.
    {
      id: "financieres",
      category: "Sectoriels classiques",
      name: "iShares MSCI World Financials Sector Advanced UCITS ETF USD (Dist)",
      tickers: ["WFNS"],
      isNew: true,
      isin: "IE00BJ5JP097",
      ter: "0,18%",
      positions: "228 positions",
      aum: "~125 M€",
      lastVerified: "08/09/2026",
      distribution: "Distribuant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique",
      whatIs: "Réplique le MSCI World Financials Advanced Select 20/35 Capped, environ 228 banques, assureurs et sociétés de paiement des marchés développés. Top positions : JPMorgan Chase, Visa, Berkshire Hathaway, Mastercard, Goldman Sachs — un mix de banques classiques et de réseaux de paiement.",
      whyInteresting: "Secteur historiquement décoté par rapport au marché, avec des dividendes généreux. Sensible positivement à la hausse des taux d'intérêt (marge d'intermédiation des banques), à l'inverse de la plupart des autres secteurs.",
      whatToKnow: "Encours modeste (~125 M€) pour un ETF sectoriel — liquidité à surveiller avant d'investir de gros montants. Cyclique : très sensible aux crises de crédit et aux retournements de cycle (2008 reste le contre-exemple historique). Version distribuante : fiscalité à surveiller en CTO. Pas de PEA.",
      verdict: "Pour augmenter délibérément la part des banques et autres sociétés financières dans un portefeuille mondial.",
      question: "Tu veux surpondérer la finance ou laisser ton ETF World déterminer son poids ?"
    },
    {
      id: "immobilier-reit",
      category: "Sectoriels classiques",
      name: "iShares Developed Markets Property Yield UCITS ETF USD (Dist)",
      tickers: ["IWDP"],
      isNew: true,
      isin: "IE00B1FZS350",
      ter: "0,59%",
      positions: "339 positions",
      aum: "~1 Md€",
      lastVerified: "08/09/2026",
      distribution: "Distribuant (trimestriel)",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique",
      whatIs: "Réplique un indice de foncières cotées (REIT) des marchés développés, environ 339 sociétés qui possèdent et gèrent de l'immobilier (bureaux, entrepôts, data centers, commerces). Top positions : Prologis (entrepôts logistiques), Equinix (data centers), Simon Property Group, Digital Realty Trust, Realty Income.",
      whyInteresting: "Exposition à l'immobilier sans les contraintes d'un achat en direct (liquidité quotidienne, ticket d'entrée minime). Les foncières cotées ont l'obligation légale de reverser la quasi-totalité des loyers perçus en dividendes — rendement généralement élevé.",
      whatToKnow: "Très sensible aux taux d'intérêt : le crédit immobilier renchérit, les valorisations des foncières baissent. Frais élevés pour un tracker (0,59%). Distribuant : fiscalité à surveiller hors PEA. Pas de PEA (aucune foncière française pure ne domine l'indice).",
      verdict: "De l’immobilier coté, achetable comme une action. Sa liquidité ne le protège ni des baisses en Bourse ni des variations de taux.",
      question: "Tu choisirais les foncières cotées pour leur liquidité, malgré leurs variations quotidiennes ?"
    },
    {
      id: "technologie",
      category: "Sectoriels classiques",
      name: "iShares MSCI World Information Technology Sector Advanced UCITS ETF USD (Dist)",
      tickers: ["WITS"],
      isNew: true,
      isin: "IE00BJ5JNY98",
      ter: "0,18%",
      positions: "161 positions",
      aum: "~1,04 Md€",
      lastVerified: "08/09/2026",
      distribution: "Distribuant (semestriel)",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le MSCI World Information Technology Advanced Select 20/35 Capped, environ 161 entreprises du secteur technologique mondial — plus large qu'un pari pur semi-conducteurs ou IA. Top positions : Nvidia (17,3%), Apple (14,2%), Microsoft (10,3%), Broadcom (7,1%), ASML — logiciel, matériel et semi-conducteurs réunis.",
      whyInteresting: "Le pari \"toute la tech\" plutôt qu'un sous-secteur isolé (semi-conducteurs, IA, cybersécurité, déjà présents ailleurs dans cette bibliothèque). Bon proxy pour qui veut sur-pondérer la tech sans choisir un thème précis.",
      whatToKnow: "Très concentré malgré 161 lignes : les 3 premières positions pèsent plus de 40% du fonds. Quasi doublon avec le Nasdaq-100 et les paris sectoriels tech déjà présents (semi-conducteurs, IA) — risque de sur-concentration si combiné avec eux dans le même portefeuille. Pas de PEA.",
      verdict: "Une façon de surpondérer toute la tech mondiale. Regarde les premières lignes : elles peuvent déjà peser lourd dans ton ETF World.",
      question: "Combien de tes principales positions se retrouveraient à la fois ici et dans ton ETF World ?"
    },

    // ---------- THÉMATIQUES ÉMERGENTES / NICHE ----------
    {
      id: "quantique",
      category: "Thématiques émergentes",
      name: "VanEck Quantum Computing UCITS ETF A",
      tickers: ["QUTM", "QNTM"],
      isNew: true,
      isin: "IE0007Y8Y157",
      ter: "0,55%",
      positions: "30 positions",
      aum: "~755 M€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Un panier d’environ 30 entreprises liées à l’informatique quantique. Certaines en font leur activité centrale ; pour d’autres, le quantique n’est qu’une partie de leurs projets. Acheter cet ETF ne revient donc pas à acheter uniquement des spécialistes du secteur.",
      whyInteresting: "Tu peux suivre ce thème sans devoir choisir toi-même entre une jeune entreprise très risquée et un groupe déjà établi. C’est surtout une façon de prendre une position ciblée sur une technologie dont l’usage commercial reste à construire.",
      whatToKnow: "Avec environ 30 lignes, le fonds reste concentré et ses variations peuvent être fortes. Les frais sont de 0,55 % par an et il n’est pas éligible au PEA. Les hausses passées ne disent pas si ces entreprises transformeront la technologie en bénéfices.",
      verdict: "Une petite position thématique éventuelle, pour qui accepte une forte volatilité et un résultat très incertain.",
      question: "Si tu voulais investir dans le quantique, tu choisirais cet ETF ou quelques entreprises précises ?"
    },
    {
      id: "ia",
      category: "Thématiques émergentes",
      name: "L&G Artificial Intelligence UCITS ETF",
      tickers: ["AIAI"],
      isNew: false,
      isin: "IE00BK5BCD43",
      ter: "0,49%",
      positions: "~80 positions",
      aum: "~1,8 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le ROBO Global Artificial Intelligence Index, des entreprises actives sur toute la chaîne de valeur de l'IA : infrastructure, logiciels, applications. Top positions : Nvidia, Microsoft, Palantir, ServiceNow, Nice — un mix d'infrastructure et de logiciel applicatif.",
      whyInteresting: "Exposition large à toute la chaîne de valeur IA, pas seulement aux puces. Performance portée par l'engouement pour l'IA générative depuis 2023, avec des progressions à deux chiffres sur 1 an.",
      whatToKnow: "Valorisations tendues sur beaucoup de lignes, risque de bulle sur certains segments applicatifs. Très corrélé au Nasdaq. Pas de PEA.",
      verdict: "Cet ETF rassemble plusieurs métiers liés à l’IA. Vérifie sa composition avant de supposer qu’il suit uniquement les fabricants de modèles ou de puces.",
      question: "Tu veux investir dans les fabricants de puces, les logiciels ou l’ensemble de la chaîne IA ?"
    },
    {
      id: "robotique",
      category: "Thématiques émergentes",
      name: "iShares Automation & Robotics UCITS ETF",
      tickers: ["RBOT"],
      isNew: false,
      isin: "IE00BYZK4552",
      ter: "0,40%",
      positions: "~120 positions",
      aum: "~4,5 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le iSTOXX FactSet Automation & Robotics Index, des entreprises liées à l'automatisation industrielle et à la robotique. Top positions : Nvidia, Fanuc, Intuitive Surgical, Keyence — mix de robotique industrielle et de robotique chirurgicale.",
      whyInteresting: "Thème porté par la relocalisation industrielle et la pénurie de main-d'œuvre qualifiée. Exposition diversifiée entre robotique industrielle classique et robotique médicale à forte marge.",
      whatToKnow: "Large diversification qui dilue l'effet \"pure play\" par rapport à un thème plus concentré. Cyclique, car dépendant de l'investissement industriel des entreprises. Pas de PEA.",
      verdict: "Une exposition à l’automatisation des entreprises, plus concrète que le seul récit autour de l’IA générative.",
      question: "Tu préfères la robotique industrielle ou les entreprises de logiciels d’IA ?"
    },
    {
      id: "blockchain",
      category: "Thématiques émergentes",
      name: "iShares Blockchain Technology UCITS ETF",
      tickers: ["BLKC"],
      isNew: false,
      isin: "IE000RDRMSD1",
      ter: "0,50%",
      positions: "~50 positions",
      aum: "~308 M€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique un indice d'entreprises liées à l'écosystème blockchain : mineurs de cryptomonnaies, plateformes d'échange, fournisseurs d'infrastructure. Top positions : Coinbase, Strategy (ex-MicroStrategy), Marathon Digital, Robinhood.",
      whyInteresting: "Exposition à l'écosystème crypto sans détenir directement de cryptomonnaies ni gérer de wallet. Forte corrélation au cycle bitcoin, mais via des actions cotées et un cadre réglementaire classique.",
      whatToKnow: "Très volatil, fortement corrélé au bitcoin. Certaines entreprises du panier sont elles-mêmes spéculatives (mineurs endettés). Pas de PEA, thème encore jeune sur le plan réglementaire.",
      verdict: "Tu achètes ici des actions d’entreprises liées à la blockchain, pas du Bitcoin. Leurs risques d’entreprise s’ajoutent au cycle crypto.",
      question: "Tu préférerais détenir directement du Bitcoin ou des sociétés exposées à son écosystème ?"
    },
    {
      id: "nucleaire",
      category: "Thématiques émergentes",
      name: "VanEck Uranium and Nuclear Technologies UCITS ETF",
      tickers: ["NUKL"],
      isNew: false,
      isin: "IE000M7V94E1",
      ter: "0,55%",
      positions: "~25 positions",
      aum: "~2,0 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le MarketVector Uranium & Nuclear Technologies Index : mines d'uranium, exploitants de centrales, équipementiers, et acteurs émergents de la fusion nucléaire. Top positions : Cameco, Constellation Energy, NuScale, Oklo.",
      whyInteresting: "Thème porté par la relance mondiale du nucléaire pour décarboner et sécuriser l'approvisionnement électrique — data centers IA compris. Diversifie entre mines d'uranium déjà rentables et paris technologiques sur la fusion.",
      whatToKnow: "Très corrélé au prix de l'uranium (cyclique et sensible aux décisions politiques). Les acteurs de la fusion sont encore pré-commerciaux, à des années voire des décennies de la rentabilité. Frais élevés, pas de PEA.",
      verdict: "Il réunit plusieurs maillons du nucléaire. La demande d’électricité ne suffit pas, à elle seule, à garantir la hausse de ces actions.",
      question: "Tu chercherais plutôt les producteurs d’uranium ou les industriels du nucléaire ?"
    },
    {
      id: "batteries-ve",
      category: "Thématiques émergentes",
      name: "L&G Battery Value-Chain UCITS ETF",
      tickers: ["BATT"],
      isNew: false,
      isin: "IE00BF0M2Z96",
      ter: "0,49%",
      positions: "~40 positions",
      aum: "~730 M€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique la Solactive Battery Value-Chain Index, toute la chaîne de valeur des batteries : extraction de lithium, fabricants de cellules, constructeurs de véhicules électriques. Top positions : Tesla, CATL, Albemarle, BYD.",
      whyInteresting: "Exposition à la transition vers l'électrique, diversifiée sur toute la chaîne de valeur (mines, cellules, constructeurs) plutôt que sur un seul maillon isolé.",
      whatToKnow: "Secteur en forte correction depuis 2022 : ralentissement de la demande VE en Europe, surcapacité de production en Chine. Volatil, encore loin de ses plus hauts. Pas de PEA.",
      verdict: "Une exposition à toute la chaîne des batteries, pas seulement aux constructeurs automobiles. Le thème a déjà montré qu’une tendance de fond peut décevoir en Bourse.",
      question: "Tu regarderais plutôt les fabricants de batteries ou les fournisseurs de matériaux ?"
    },

    // ---------- SPATIAL ----------
    {
      id: "spatial",
      category: "Spatial",
      name: "VanEck Space Innovators UCITS ETF",
      tickers: ["JEDI"],
      isNew: true,
      isin: "IE000YU9K6K2",
      ter: "0,55%",
      positions: "25 positions",
      aum: "~2,0 Md$",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique",
      whatIs: "Réplique l'indice MarketVector Global Space Industry Screened : environ 25 entreprises actives dans l'économie spatiale (fabricants de satellites, lanceurs, équipements de communication, tourisme spatial).",
      whyInteresting: "Seul ETF UCITS dédié à l'économie spatiale au sens large plutôt qu'à un seul acteur. Thème porté par la baisse des coûts de lancement et la multiplication des usages commerciaux (télécoms, observation Terre, défense).",
      whatToKnow: "Univers d'investissement restreint (25 valeurs) donc concentration plus forte que les grands indices. Secteur jeune et volatil, plusieurs sociétés en phase de forte croissance sans profitabilité établie. Pas de PEA.",
      verdict: "Une exposition très ciblée à l’économie spatiale, avec peu de recul sur plusieurs entreprises du secteur.",
      question: "Quelles activités spatiales voudrais-tu réellement détenir : satellites, lanceurs ou équipements ?"
    },

    // ---------- STRATÉGIQUES ----------
    {
      id: "dividendes",
      category: "Stratégiques",
      name: "SPDR S&P US Dividend Aristocrats UCITS ETF",
      tickers: ["USDV"],
      isNew: false,
      isin: "IE00B6YX5D40",
      ter: "0,35%",
      positions: "~120 positions",
      aum: "~3,4 Md€",
      lastVerified: "25/08/2026",
      distribution: "Distribuant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le S&P High Yield Dividend Aristocrats, des entreprises américaines ayant augmenté leur dividende chaque année depuis au moins 20 ans. Sélection dominée par la consommation, l'industrie et la santé plutôt que par la tech.",
      whyInteresting: "Revenu régulier et croissant, versé sous forme de dividendes trimestriels. La sélection filtre naturellement des entreprises financièrement solides et disciplinées sur le long terme.",
      whatToKnow: "Sous-pondère fortement la tech, donc sous-performe souvent en marché haussier tiré par la croissance. Distribuant : fiscalité à surveiller en compte-titres (flat tax à chaque versement). Pas de PEA.",
      verdict: "Une sélection de sociétés américaines ayant augmenté leur dividende pendant au moins vingt ans. La régularité du versement ne garantit pas le rendement total.",
      question: "Tu regardes d’abord le dividende versé ou la performance totale de ton placement ?"
    },
    {
      id: "covered-call",
      category: "Stratégiques",
      name: "Global X Nasdaq 100 Covered Call UCITS ETF",
      tickers: ["QYLE"],
      isNew: false,
      isin: "IE00BM8R0J59",
      ter: "0,45%",
      positions: "~100 positions",
      aum: "~780 M€",
      lastVerified: "25/08/2026",
      distribution: "Distribuant (mensuel)",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique avec overlay d'options",
      whatIs: "Réplique le Nasdaq-100 tout en vendant systématiquement des options d'achat (covered calls) sur l'indice pour générer un revenu. Combine les 100 valeurs du Nasdaq avec une stratégie de vente d'options mensuelle.",
      whyInteresting: "Génère un rendement élevé et régulier, souvent entre 8% et 12% par an distribué mensuellement — utile pour qui cherche un complément de revenu plutôt qu'une pure plus-value.",
      whatToKnow: "Le rendement élevé plafonne la performance en cas de forte hausse du Nasdaq : la stratégie sacrifie une partie du potentiel de hausse contre le revenu immédiat. Fiscalité des distributions à surveiller. Produit plus complexe qu'un tracker classique, pas de PEA.",
      verdict: "Des distributions régulières en échange d’une partie du potentiel de hausse du Nasdaq-100. À comparer avec la détention directe de l’indice.",
      question: "Accepterais-tu de limiter la hausse possible pour recevoir des distributions mensuelles ?"
    },
    {
      id: "low-volatility",
      category: "Stratégiques",
      name: "iShares Edge MSCI World Minimum Volatility UCITS ETF",
      tickers: ["MVOL"],
      isNew: false,
      isin: "IE00B8FHGS14",
      ter: "0,30%",
      positions: "~300 positions",
      aum: "~2,3 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique le MSCI World Minimum Volatility Index, qui sélectionne et pondère les titres du MSCI World pour minimiser la volatilité globale du portefeuille. Sur-pondère la santé et les biens de consommation défensifs, sous-pondère la tech et l'énergie.",
      whyInteresting: "Amortit les baisses de marché grâce à une sélection de valeurs moins volatiles. Utile pour un profil plus prudent ou proche d'un objectif à horizon court, avec historiquement une bonne performance ajustée du risque.",
      whatToKnow: "Sous-performe en marché haussier fort, car il rate une partie des rallyes tech. Frais légèrement supérieurs à un tracker classique. Pas de PEA.",
      verdict: "Un ETF World sélectionné pour réduire les fluctuations. Il peut quand même baisser et sa composition s’éloigne de l’indice classique.",
      question: "Tu accepterais de t’écarter du MSCI World pour chercher des variations moins fortes ?"
    },
    {
      id: "value",
      category: "Stratégiques",
      name: "iShares Edge MSCI World Value Factor UCITS ETF",
      tickers: ["IWVL", "WVAL"],
      isNew: false,
      isin: "IE00BP3QZB59",
      ter: "0,25%",
      positions: "~350 positions",
      aum: "~6,1 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique le MSCI World Enhanced Value Index, qui sélectionne les entreprises décotées par rapport à leurs fondamentaux (PER bas, price-to-book bas). Sur-pondère la finance, l'énergie et l'industrie, sous-pondère la tech chère.",
      whyInteresting: "Pari sur une rotation value après plus d'une décennie dominée par la croissance et la tech. Historiquement, les stratégies value ont tendance à surperformer sur longues périodes après des excès de valorisation growth.",
      whatToKnow: "A largement sous-performé le marché global depuis 2010. Le timing d'une rotation value reste incertain et peut prendre des années à se matérialiser. Pas de PEA.",
      verdict: "Il privilégie les sociétés jugées moins chères selon les critères de l’indice. Une valorisation basse ne promet pas un rebond.",
      question: "Tu serais prêt à garder ce biais value plusieurs années s’il fait moins bien que le World ?"
    },
    {
      id: "small-caps",
      category: "Stratégiques",
      name: "iShares MSCI World Small Cap UCITS ETF",
      tickers: ["WSML"],
      isNew: false,
      isin: "IE00BF4RFH31",
      ter: "0,35%",
      positions: "~3 400 positions",
      aum: "~7,7 Md€",
      lastVerified: "25/08/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique le MSCI World Small Cap Index, environ 3 400 petites capitalisations des marchés développés. Extrêmement diversifié : aucune ligne individuelle ne dépasse 0,5% du fonds.",
      whyInteresting: "Exposition à un segment qui a historiquement délivré une prime de taille sur longue période. Bonne diversification par rapport aux large caps qui dominent la plupart des indices classiques.",
      whatToKnow: "Plus volatil et moins liquide que les large caps. Sous-performe souvent en période de resserrement du crédit, les small caps étant plus sensibles aux taux d'intérêt. Pas de PEA.",
      verdict: "Il complète un World classique avec de petites entreprises des marchés développés. Leur taille apporte une autre exposition, avec davantage de variations possibles.",
      question: "Si tu ajoutes des small caps à ton World, quel poids leur donnerais-tu ?"
    },
    // Ajouté le 08/09/2026 (audit "densité", 2 facteurs manquants dans la catégorie Stratégiques :
    // qualité, momentum). Attention lors de la recherche : la 1re requête sur le facteur Quality a
    // renvoyé par erreur l'ISIN du fonds Momentum (IE00BP3QZ825) — repéré et corrigé avant publication
    // en revérifiant chaque ISIN individuellement plutôt que de faire confiance à un premier résultat.
    // Encours du Momentum : 1re requête a donné 2,44 Md CHF (incohérent avec 2 requêtes suivantes,
    // convergentes à 5,3-6,0 Md€/$) — écarté comme donnée isolée non recoupée, retenu ~5,3 Md€
    // (justETF, confirmé par un chiffre de holdings daté du même jour).
    // TER corrigé le 10/09/2026 (audit "cohérence inter-outils") : 0,30% publié initialement le
    // 08/09/2026 était erroné — comparaison avec le Comparateur d'indices (même ISIN, 0,25% déjà
    // en place) a révélé la divergence, tranchée par 2 nouvelles requêtes indépendantes (justETF,
    // Fidelity, Morningstar convergent toutes sur 0,25%) plutôt qu'en se fiant à la donnée déjà en
    // place — l'écart initial venait probablement d'une confusion avec un TER "brut" avant remise.
    // Encours aligné à ~5,4 Md€ à la même occasion (nouvelle requête : 5 434 M€/£4 540 M/5,79 Md$,
    // convergents entre devises), plutôt que le ~6,3 Md$ initial issu de la même recherche fautive.
    {
      id: "quality",
      category: "Stratégiques",
      name: "iShares Edge MSCI World Quality Factor UCITS ETF (Acc)",
      tickers: ["IWQU", "IWFQ"],
      isNew: true,
      isin: "IE00BP3QZ601",
      ter: "0,25%",
      positions: "290 positions",
      aum: "~5,4 Md€",
      lastVerified: "10/09/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique le MSCI World Quality Factor, environ 290 entreprises sélectionnées pour leur rentabilité élevée, leur endettement maîtrisé et la stabilité de leurs résultats. Top positions : Nvidia, Apple, Microsoft, Visa, Meta — les mêmes géants que le World, mais filtrés sur des critères de qualité financière plutôt que sur la seule capitalisation.",
      whyInteresting: "Historiquement, le facteur qualité a montré une meilleure résistance dans les phases de baisse tout en participant aux hausses — un profil rendement/risque souvent plus favorable qu'un tracker classique sur longue période.",
      whatToKnow: "Ressemble beaucoup à un MSCI World dans sa composition (mêmes méga-caps en tête), donc l'effet diversifiant reste limité. Frais plus élevés qu'un tracker classique (0,25% contre 0,12-0,20%). Pas de PEA.",
      verdict: "Un filtre de solidité appliqué aux grandes actions mondiales. Avant de l’ajouter, compare ses premières positions à celles de ton ETF World.",
      question: "Tu vois assez de différence avec le World classique pour payer ce filtre supplémentaire ?"
    },
    {
      id: "momentum",
      category: "Stratégiques",
      name: "iShares Edge MSCI World Momentum Factor UCITS ETF (Acc)",
      tickers: ["IWMO"],
      isNew: true,
      isin: "IE00BP3QZ825",
      ter: "0,30%",
      positions: "434 positions",
      aum: "~5,3 Md€",
      lastVerified: "08/09/2026",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique le MSCI World Momentum Factor, environ 434 entreprises sélectionnées pour leur tendance de prix haussière récente — l'indice \"achète ce qui monte\" et rééquilibre régulièrement. Top positions récentes : Micron, Nvidia, Broadcom, Alphabet, ASML.",
      whyInteresting: "Stratégie qui capte mécaniquement les tendances de marché en cours plutôt que de parier sur un secteur ou une thèse précise. Rééquilibrages fréquents (semestriels) pour rester aligné sur les valeurs qui performent le mieux à l'instant T.",
      whatToKnow: "Rotation sectorielle fréquente : le fonds peut changer significativement de visage d'un semestre à l'autre selon ce qui \"monte\" à ce moment-là. Frais plus élevés qu'un tracker classique (0,30%). Peut accentuer les excès de marché (achète après la hausse, vend après la baisse). Pas de PEA.",
      verdict: "Il renforce les titres dont la tendance récente est favorable. Cette règle peut se retourner lorsque les leaders changent rapidement.",
      question: "Tu pourrais conserver un ETF momentum après un retournement brutal des valeurs en tête ?"
    },

    // ---------- OBLIGATAIRES ----------
    {
      id: "obligations-etat",
      category: "Obligataires",
      name: "iShares Core Euro Government Bond UCITS ETF (Dist)",
      tickers: ["SEGA"],
      isNew: false,
      isin: "IE00B4WXJJ64",
      ter: "0,07%",
      // iShares, fiche IE00B4WXJJ64, données au 22/09/2026 : 552 lignes, duration 6,70 ans.
      // https://www.ishares.com/uk/professionals/en/products/251740/ishares-euro-government-bond-ucits-etf
      positions: "552 positions",
      aum: "~5,3 Md€",
      lastVerified: "22/09/2026",
      distribution: "Distribuant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique par échantillonnage",
      whatIs: "Cet ETF détient des obligations émises par plusieurs États de la zone euro, avec des échéances différentes. Sa duration effective était d’environ 6,7 ans en septembre 2026 : c’est le chiffre à regarder pour comprendre sa réaction aux taux.",
      whyInteresting: "Il ajoute des obligations à un portefeuille composé surtout d’actions, pour 0,07 % de frais annuels. Cela peut aider à répartir les risques, même si les obligations ne protègent pas lors de toutes les baisses boursières.",
      whatToKnow: "Avec une duration d’environ 6,7 ans, une hausse parallèle des taux d’un point pourrait entraîner une baisse approximative de 6,7 % du prix, toutes choses égales par ailleurs. Il porte aussi le risque des États présents dans l’indice et n’est pas éligible au PEA.",
      verdict: "Utile si tu veux des obligations d’État en portefeuille, mais à choisir en comprenant d’abord sa sensibilité aux taux.",
      question: "Pour ta poche prudente, tu préfères ces obligations ou un fonds à duration plus courte ?"
    },
    {
      id: "high-yield",
      category: "Obligataires",
      name: "iShares Euro High Yield Corporate Bond UCITS ETF (Dist)",
      tickers: ["IHYA", "EHYA"],
      isNew: false,
      isin: "IE00B66F4759",
      ter: "0,50%",
      positions: "~500 positions",
      aum: "~5,8 Md€",
      lastVerified: "25/08/2026",
      distribution: "Distribuant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique un indice d'obligations d'entreprises notées \"spéculatives\" (BB et en dessous), libellées en euros. Diversifié sur environ 500 émetteurs de secteurs variés.",
      whyInteresting: "Rendement nettement supérieur aux obligations d'État ou investment grade — le coupon plus élevé compense le risque de défaut. Diversifié sur un grand nombre d'émetteurs, ce qui limite l'impact d'un défaut isolé.",
      whatToKnow: "Risque de crédit réel : les défauts augmentent en période de récession. Plus corrélé aux actions que les obligations d'État en période de stress de marché. Frais plus élevés que le segment government bonds. Pas de PEA.",
      verdict: "Des obligations d’entreprises offrant davantage de rendement, avec un risque de défaut plus élevé. Elles ne jouent pas le même rôle que des obligations d’État.",
      question: "Quel risque de baisse accepterais-tu pour chercher plus de revenus obligataires ?"
    },
    // Revérifié le 14/09/2026 (audit "outils", complétion des 3 fiches obligataires sans date de
    // sourcing documentée) : ISIN, TER, encours et éligibilité PEA/CTO confirmés exacts via justETF/
    // iShares (Fund NAV 13 229,54 M€ au 11/09/2026, cohérent avec les 13,36 Md€ déjà en place, écart
    // de simple fluctuation de NAV). Aucune correction nécessaire.
    {
      id: "corp-bond-ig",
      category: "Obligataires",
      name: "iShares Core € Corp Bond UCITS ETF (Dist)",
      tickers: ["IEAC"],
      isNew: true,
      isin: "IE00B3F81R35",
      lastVerified: "14/09/2026",
      ter: "0,09%",
      positions: "~3 000 positions",
      aum: "~13,36 Md€",
      distribution: "Distribuant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique un indice large d'obligations d'entreprises \"investment grade\" (notées BBB- et au-dessus) libellées en euros, tous secteurs confondus.",
      whyInteresting: "Un des ETF obligataires investment grade les moins chers du marché (0,09%), avec une très large diversification (~3 000 lignes). Version distribuante : les coupons sont versés, pas capitalisés.",
      whatToKnow: "Sensible aux taux d'intérêt, moins qu'une obligation d'État de duration équivalente mais le risque reste réel en cas de hausse des taux. Version distribuante donc fiscalement moins efficace qu'une version capitalisante en dehors d'une enveloppe défiscalisée. Pas de PEA.",
      verdict: "Des obligations d’entreprises bien notées pour diversifier la poche obligataire. La qualité de crédit n’efface pas le risque de taux.",
      question: "Pour tes obligations, tu privilégierais les entreprises bien notées ou les États ?"
    },
    // Revérifié le 14/09/2026 (audit "outils", complétion des 3 fiches obligataires sans date de
    // sourcing documentée) : ISIN, TER et éligibilité PEA/CTO confirmés exacts. Encours CORRIGÉ :
    // ~1,37 Md€ -> ~1,59 Md€ (justETF, fonds à 1 592 M€), l'ancienne valeur sous-estimait la
    // croissance réelle du fonds sur ce segment high yield capitalisant.
    {
      id: "high-yield-acc",
      category: "Obligataires",
      name: "iShares € High Yield Corp Bond UCITS ETF (Acc)",
      tickers: ["HIGH"],
      isNew: true,
      isin: "IE00BF3N7094",
      lastVerified: "14/09/2026",
      ter: "0,50%",
      positions: "~500 positions",
      aum: "~1,59 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique",
      whatIs: "Version capitalisante de l'exposition high yield en euros : obligations d'entreprises notées \"spéculatives\" (BB et en dessous), coupons réinvestis automatiquement.",
      whyInteresting: "Même rendement/risque que le high yield distribuant déjà présent dans cette catégorie, mais capitalisation automatique des coupons — plus adapté à une logique de capitalisation long terme hors PEA.",
      whatToKnow: "Risque de crédit réel, plus corrélé aux actions que l'investment grade en période de stress. Encours nettement plus petit que la version distribuante du même segment. Pas de PEA.",
      verdict: "La version capitalisante du crédit à haut rendement. Les intérêts sont réinvestis dans le fonds, mais le risque de crédit reste le même.",
      question: "Sur du high yield, tu veux des distributions ou préfères-tu leur réinvestissement automatique ?"
    },
    // Revérifié le 14/09/2026 (audit "outils", complétion des 3 fiches obligataires sans date de
    // sourcing documentée) : ISIN, TER et éligibilité PEA/CTO confirmés exacts. Encours NON TRANCHÉ :
    // justETF donne 274 M£ (~350-390 M$ selon conversion), cohérent avec les ~407 M$ déjà en place ;
    // une autre requête a renvoyé 5,46 Md$ mais accolée dans le même résultat à un ISIN différent
    // (IE00B5M4WH52, un fonds jumeau sans le qualificatif "USD (Acc)") — écarté comme probable
    // confusion de part plutôt que retenu, WebFetch étant bloqué dans ce sandbox pour trancher via la
    // fiche officielle. Valeur conservée (cohérente avec la source la mieux attribuée à cet ISIN
    // précis), même principe que l'écart non tranché sur oblig_etat_eur_short/MSCI Japan IMI.
    {
      id: "em-local-bond",
      category: "Obligataires",
      name: "iShares J.P. Morgan EM Local Govt Bond UCITS ETF (Acc)",
      tickers: ["EMGA"],
      isNew: true,
      isin: "IE00BFZPF546",
      lastVerified: "14/09/2026",
      ter: "0,50%",
      positions: "~200 positions",
      aum: "~407 M$",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique",
      whatIs: "Réplique un indice de dette d'État de pays émergents, émise en devise locale (et non en dollar) : Brésil, Mexique, Afrique du Sud, Indonésie, Inde, etc.",
      whyInteresting: "Diversification à la fois obligataire et devises : expose à la fois aux taux et aux monnaies émergentes, avec un rendement généralement supérieur à la dette d'État développée.",
      whatToKnow: "Double risque : risque de crédit souverain émergent ET risque de change (une devise émergente qui se déprécie efface le gain obligataire). Plus volatil qu'une obligation d'État développée. Pas de PEA.",
      verdict: "Une exposition à la fois aux obligations et aux devises émergentes. Une dépréciation des monnaies locales peut effacer les coupons reçus.",
      question: "Dans ta poche obligataire, prendrais-tu aussi le risque des monnaies émergentes ?"
    }
  ];
