// Bibliothèque de fiches ETF — reprise telle quelle de la session d'origine (contenu pré-rédigé,
// données stockées en dur, aucune donnée de marché en temps réel). Modifie librement un champ
// (isin, ter, positions, aum, distribution, pea, cto, location, whatIs, whyInteresting,
// whatToKnow, verdict, question) sans rien casser ailleurs.

export const CATEGORY_ORDER = [
    "Cœur de portefeuille",
    "Sectoriels classiques",
    "Thématiques émergentes",
    "Spatial",
    "Stratégiques",
    "Obligataires"
  ];

export const CATEGORY_EMOJI = {
    "Cœur de portefeuille": "🔵",
    "Sectoriels classiques": "🟢",
    "Thématiques émergentes": "🟠",
    "Spatial": "🚀",
    "Stratégiques": "🟣",
    "Obligataires": "⚪"
  };

export const ETFS = [
    // ---------- CŒUR DE PORTEFEUILLE ----------
    {
      id: "msci-world",
      category: "Cœur de portefeuille",
      name: "Amundi MSCI World UCITS ETF",
      tickers: ["CW8", "LCWD"],
      isNew: false,
      isin: "LU1681043599",
      ter: "0,38%",
      positions: "1 500 positions",
      aum: "~9,8 Md€",
      distribution: "Capitalisant",
      pea: true,
      cto: true,
      location: "Luxembourg, réplication physique optimisée (échantillonnage)",
      whatIs: "Réplique le MSCI World, l'indice qui suit environ 1 500 grandes et moyennes capitalisations de 23 pays développés. Diversifié sur tous les secteurs, mais dominé par les États-Unis à hauteur de 70% environ, loin devant le Japon, le Royaume-Uni et la France. Top positions : Nvidia, Apple, Microsoft, Amazon, Meta — la tech américaine tire l'ensemble de l'indice.",
      whyInteresting: "Le \"one fund\" par excellence pour bâtir un portefeuille diversifié en une seule ligne. Perf tirée par la tech US ces dernières années : autour de +18% sur 1 an, et une progression solide depuis le lancement. Frais parmi les plus bas du marché pour ce niveau de diversification.",
      whatToKnow: "Diversifié en nombre de lignes, beaucoup moins en géographie : 70% USA, donc très corrélé au Nasdaq. Aucune small cap. Existe en version encore moins chère (SWDA, 0,20%) si les frais priment sur la simplicité PEA.",
      verdict: "Le socle par défaut d'un portefeuille long terme — simple et diversifié, mais très dépendant des USA.",
      question: "Le MSCI World, la base de ton portefeuille ou tu préfères construire ton allocation toi-même ?"
    },
    {
      id: "sp500",
      category: "Cœur de portefeuille",
      name: "Amundi S&P 500 UCITS ETF",
      tickers: ["500", "PE500"],
      isNew: false,
      isin: "FR0010912576",
      ter: "0,15%",
      positions: "500 positions",
      aum: "~2,9 Md€",
      distribution: "Capitalisant",
      pea: true,
      cto: true,
      location: "France, réplication synthétique (swap)",
      whatIs: "Réplique le S&P 500, l'indice des 500 plus grandes capitalisations cotées aux États-Unis. Fortement pondéré tech : Apple, Nvidia, Microsoft, Amazon et Alphabet pèsent à eux cinq plus d'un quart de l'indice. 100% USA, tous secteurs représentés mais la tech domine largement.",
      whyInteresting: "Le benchmark le plus suivi au monde, avec une performance historique solide sur longue période. Version PEA-éligible grâce à la réplication synthétique — fiscalité avantageuse pour un investisseur français. Perf autour de +20% sur 1 an sur cette ligne.",
      whatToKnow: "100% USA donc risque de change EUR/USD non couvert. Concentration tech forte. Réplication synthétique : risque de contrepartie généralement bien collatéralisé, mais à comprendre avant d'investir. Aucune diversification internationale.",
      verdict: "Le pari sur l'exceptionnalisme américain, en direct et éligible PEA.",
      question: "Toujours confiance dans la surperformance US ou tu commences à diversifier ailleurs ?"
    },
    {
      id: "nasdaq100",
      category: "Cœur de portefeuille",
      name: "Amundi Nasdaq-100 UCITS ETF",
      tickers: ["ANX", "PUST"],
      isNew: false,
      isin: "LU1681038243",
      ter: "0,23%",
      positions: "100 positions",
      aum: "~1,66 Md€",
      distribution: "Capitalisant",
      pea: true,
      cto: true,
      location: "France, réplication synthétique (swap)",
      whatIs: "Réplique le Nasdaq-100, les 100 plus grosses valeurs non-financières cotées au Nasdaq. Ultra tech : Nvidia, Apple, Microsoft, Broadcom, Amazon en tête. Quasi aucune banque, aucune valeur pétrolière — un pari pur sur la croissance et la technologie américaine.",
      whyInteresting: "Exposition concentrée aux entreprises les plus innovantes de la cote US, moteur de la hausse boursière depuis plus d'une décennie. Perf forte portée par l'IA : au-delà de +25% sur 1 an sur les bons millésimes. PEA-éligible via la réplication synthétique.",
      whatToKnow: "Zéro diversification sectorielle réelle — c'est un pari tech assumé, pas un fonds \"large\". Volatilité plus élevée que le S&P 500. Risque de change non couvert. Correction sévère possible en cas de dégonflement des valorisations tech.",
      verdict: "Le pari concentré sur la croissance tech américaine, plus offensif que le S&P 500.",
      question: "Le Nasdaq, trop concentré sur quelques géants ou justement là où il faut être ?"
    },
    {
      id: "eurostoxx50",
      category: "Cœur de portefeuille",
      name: "Amundi Euro Stoxx 50 UCITS ETF",
      tickers: ["C50", "CE9"],
      isNew: false,
      isin: "LU1681043010",
      ter: "0,15%",
      positions: "50 positions",
      aum: "~5,2 Md€",
      distribution: "Capitalisant",
      pea: true,
      cto: true,
      location: "Luxembourg, réplication physique intégrale",
      whatIs: "Réplique l'Euro Stoxx 50, les 50 plus grandes capitalisations de la zone euro. Top positions : LVMH, ASML, SAP, TotalEnergies, Siemens. Un mix de luxe, de tech européenne, d'énergie et d'industrie, très différent de la composition d'un indice américain.",
      whyInteresting: "Exposition pure à la zone euro, éligible PEA au meilleur prix du marché (0,15% de frais). Bon complément pour rééquilibrer un portefeuille trop USA-centré. Sensible aux cycles de taux de la BCE.",
      whatToKnow: "Seulement 50 titres : concentration forte sur quelques secteurs (luxe, banques, industrie). Croissance historiquement plus lente que le S&P 500 sur longue période. Peu d'exposition à la tech pure.",
      verdict: "Le rééquilibrage domestique pour ne pas être 100% exposé aux marchés américains.",
      question: "Zone euro boudée ou sous-évaluée à tes yeux en ce moment ?"
    },
    {
      id: "msci-em",
      category: "Cœur de portefeuille",
      name: "iShares Core MSCI EM IMI UCITS ETF",
      tickers: ["EMIM"],
      isNew: false,
      isin: "IE00BKM4GZ66",
      ter: "0,18%",
      positions: "~3 000 positions",
      aum: "~25,4 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée (échantillonnage)",
      whatIs: "Réplique le MSCI Emerging Markets IMI, environ 3 000 valeurs de pays émergents toutes tailles confondues. Chine, Taïwan, Inde et Corée du Sud en tête. Top positions : Taiwan Semiconductor, Tencent, Samsung, Alibaba — un mix de tech asiatique et de conglomérats locaux.",
      whyInteresting: "Diversification hors marchés développés, exposition à la croissance démographique et technologique de l'Asie émergente et de l'Inde. Valorisations globalement plus basses que sur les marchés américains, marge de rattrapage potentielle.",
      whatToKnow: "Forte dépendance à la Chine (risque géopolitique, gouvernance d'entreprise, régulation). Volatilité plus élevée que les marchés développés. Pas de PEA. Multiples devises non couvertes contre l'euro.",
      verdict: "Le pari sur la croissance émergente — plus risqué et plus volatil que les marchés développés.",
      question: "Les émergents : sous-pondérés dans ton portefeuille ou tu évites carrément ?"
    },

    // ---------- SECTORIELS CLASSIQUES ----------
    {
      id: "semiconducteurs",
      category: "Sectoriels classiques",
      name: "iShares MSCI Global Semiconductors UCITS ETF",
      tickers: ["SEMI"],
      isNew: false,
      isin: "IE000U9J6270",
      ter: "0,45%",
      positions: "~30 positions",
      aum: "~2,3 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le MSCI ACWI IMI Semiconductors & Semiconductor Equipment. Concentré sur les fabricants de puces et équipementiers mondiaux : Nvidia, TSMC, Broadcom, ASML, AMD en tête. C'est le maillon matériel de toute la chaîne de valeur IA.",
      whyInteresting: "Exposition directe au boom de l'IA côté infrastructure physique (GPU, fonderies, équipements de gravure). Performance explosive tirée par la demande en puces : largement au-dessus de +30% sur 1 an sur les bons millésimes.",
      whatToKnow: "Très concentré sur environ 30 titres, dépendant de quelques géants (Nvidia, TSMC). Secteur cyclique par nature (cycles de stocks des semi-conducteurs). Forte volatilité, pas de PEA.",
      verdict: "Le pari le plus direct sur l'infrastructure matérielle de l'IA, très cyclique.",
      question: "Nvidia et les puces : la martingale de la décennie ou une bulle en formation ?"
    },
    {
      id: "sante-biotech",
      category: "Sectoriels classiques",
      name: "iShares Nasdaq US Biotechnology UCITS ETF",
      tickers: ["BTEK", "QBIO"],
      isNew: false,
      isin: "IE00BYXG2H39",
      ter: "0,35%",
      positions: "~200 positions",
      aum: "~600 M€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le Nasdaq Biotechnology Index, environ 200 entreprises biotech et pharma cotées au Nasdaq. Top positions : Amgen, Gilead, Vertex, Regeneron — un mix de biotechs innovantes et de laboratoires déjà établis.",
      whyInteresting: "Exposition à l'innovation médicale (thérapies géniques, oncologie, maladies rares), secteur défensif par nature puisque la santé n'est pas une dépense discrétionnaire. Bonne diversification sectorielle par rapport à un portefeuille tech-centré.",
      whatToKnow: "Volatilité liée aux résultats d'essais cliniques et aux décisions de la FDA — des annonces qui font bouger une ligne de +/-20% en une séance. Sensible aux taux d'intérêt. Pas de PEA, cycles de développement longs.",
      verdict: "Le pari défensif-innovant, entre valeurs refuges pharma et paris biotech à forte volatilité.",
      question: "La santé, le secteur le plus sous-estimé de ton portefeuille ?"
    },
    {
      id: "energie",
      category: "Sectoriels classiques",
      name: "Amundi MSCI World Energy UCITS ETF",
      tickers: ["WNRG"],
      isNew: false,
      isin: "LU1900068328",
      ter: "0,30%",
      positions: "~100 positions",
      aum: "~400 M€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Luxembourg, réplication physique optimisée",
      whatIs: "Réplique le MSCI World Energy, environ 100 entreprises mondiales du secteur pétrole, gaz et énergie. Top positions : ExxonMobil, Chevron, Shell, TotalEnergies — les grandes majors énergétiques occidentales.",
      whyInteresting: "Exposition aux majors de l'énergie fossile, avec des dividendes historiquement généreux sur ce secteur. Fonctionne souvent comme une couverture naturelle contre l'inflation énergétique et les tensions géopolitiques sur le pétrole.",
      whatToKnow: "Secteur cyclique, très dépendant du prix du baril. En décalage avec la transition énergétique (risque réglementaire à moyen terme). Concentré sur quelques majors. Pas de PEA.",
      verdict: "Le pari contrariant sur les énergies fossiles, cyclique et sensible aux cours du brut.",
      question: "Encore de la place pour le pétrole dans un portefeuille aujourd'hui ?"
    },
    {
      id: "defense",
      category: "Sectoriels classiques",
      name: "VanEck Defense UCITS ETF",
      tickers: ["DFNS", "DFND"],
      isNew: false,
      isin: "IE000YYE6WK5",
      ter: "0,55%",
      positions: "~30 positions",
      aum: "~6,8 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le MarketVector Global Defense Index, un panier d'entreprises mondiales de défense et d'armement. Top positions : Palantir, RTX, Lockheed Martin, Rheinmetall, Thales — un mix USA-Europe centré sur les grands programmes militaires.",
      whyInteresting: "Thème porté par la hausse durable des budgets militaires (réarmement européen, tensions OTAN). Performance forte depuis le lancement, secteur peu corrélé aux cycles économiques classiques puisque les commandes sont publiques et pluriannuelles.",
      whatToKnow: "Question éthique à trancher soi-même avant d'investir. Concentré sur une trentaine de titres. Dépendant des budgets publics et de la géopolitique — un changement de doctrine peut peser lourd. Pas de PEA, frais élevés.",
      verdict: "Le pari géopolitique sur le réarmement mondial, à la fois porteur et clivant éthiquement.",
      question: "Investir dans la défense : ligne rouge ou simple lecture réaliste du monde actuel ?"
    },
    {
      id: "cybersecurite",
      category: "Sectoriels classiques",
      name: "L&G Cyber Security UCITS ETF",
      tickers: ["ISPY"],
      isNew: false,
      isin: "IE00BYPLS672",
      ter: "0,69%",
      positions: "~30 positions",
      aum: "~500 M€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique l'ISE Cyber Security Select Index, une trentaine de pure players de la cybersécurité. Top positions : Palo Alto Networks, CrowdStrike, Fortinet, Cisco — les principaux fournisseurs de solutions de protection numérique.",
      whyInteresting: "Thème structurel porté par la hausse continue des cyberattaques et la digitalisation de tous les secteurs. Demande peu cyclique : les budgets cybersécurité sont rarement coupés, même en période de restriction budgétaire.",
      whatToKnow: "Concentré sur une trentaine de titres, valorisations tech souvent tendues. Frais parmi les plus élevés du segment thématique (0,69%). Pas de PEA.",
      verdict: "Le pari structurel sur une dépense qui ne baisse jamais, même en récession.",
      question: "La cybersécurité, thème le plus sous-évalué du marché selon toi ?"
    },
    {
      id: "eau",
      category: "Sectoriels classiques",
      name: "Amundi Water UCITS ETF",
      tickers: ["WAT"],
      isNew: false,
      isin: "FR0010527275",
      ter: "0,60%",
      positions: "~30 positions",
      aum: "~700 M€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "France, réplication physique intégrale",
      whatIs: "Réplique le World Water Index, des entreprises liées au traitement, à la distribution et à la gestion de l'eau. Top positions : American Water Works, Veolia, Xylem, Ecolab — un mix d'utilities et d'équipementiers industriels.",
      whyInteresting: "Thème défensif porté par une ressource rare et non substituable, avec une demande structurellement croissante (urbanisation, stress hydrique, vieillissement des infrastructures).",
      whatToKnow: "Secteur peu volatil mais croissance plus lente qu'un thème tech. Forte pondération utilities/industrie, peu de tech pure. Frais élevés (0,60%) pour un profil aussi défensif. Pas de PEA.",
      verdict: "Le thème le plus défensif de la thématique ESG, croissance lente mais quasi certaine.",
      question: "L'eau, la ressource la plus sous-investie de la prochaine décennie ?"
    },
    {
      id: "luxe",
      category: "Sectoriels classiques",
      name: "Amundi S&P Global Luxury UCITS ETF",
      tickers: ["GLUX"],
      isNew: false,
      isin: "LU1681041995",
      ter: "0,35%",
      positions: "~80 positions",
      aum: "~300 M€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Luxembourg, réplication physique optimisée",
      whatIs: "Réplique le S&P Global Luxury Index, des entreprises mondiales du luxe et des biens haut de gamme. Top positions : LVMH, Hermès, L'Oréal, Ferrari, Richemont — les grandes maisons de luxe européennes et quelques acteurs mondiaux.",
      whyInteresting: "Exposition à la classe moyenne mondiale montante et à la résilience de la demande ultra-riche. Des marques avec un fort pricing power, capables de répercuter l'inflation sans perdre leurs clients.",
      whatToKnow: "Très corrélé à la consommation chinoise — un ralentissement à Pékin se ressent immédiatement sur la ligne. Cyclique malgré l'image \"premium\". Valorisations élevées. Pas de PEA.",
      verdict: "Le pari sur le pricing power des marques, mais très dépendant du consommateur chinois.",
      question: "Le luxe, valeur refuge ou trop dépendant de la Chine aujourd'hui ?"
    },

    // ---------- THÉMATIQUES ÉMERGENTES / NICHE ----------
    {
      id: "quantique",
      category: "Thématiques émergentes",
      name: "VanEck Quantum Computing UCITS ETF A",
      tickers: ["QUTM", "QNTM"],
      isNew: true,
      isin: "IE0007Y8Y157",
      ter: "0,55%",
      positions: "30 positions",
      aum: "~734 M€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Le premier ETF quantique lancé en Europe (mai 2025). Il réplique le MarketVector Global Quantum Leaders, un panier de 30 entreprises mondiales actives dans l'informatique quantique. Top positions : IonQ (12,2%), Intel (6,9%), D-Wave Quantum (6,3%), Infineon (5,7%), Nokia (5,4%). Mix de pure players quantiques et de géants tech qui investissent dans le domaine. 57% USA, 11,7% Allemagne, 7,4% Japon.",
      whyInteresting: "Une exposition à l'informatique quantique sans devoir choisir entre pure players et géants établis. Débuts encourageants : +39,43% sur 1 an, +49,04% depuis le lancement. Premier arrivé sur ce thème en Europe, le plus gros et liquide des ETF quantiques.",
      whatToKnow: "Très concentré : 30 positions, top 10 pèse 56,4% du fonds. Volatilité élevée (29,74%/an), chute déjà vue de -24,47% sur 1 an. Technologie encore balbutiante commercialement. Frais élevés (0,55%). Pas de PEA.",
      verdict: "Le pari le plus pointu sur une technologie encore embryonnaire, concentré sur 30 titres.",
      question: "Le quantique, tu y crois comme prochaine révolution tech ?"
    },
    {
      id: "ia",
      category: "Thématiques émergentes",
      name: "L&G Artificial Intelligence UCITS ETF",
      tickers: ["AIAI"],
      isNew: false,
      isin: "IE00BK5BCD43",
      ter: "0,49%",
      positions: "~80 positions",
      aum: "~1,5 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le ROBO Global Artificial Intelligence Index, des entreprises actives sur toute la chaîne de valeur de l'IA : infrastructure, logiciels, applications. Top positions : Nvidia, Microsoft, Palantir, ServiceNow, Nice — un mix d'infrastructure et de logiciel applicatif.",
      whyInteresting: "Exposition large à toute la chaîne de valeur IA, pas seulement aux puces. Performance portée par l'engouement pour l'IA générative depuis 2023, avec des progressions à deux chiffres sur 1 an.",
      whatToKnow: "Valorisations tendues sur beaucoup de lignes, risque de bulle sur certains segments applicatifs. Très corrélé au Nasdaq. Pas de PEA.",
      verdict: "L'exposition \"large\" à l'IA, moins concentrée que le pari pur sur les semi-conducteurs.",
      question: "L'IA, encore un cycle de croissance devant elle ou déjà dans les prix ?"
    },
    {
      id: "robotique",
      category: "Thématiques émergentes",
      name: "iShares Automation & Robotics UCITS ETF",
      tickers: ["RBOT"],
      isNew: false,
      isin: "IE00BYZK4552",
      ter: "0,40%",
      positions: "~120 positions",
      aum: "~4,5 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le iSTOXX FactSet Automation & Robotics Index, des entreprises liées à l'automatisation industrielle et à la robotique. Top positions : Nvidia, Fanuc, Intuitive Surgical, Keyence — mix de robotique industrielle et de robotique chirurgicale.",
      whyInteresting: "Thème porté par la relocalisation industrielle et la pénurie de main-d'œuvre qualifiée. Exposition diversifiée entre robotique industrielle classique et robotique médicale à forte marge.",
      whatToKnow: "Large diversification qui dilue l'effet \"pure play\" par rapport à un thème plus concentré. Cyclique, car dépendant de l'investissement industriel des entreprises. Pas de PEA.",
      verdict: "Le pari diversifié sur l'automatisation du monde physique.",
      question: "La robotique, le prochain grand thème après l'IA logicielle ?"
    },
    {
      id: "blockchain",
      category: "Thématiques émergentes",
      name: "iShares Blockchain Technology UCITS ETF",
      tickers: ["BLKC"],
      isNew: false,
      isin: "IE0007G8Y955",
      ter: "0,45%",
      positions: "~50 positions",
      aum: "~300 M€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique un indice d'entreprises liées à l'écosystème blockchain : mineurs de cryptomonnaies, plateformes d'échange, fournisseurs d'infrastructure. Top positions : Coinbase, Strategy (ex-MicroStrategy), Marathon Digital, Robinhood.",
      whyInteresting: "Exposition à l'écosystème crypto sans détenir directement de cryptomonnaies ni gérer de wallet. Forte corrélation au cycle bitcoin, mais via des actions cotées et un cadre réglementaire classique.",
      whatToKnow: "Très volatil, fortement corrélé au bitcoin. Certaines entreprises du panier sont elles-mêmes spéculatives (mineurs endettés). Pas de PEA, thème encore jeune sur le plan réglementaire.",
      verdict: "Le proxy actions pour jouer le cycle crypto sans détenir de coins.",
      question: "Les actions crypto, un moyen plus sage de jouer le bitcoin ou juste une autre forme de spéculation ?"
    },
    {
      id: "nucleaire",
      category: "Thématiques émergentes",
      name: "VanEck Uranium and Nuclear Technologies UCITS ETF",
      tickers: ["NUKL"],
      isNew: false,
      isin: "IE000M7V94V1",
      ter: "0,55%",
      positions: "~25 positions",
      aum: "~480 M€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le MarketVector Uranium & Nuclear Technologies Index : mines d'uranium, exploitants de centrales, équipementiers, et acteurs émergents de la fusion nucléaire. Top positions : Cameco, Constellation Energy, NuScale, Oklo.",
      whyInteresting: "Thème porté par la relance mondiale du nucléaire pour décarboner et sécuriser l'approvisionnement électrique — data centers IA compris. Diversifie entre mines d'uranium déjà rentables et paris technologiques sur la fusion.",
      whatToKnow: "Très corrélé au prix de l'uranium (cyclique et sensible aux décisions politiques). Les acteurs de la fusion sont encore pré-commerciaux, à des années voire des décennies de la rentabilité. Frais élevés, pas de PEA.",
      verdict: "Le pari sur la renaissance du nucléaire, entre mines d'uranium établies et paris technologiques sur la fusion.",
      question: "Le nucléaire, l'énergie qui va alimenter la révolution IA ?"
    },
    {
      id: "batteries-ve",
      category: "Thématiques émergentes",
      name: "L&G Battery Value-Chain UCITS ETF",
      tickers: ["BATT"],
      isNew: false,
      isin: "IE00BF0M2Z96",
      ter: "0,49%",
      positions: "~40 positions",
      aum: "~200 M€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique la Solactive Battery Value-Chain Index, toute la chaîne de valeur des batteries : extraction de lithium, fabricants de cellules, constructeurs de véhicules électriques. Top positions : Tesla, CATL, Albemarle, BYD.",
      whyInteresting: "Exposition à la transition vers l'électrique, diversifiée sur toute la chaîne de valeur (mines, cellules, constructeurs) plutôt que sur un seul maillon isolé.",
      whatToKnow: "Secteur en forte correction depuis 2022 : ralentissement de la demande VE en Europe, surcapacité de production en Chine. Volatil, encore loin de ses plus hauts. Pas de PEA.",
      verdict: "Le thème qui a le plus déçu depuis 2022, à contre-courant pour qui croit encore au rattrapage.",
      question: "Les batteries et le VE, le rebond est pour bientôt ou le thème est mort ?"
    },

    // ---------- SPATIAL ----------
    {
      id: "spatial",
      category: "Spatial",
      name: "VanEck Space Innovators UCITS ETF",
      tickers: ["JEDI"],
      isNew: true,
      isin: "IE000YU9K6K2",
      ter: "0,55%",
      positions: "25 positions",
      aum: "~1,9 Md$",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique",
      whatIs: "Réplique l'indice MarketVector Global Space Industry Screened : environ 25 entreprises actives dans l'économie spatiale (fabricants de satellites, lanceurs, équipements de communication, tourisme spatial).",
      whyInteresting: "Seul ETF UCITS dédié à l'économie spatiale au sens large plutôt qu'à un seul acteur. Thème porté par la baisse des coûts de lancement et la multiplication des usages commerciaux (télécoms, observation Terre, défense).",
      whatToKnow: "Univers d'investissement restreint (25 valeurs) donc concentration plus forte que les grands indices. Secteur jeune et volatil, plusieurs sociétés en phase de forte croissance sans profitabilité établie. Pas de PEA.",
      verdict: "Le pari pur sur l'économie spatiale, à réserver à une petite poche satellite du portefeuille.",
      question: "L'économie spatiale, le prochain grand thème ou encore trop tôt pour investir dessus ?"
    },

    // ---------- STRATÉGIQUES ----------
    {
      id: "dividendes",
      category: "Stratégiques",
      name: "SPDR S&P US Dividend Aristocrats UCITS ETF",
      tickers: ["USDV"],
      isNew: false,
      isin: "IE00B6YX5D40",
      ter: "0,35%",
      positions: "~120 positions",
      aum: "~2,2 Md€",
      distribution: "Distribuant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique le S&P High Yield Dividend Aristocrats, des entreprises américaines ayant augmenté leur dividende chaque année depuis au moins 20 ans. Sélection dominée par la consommation, l'industrie et la santé plutôt que par la tech.",
      whyInteresting: "Revenu régulier et croissant, versé sous forme de dividendes trimestriels. La sélection filtre naturellement des entreprises financièrement solides et disciplinées sur le long terme.",
      whatToKnow: "Sous-pondère fortement la tech, donc sous-performe souvent en marché haussier tiré par la croissance. Distribuant : fiscalité à surveiller en compte-titres (flat tax à chaque versement). Pas de PEA.",
      verdict: "Le choix \"rentier\" : stabilité et revenu régulier plutôt que croissance maximale.",
      question: "Les dividendes, stratégie de grand-père ou pilier sous-estimé d'un portefeuille ?"
    },
    {
      id: "covered-call",
      category: "Stratégiques",
      name: "Global X Nasdaq 100 Covered Call UCITS ETF",
      tickers: ["QYLE"],
      isNew: false,
      isin: "IE000OJ5TDZ1",
      ter: "0,45%",
      positions: "~100 positions",
      aum: "~150 M€",
      distribution: "Distribuant (mensuel)",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique avec overlay d'options",
      whatIs: "Réplique le Nasdaq-100 tout en vendant systématiquement des options d'achat (covered calls) sur l'indice pour générer un revenu. Combine les 100 valeurs du Nasdaq avec une stratégie de vente d'options mensuelle.",
      whyInteresting: "Génère un rendement élevé et régulier, souvent entre 8% et 12% par an distribué mensuellement — utile pour qui cherche un complément de revenu plutôt qu'une pure plus-value.",
      whatToKnow: "Le rendement élevé plafonne la performance en cas de forte hausse du Nasdaq : la stratégie sacrifie une partie du potentiel de hausse contre le revenu immédiat. Fiscalité des distributions à surveiller. Produit plus complexe qu'un tracker classique, pas de PEA.",
      verdict: "Le générateur de revenu mensuel, au prix d'un potentiel de hausse plafonné.",
      question: "Le covered call, le bon compromis revenu/performance ou une fausse bonne idée ?"
    },
    {
      id: "low-volatility",
      category: "Stratégiques",
      name: "iShares Edge MSCI World Minimum Volatility UCITS ETF",
      tickers: ["MVOL"],
      isNew: false,
      isin: "IE00B8FHGS14",
      ter: "0,30%",
      positions: "~300 positions",
      aum: "~2,5 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique le MSCI World Minimum Volatility Index, qui sélectionne et pondère les titres du MSCI World pour minimiser la volatilité globale du portefeuille. Sur-pondère la santé et les biens de consommation défensifs, sous-pondère la tech et l'énergie.",
      whyInteresting: "Amortit les baisses de marché grâce à une sélection de valeurs moins volatiles. Utile pour un profil plus prudent ou proche d'un objectif à horizon court, avec historiquement une bonne performance ajustée du risque.",
      whatToKnow: "Sous-performe en marché haussier fort, car il rate une partie des rallyes tech. Frais légèrement supérieurs à un tracker classique. Pas de PEA.",
      verdict: "Le choix défensif pour dormir tranquille, au prix d'un potentiel de hausse réduit.",
      question: "La basse volatilité, la bonne stratégie pour un marché nerveux comme aujourd'hui ?"
    },
    {
      id: "value",
      category: "Stratégiques",
      name: "iShares Edge MSCI World Value Factor UCITS ETF",
      tickers: ["IWVL", "WVAL"],
      isNew: false,
      isin: "IE00BP3QZB59",
      ter: "0,30%",
      positions: "~350 positions",
      aum: "~2 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique le MSCI World Enhanced Value Index, qui sélectionne les entreprises décotées par rapport à leurs fondamentaux (PER bas, price-to-book bas). Sur-pondère la finance, l'énergie et l'industrie, sous-pondère la tech chère.",
      whyInteresting: "Pari sur une rotation value après plus d'une décennie dominée par la croissance et la tech. Historiquement, les stratégies value ont tendance à surperformer sur longues périodes après des excès de valorisation growth.",
      whatToKnow: "A largement sous-performé le marché global depuis 2010. Le timing d'une rotation value reste incertain et peut prendre des années à se matérialiser. Pas de PEA.",
      verdict: "Le pari contrariant sur le retour en grâce des entreprises décotées.",
      question: "La value, le grand retour attendu depuis 10 ans — c'est pour cette fois ?"
    },
    {
      id: "small-caps",
      category: "Stratégiques",
      name: "iShares MSCI World Small Cap UCITS ETF",
      tickers: ["WSML"],
      isNew: false,
      isin: "IE00BF4RFH31",
      ter: "0,35%",
      positions: "~3 400 positions",
      aum: "~2,6 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique le MSCI World Small Cap Index, environ 3 400 petites capitalisations des marchés développés. Extrêmement diversifié : aucune ligne individuelle ne dépasse 0,5% du fonds.",
      whyInteresting: "Exposition à un segment qui a historiquement délivré une prime de taille sur longue période. Bonne diversification par rapport aux large caps qui dominent la plupart des indices classiques.",
      whatToKnow: "Plus volatil et moins liquide que les large caps. Sous-performe souvent en période de resserrement du crédit, les small caps étant plus sensibles aux taux d'intérêt. Pas de PEA.",
      verdict: "Le complément diversifiant pour ne pas être 100% large caps, plus volatil mais historiquement bien rémunéré.",
      question: "Les small caps, le pari de la décennie ou l'angle mort de ton portefeuille ?"
    },

    // ---------- OBLIGATAIRES ----------
    {
      id: "obligations-etat",
      category: "Obligataires",
      name: "iShares Core Euro Government Bond UCITS ETF",
      tickers: ["SEGA"],
      isNew: false,
      isin: "IE00B4WXJJ64",
      ter: "0,09%",
      positions: "~250 positions",
      aum: "~5,3 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique un indice d'obligations d'État de la zone euro, toutes échéances confondues. Émetteurs principaux : France, Allemagne, Italie, Espagne. Duration moyenne d'environ 8 ans.",
      whyInteresting: "Diversification par rapport aux actions, avec un rôle d'amortisseur en cas de baisse actions (historiquement — 2022 a montré que ce n'est jamais garanti). Frais parmi les plus bas du marché (0,09%).",
      whatToKnow: "Très sensible aux taux d'intérêt : une duration de ~8 ans signifie environ -8% si les taux montent d'un point. Rendement modeste en absolu. L'Italie pèse lourd dans le panier (risque souverain). Pas de PEA.",
      verdict: "L'amortisseur classique de portefeuille, sensible aux taux mais moins volatil que les actions.",
      question: "Les obligations d'État, encore un pilier de portefeuille ou trop peu rémunératrices aujourd'hui ?"
    },
    {
      id: "high-yield",
      category: "Obligataires",
      name: "iShares Euro High Yield Corporate Bond UCITS ETF",
      tickers: ["IHYA", "EHYA"],
      isNew: false,
      isin: "IE00B66F4759",
      ter: "0,50%",
      positions: "~500 positions",
      aum: "~4,2 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique optimisée",
      whatIs: "Réplique un indice d'obligations d'entreprises notées \"spéculatives\" (BB et en dessous), libellées en euros. Diversifié sur environ 500 émetteurs de secteurs variés.",
      whyInteresting: "Rendement nettement supérieur aux obligations d'État ou investment grade — le coupon plus élevé compense le risque de défaut. Diversifié sur un grand nombre d'émetteurs, ce qui limite l'impact d'un défaut isolé.",
      whatToKnow: "Risque de crédit réel : les défauts augmentent en période de récession. Plus corrélé aux actions que les obligations d'État en période de stress de marché. Frais plus élevés que le segment government bonds. Pas de PEA.",
      verdict: "Le compromis rendement/risque entre actions et obligations d'État, à réserver aux portefeuilles diversifiés.",
      question: "Le high yield, le bon compromis rendement/risque ou trop de risque de crédit caché ?"
    },
    {
      id: "corp-bond-ig",
      category: "Obligataires",
      name: "iShares Core € Corp Bond UCITS ETF (Dist)",
      tickers: ["IEAC"],
      isNew: true,
      isin: "IE00B3F81R35",
      ter: "0,09%",
      positions: "~3 000 positions",
      aum: "~13,36 Md€",
      distribution: "Distribuant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique intégrale",
      whatIs: "Réplique un indice large d'obligations d'entreprises \"investment grade\" (notées BBB- et au-dessus) libellées en euros, tous secteurs confondus.",
      whyInteresting: "Un des ETF obligataires investment grade les moins chers du marché (0,09%), avec une très large diversification (~3 000 lignes). Version distribuante : les coupons sont versés, pas capitalisés.",
      whatToKnow: "Sensible aux taux d'intérêt, moins qu'une obligation d'État de duration équivalente mais le risque reste réel en cas de hausse des taux. Version distribuante donc fiscalement moins efficace qu'une version capitalisante en dehors d'une enveloppe défiscalisée. Pas de PEA.",
      verdict: "Le cœur obligataire investment grade au coût le plus bas, pour qui veut du crédit d'entreprise plutôt que de la dette d'État.",
      question: "Le crédit investment grade, le juste milieu entre sécurité et rendement ?"
    },
    {
      id: "high-yield-acc",
      category: "Obligataires",
      name: "iShares € High Yield Corp Bond UCITS ETF (Acc)",
      tickers: ["HIGH"],
      isNew: true,
      isin: "IE00BF3N7094",
      ter: "0,50%",
      positions: "~500 positions",
      aum: "~1,37 Md€",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique",
      whatIs: "Version capitalisante de l'exposition high yield en euros : obligations d'entreprises notées \"spéculatives\" (BB et en dessous), coupons réinvestis automatiquement.",
      whyInteresting: "Même rendement/risque que le high yield distribuant déjà présent dans cette catégorie, mais capitalisation automatique des coupons — plus adapté à une logique de capitalisation long terme hors PEA.",
      whatToKnow: "Risque de crédit réel, plus corrélé aux actions que l'investment grade en période de stress. Encours nettement plus petit que la version distribuante du même segment. Pas de PEA.",
      verdict: "La version capitalisante du high yield pour qui privilégie la capitalisation automatique au versement de coupons.",
      question: "Capitalisant ou distribuant : quelle version du high yield colle à ta stratégie ?"
    },
    {
      id: "em-local-bond",
      category: "Obligataires",
      name: "iShares J.P. Morgan EM Local Govt Bond UCITS ETF (Acc)",
      tickers: ["EMGA"],
      isNew: true,
      isin: "IE00BFZPF546",
      ter: "0,50%",
      positions: "~200 positions",
      aum: "~5,54 Md$",
      distribution: "Capitalisant",
      pea: false,
      cto: true,
      location: "Irlande, réplication physique",
      whatIs: "Réplique un indice de dette d'État de pays émergents, émise en devise locale (et non en dollar) : Brésil, Mexique, Afrique du Sud, Indonésie, Inde, etc.",
      whyInteresting: "Diversification à la fois obligataire et devises : expose à la fois aux taux et aux monnaies émergentes, avec un rendement généralement supérieur à la dette d'État développée.",
      whatToKnow: "Double risque : risque de crédit souverain émergent ET risque de change (une devise émergente qui se déprécie efface le gain obligataire). Plus volatil qu'une obligation d'État développée. Pas de PEA.",
      verdict: "Le pari diversifiant sur la dette et les devises émergentes, à réserver à une petite poche satellite.",
      question: "La dette émergente en devise locale, la diversification qui manque à ton portefeuille obligataire ?"
    }
  ];
