// Banque de tweets à recycler — contenu initial repris tel quel du prototype HTML fourni le
// 23/09/2026 (banque-tweets.html, ~42 tweets réels déjà catégorisés), migré ici sans régénération.
// Pas de logique ici — cf. lib.js pour les fonctions pures (filtre/tri/cooldown).

export const MONTHS = ["Avril", "Mai", "Juin", "Juillet", "Août", "Septembre"]
export const CATEGORIES = [
  "Storytelling",
  "Simulation & chiffres",
  "Guide ETF",
  "Bilan patrimoine",
  "Engagement & débat",
  "Actu & humour",
]
export const FORMATS = ["Preuve vendredi soir", "Bilan de la semaine"]

// Sous-ensemble de CATEGORIES mis en avant visuellement (couleur "or" plutôt que "vert" dans le
// prototype d'origine) — repris tel quel, aucune règle nouvelle inventée ici.
export const GOLD_CATEGORIES = ["Guide ETF", "Actu & humour"]

// Un tweet est de nouveau disponible 45 jours après sa dernière publication.
export const COOLDOWN_DAYS = 45

export const TWEETS = [
  { id: 1, month: "Avril", category: "Storytelling", formats: ["Bilan de la semaine"], text: "Il y a 10 ans, je fumais clope sur clope, je sortais tous les week-ends et j'avais à peine 5 000 € sur mes comptes bancaires.\n\nPuis un jour, j'en ai eu marre. J'ai arrêté les conneries et j'ai appris à investir et à penser à long terme.\n\nAujourd'hui, j'ai dépassé les 70 000 €.\n\nMais le plus beau ? Ce n'est pas l'argent. C'est d'avoir repris le contrôle de ma vie. D'avoir prouvé que la discipline finit toujours par payer.\n\nRoad to 100k.\n\nEt toi, où en es-tu dans ton chemin ? Dis-le-moi en commentaire" },
  { id: 2, month: "Avril", category: "Engagement & débat", text: "Les Français sont pauvres, c'est terrifiant\n\nÉpargne moyenne en 2025 :\n18-24 ans → 3 000 €\n25-29 ans → 5 500 €\n30-39 ans → 13 000 €\n40-49 ans → 24 000 €\n50-59 ans → 32 000 €\n60-69 ans → 40 000 €\n\nEt toi, tu te situes où ?" },
  { id: 3, month: "Avril", category: "Storytelling", formats: ["Bilan de la semaine"], text: "J'ai commencé à placer mon argent sur mon assurance vie en 2017. Puis, j'ai acheté du BTC en 2024 et ouvert mon PEA en 2025. Tout ça au prix d'effort sur mon train de vie.\n\nOn ne vit qu'une fois, d'accord, mais autant essayer de vivre correctement le plus longtemps possible.\n\nLe système des retraites ne tient plus, c'est indéniable. Qui sait quelle retraite nous attend dans 30 ans ?\n\nAujourd'hui, je dors sur mes deux oreilles. Peu importe les krachs, j'ai acheté des actifs auxquels je crois.\n\nDemain, je ferai partie de ceux à qui on dit \"tu as eu de la chance\". De la chance ? Non, j'ai pris conscience de l'urgence de la situation et j'ai pris des risques. Ceux qui ne jouent pas ne gagnent pas.\n\nEt toi, tu seras qui dans 20 ans ? Celui qui a joué ou celui qui dira aux autres qu'ils ont eu de la chance ?" },
  { id: 4, month: "Avril", category: "Simulation & chiffres", text: "100€/mois investi. Même effort. Deux horizons.\n\nSur 30 ans :\nLivret A : 36 000€ investis → 50 000€ (+14 000€)\nFonds euros : 36 000€ investis → 58 000€ (+22 000€)\nMSCI World : 36 000€ investis → 122 000€ (+86 000€)\n\nSur 40 ans :\nLivret A : 48 000€ investis → 70 000€ (+22 000€)\nFonds euros : 48 000€ investis → 93 000€ (+45 000€)\nMSCI World : 48 000€ investis → 262 000€ (+214 000€)\n\n10 ans de plus sur le MSCI World = +140 000€ supplémentaires.\n\nLe temps est ton meilleur allié. Commence maintenant.\n\nPas un conseil financier" },
  { id: 5, month: "Avril", category: "Simulation & chiffres", text: "🛍️ En économisant 200€ par mois, tu peux t'acheter :\n🧥 Un manteau (≈ 200€) → 1 mois\n⌚ Une belle montre (≈ 600€) → 3 mois\n📱 Un iPhone 17 (≈ 969€) → 5 mois\n🚗 Une voiture (≈ 20 000€) → 8 ans\n🏠 Un appartement (≈ 140 000€) → 58 ans\n\nMais si tu places ces 200€/mois sur un ETF MSCI World (≈8%/an, perf historique) 📈 :\n5 ans → 14 700€\n10 ans → 36 600€\n20 ans → 117 000€\n30 ans → 298 000€\n\nLa vraie différence entre consommer et investir ? ⏳ C'est le temps qui travaille pour toi, et les intérêts composés.\n\nPas un conseil financier ⚠️" },

  { id: 6, month: "Mai", category: "Storytelling", formats: ["Bilan de la semaine"], text: "Je conserve 10 000€ sur mon livret A\n\nCertains diront que je perds de l'argent, que cette somme aurait pu travailler sur un ETF MSCI World\n\nC'est vrai. Pourtant, je la garde précieusement.\n\nPourquoi ? Parce que c'est le prix de ma tranquilité\n\nUn problème de voiture ? Des travaux dans mon logement ? Je ne m'inquiète plus pour tout ça. Et grâce à cette somme qui est rémunérée à 1,5% seulement, je peux investir mon argent chaque mois\n\nAvant de construire votre patrimoine financier, pensez à votre épargne de précaution. C'est elle qui vous fera tenir lorsque votre argent fera -20%\n\nEt toi, c'est quoi le prix de ta tranquillité ?" },
  { id: 7, month: "Mai", category: "Engagement & débat", text: "Voilà les chiffres potentiels de ma retraite, en admettant que j'en ai une\n\nSelon moi, investir n'est pas un luxe mais une nécessité pour se protéger d'un avenir incertain\n\nVous avez fait votre simulation de votre côté ? On fait le concours de celui qui a la plus petite ?" },
  { id: 8, month: "Mai", category: "Storytelling", formats: ["Bilan de la semaine"], text: "J'ai 32 ans et comme beaucoup, j'ai longtemps repoussé l'idée de regarder combien je gagnerais à la retraite. Et ça ne m'a pas plu.\n\nPuis j'ai pris 5 minutes pour faire un calcul.\n\nSi je mets 300 € par mois dans un ETF à 8 % jusqu'à 65 ans :\n→ Je sors seulement 118 800 € de ma poche...\n→ Pour avoir 580 000 € au total.\n\nÇa veut dire que 462 000 € viendront juste avec du temps et de la patience.\n\nLe plus dur, ce n'est pas d'investir, mais d'arrêter de tout remettre à demain. Le vrai risque, c'est d'attendre.\n\nEt toi, tu as fait ce calcul aussi ?" },
  { id: 9, month: "Mai", category: "Bilan patrimoine", formats: ["Bilan de la semaine"], text: "Mon patrimoine vient d'atteindre 73 000€\nObjectif : 100 000€ dans 2 ans\n\nVoici exactement comment c'est réparti et pourquoi\n\nLivret A : 10 000€\nLe matelas de sécurité. Pas plus, pas moins. Une partie prête à frapper si le marché offre une vraie opportunité.\n\nAssurance Vie : 46 000€\nFutur achat immo en ligne de mire. L'argent doit travailler plus que sur un livret A, tout en restant sécurisé. Renforcements réguliers par petites sommes.\n\nPEA : 6 500€\nLe moteur de croissance du patrimoine. Ouvert en 2025. DCA léger au début devenu agressif cette année. C'est là que va la majorité de mon épargne mensuelle.\n\nBitcoin : 10 000€\n100% BTC. Accumulé en 2024, renforcé à 66k en mars 2026. Plan : ne plus toucher. Rééquilibrer vers le PEA quand ça repart.\n\nVous pensez quoi de cette répartition ?" },
  { id: 10, month: "Mai", category: "Guide ETF", text: "Les ETF que j'aurais voulu connaître quand j'ai commencé à investir.\n\nMSCI World : 1 500 entreprises, 23 pays développés en un seul ETF\n→ PEA : FR001400U5Q4 (Amundi) Frais : 0,20%\n→ CTO : IE00B4L5Y983 (iShares) Frais : 0,20%\n\nMSCI Emerging Markets : s'exposer à la croissance de l'Inde, la Chine, le Brésil avec un filtre ISR\n→ PEA : FR0013412020 (Amundi, version ESG) Frais : 0,30%\n→ CTO : IE00BTJRMP35 (Xtrackers) Frais : 0,18%\n\nS&P 500 : les 500 plus grandes entreprises américaines\n→ PEA : FR0011550185 (BNP Paribas Easy) Frais : 0,14%\n→ CTO : IE00B5BMR087 (iShares) Frais : 0,07%\n\nNasdaq-100 : les géants de la tech américaine (Apple, Nvidia, Microsoft...)\n→ PEA : FR0011871110 (Amundi) Frais : 0,30%\n→ CTO : IE00B53SZB19 (iShares) Frais : 0,30%\n\nStoxx Europe 600 : les 600 plus grandes entreprises européennes\n→ PEA : FR0011550193 (BNP Paribas Easy) Frais : 0,19%\n→ CTO : LU0908500753 (Amundi Core) Frais : 0,07%\n\nEuro Stoxx 50 : les 50 champions de la zone euro (LVMH, SAP, ASML...)\n→ PEA : FR0007054358 (Amundi) Frais : 0,20%\n→ CTO : IE0008471009 (iShares, version distribuante) Frais : 0,10%\n\nMSCI ACWI : le monde entier en un ETF, pays développés + émergents (2 500 entreprises)\n→ CTO : IE00B6R52259 (iShares) Frais : 0,20%\n\nMSCI World Momentum : le World, filtré sur les actions qui montent le plus fort\n→ CTO : IE00BP3QZ825 (iShares Edge) Frais : 0,25%\n\nTu détiens lesquels ? Et avec quelle allocation ? Dis-moi en commentaire" },
  { id: 11, month: "Mai", category: "Storytelling", formats: ["Preuve vendredi soir"], text: "Mon PEA ouvert fin octobre 2025 atteint +10% pour la première fois.\n\n7 mois d'investissements programmés, chaque mois, avec régularité, en fonction de ce que je suis capable d'économiser. On avance doucement mais sûrement.\n\nL'objectif est clair : construire une sérénité financière, pas s'enrichir rapidement\n\nUne règle que je répète souvent et que j'applique moi-même : l'argent que vous placez sur un PEA ne doit pas être de l'argent dont vous avez besoin à court ou moyen terme.\n\nMa stratégie ? Une grosse part sur un ETF MSCI World, une part sur le STOXX 600, une part sur les marchés émergents. 3 ETF, c'est tout.\n\nEt voici ce que peu de gens réalisent : la majorité des Français n'investissent pas en bourse. Si vous avez un PEA avec un plan régulier, vous faites déjà partie de ceux qui agissent concrètement pour leur avenir financier.\n\nFélicitations à ceux qui le font ! Bravo à vous pour prendre votre avenir en main !" },
  { id: 12, month: "Mai", category: "Simulation & chiffres", text: "300 €/mois pendant 30 ans, c'est 108 000 € de ta poche.\n\nVoilà ce que ça devient selon où tu les mets\n\nFonds euros (~3%) → 174 000 €\nSCPI (~5%) → 250 000 €\nETF World (~7%) → 340 000 €\n\nEt toi, tu les placerais où ces 300€ par mois ?" },
  { id: 13, month: "Mai", category: "Simulation & chiffres", text: "200€/mois, même effort, deux horizons.\n\nSur 30 ans :\nCash : 72 000€ investis → 72 000€ (+0€)\nFonds euros (3%) : 72 000€ investis → 116 550€ (+44 550€)\nMSCI World (7%) : 72 000€ investis → 243 994€ (+171 994€)\n\nSur 40 ans :\nCash : 96 000€ investis → 96 000€ (+0€)\nFonds euros (3%) : 96 000€ investis → 185 674€ (+89 674€)\nMSCI World (7%) : 96 000€ investis → 524 962€ (+428 962€)\n\nLaisser son argent dormir sur 40 ans = 428 962€ laissés sur la table.\n\nLe temps est ton meilleur allié." },

  { id: 14, month: "Juin", category: "Storytelling", text: "À 32 ans, j'ai 8 050 € sur mon PEA et CTO.\n\nJe me suis projeté sur 35 ans : 300 € investis chaque mois, avec une performance espérée de +8 % par an (moyenne historique du MSCI World).\n\nRésultat ? 761 792 €\n\nOui, c'est une simulation. Oui, l'inflation existe. Oui, c'est brut. Mais je préfère largement me projeter comme ça plutôt que de compter sur une retraite de misère.\n\nJ'ai commencé petit, j'ai pris mon temps pour comprendre... et je continue tous les mois.\n\nEt toi, tu vises combien de patrimoine à la retraite ?" },
  { id: 15, month: "Juin", category: "Simulation & chiffres", text: "10 000€ investis il y a 5 ans\n\nLivret A → 11 100€\nCAC 40 (Amundi CAC 40) → 14 700€\nMSCI World (Amundi CW8) → 16 700€\nNasdaq 100 (Amundi PEA Nasdaq-100) → 20 000€\nBanques zone euro (Amundi Euro Stoxx Banks) → 36 000€\n\nOui, tu as bien lu. Le secteur que tout le monde enterrait en 2020 a écrasé tous les autres et a fait +260%.\n\n2 leçons :\n1. Le Livret A n'a même pas couvert l'inflation sur la période.\n2. Personne ne sait ce qui performera demain. C'est exactement pour ça que le MSCI World existe.\n\nTu investissais ton argent en 2021 ?\n\nPerformances passées ≠ performances futures. Pas un conseil en investissement." },
  { id: 16, month: "Juin", category: "Storytelling", formats: ["Preuve vendredi soir"], text: "\"La bourse c'est compliqué, ça demande des compétences.\"\n\nJ'ai ouvert mon PEA le 27 octobre 2025. Depuis : +10,52%\n\nPas besoin d'être un génie de la bourse ni de trader toutes les nuits. Juste un DCA sur 3 ETF bien choisis, et le temps qui bosse pour toi.\n\nEt tu sais quoi ? Ça me prend littéralement 1 minute par mois.\n\nEt toi, c'est quoi ta performance sur ton PEA ?" },
  { id: 17, month: "Juin", category: "Guide ETF", text: "LE GUIDE des ETF éligibles PEA, classés par exposition. Sauvegarde ce tweet, tu pourrais en avoir besoin\n\n1/ MONDE (MSCI World)\nAmundi PEA Monde — Ticker : DCAM · FR001400U5Q4 · 0,20%\niShares MSCI World Swap PEA (part à ~5€) — Ticker : WPEA · IE0002XZSHO1 · 0,20%\nLa brique de base d'un PEA. Une ligne, le monde développé entier.\n\n2/ ÉTATS-UNIS\nAmundi PEA S&P 500 (le moins cher) — Ticker : PSP5 · FR0011871128 · 0,12%\nAmundi PEA Nasdaq-100 — Ticker : PUST · FR0011871110 · 0,30%\nÀ 0,12%, le S&P 500 est imbattable côté frais.\n\n3/ EUROPE\nBNP Paribas Easy STOXX Europe 600 (le SEUL éligible PEA) — Ticker : ETZ · FR0011550193 · 0,19%\nAmundi Core Euro Stoxx 50 (le moins cher) — Ticker : C50 · LU1681047236 · 0,09%\nAmundi PEA MSCI Europe — Ticker : PCEU · FR0013412038 · 0,15%\nAmundi CAC 40 ESG — LU1681046931 · 0,25%\n\n4/ ÉMERGENTS & ASIE\nAmundi PEA Emergent (MSCI Emerging) — Ticker : PAEEM · FR0013412020 · 0,30%\nAmundi PEA Asie Émergente — FR0013412012 · 0,30%\nAmundi PEA Inde (MSCI India) — Ticker : PINR · FR0011869320 · 0,85%\nAmundi PEA Japon (TOPIX) — Ticker : PTPXE · FR0013411980 · 0,20%\nAmundi PEA Japon TOPIX couvert EUR (hedged) — FR0013411998 · 0,48%\nL'Inde affiche le TER le plus élevé de la liste (0,85%) : c'est le seul ETF Inde éligible PEA, sans concurrence pour faire baisser les frais.\n\n5/ Récap stratégie\nUn PEA solide peut tenir en 1 à 3 lignes :\n100% Monde (DCAM ou WPEA)\nMonde + une poche émergents\nS&P 500 + Europe + Émergents\n\nTu as lesquels dans ton portefeuille ? Pas un conseil financier" },
  { id: 18, month: "Juin", category: "Storytelling", formats: ["Preuve vendredi soir"], text: "Il y a quelques années, j'aurais laissé mon argent dormir sur un Livret A. Aujourd'hui, il part directement sur mon PEA, chaque mois, sans exception\n\nLe DCA du mois de juin est passé\nMSCI World — 94 parts | 6,80€ | 639,20€\nStoxx 600 — 3 parts | 20,53€ | 61,58€\nEmerging Markets — 2 parts | 37,08€ | 74,16€\nTotal investi : 774,94€ ce mois-ci\n\nLe marché est en ATH ? J'accumule. Il baisse ? J'accumule. Sans regarder le prix.\n\nEt toi, ton DCA de juin est déjà passé ?" },
  { id: 19, month: "Juin", category: "Bilan patrimoine", formats: ["Bilan de la semaine"], text: "3 ETF, c'est tout.\n\nOn me demande souvent ma répartition sur mon PEA par ETF, secteurs et pays. La voici\n\nLes ETF :\nMSCI World : 65%\nStoxx 600 : 23%\nEmerging markets : 13%\n\nPays :\n46% USA\n8% UK\n5% France\n\nSecteur :\nTech : 23%\nServices financiers : 19%\nIndustrie : 13%\n\nQue penses-tu de ce portefeuille ?" },
  { id: 20, month: "Juin", category: "Actu & humour", text: "Vive la retraite par répartition\n\nJe vends tout, all in livret A et LDDS" },
  { id: 21, month: "Juin", category: "Guide ETF", text: "Tu veux une exposition européenne sur ton PEA mais tu hésites entre MSCI Europe, Stoxx 50 et Stoxx 600 ? On décrypte les trois\n\nL'EXPOSITION\nSTOXX 600 — les 600 plus grandes entreprises européennes, 17 pays. UK + Suisse + Scandinavie inclus → le plus large\nEURO STOXX 50 — les 50 plus grosses boîtes de la zone euro uniquement → ultra-concentré (ASML, SAP, LVMH...)\nMSCI Europe — les grandes valeurs de 15 pays développés européens → très proche du STOXX 600\n\nLES ETF ÉLIGIBLES PEA\nSTOXX 600 → un SEUL choix : BNP Paribas Easy STOXX Europe 600 UCITS ETF — Ticker : ETZ · ISIN : FR0011550193 · TER 0,19 % · synthétique (swap), capitalisant, 1 054 M€ d'encours\nEURO STOXX 50 → le plus de choix (indice 100 % zone euro) : iShares Core EURO STOXX 50 (Acc) — ISIN : IE00B53L3W79 · TER 0,10 % · 7 667 M€ / HSBC EURO STOXX 50 — ISIN : IE00B4K6B022 · TER 0,05 % (le moins cher)\nMSCI Europe → un seul vrai choix : Amundi PEA MSCI Europe UCITS ETF (Acc) — Ticker : PCEU · ISIN : FR0013412038 · TER 0,15 % · synthétique, capitalisant, 327 M€ d'encours\n\nDIVERSIFICATION\nSTOXX 600 (600 lignes) > MSCI Europe (~430) > EURO STOXX 50 (50)\nLe 50 concentre ton risque : ses 10 plus grosses lignes pèsent +41 % de l'indice. Plus volatil, très dépendant du luxe et de la tech euro.\n\nPERFORMANCE\nAmundi PEA MSCI Europe (PCEU) — YTD +9,21 % · 1 an +19,11 % · 5 ans +59,42 %\nBNP STOXX 600 (ETZ) — YTD +7,01 % · 1 an +15,72 % · 5 ans +57,87 %\niShares EURO STOXX 50 (SXRT) — YTD +3,72 % · 1 an +25,49 % · 5 ans +73,87 %\n\nLE VERDICT POUR UN PEA\nExposition la plus large (UK + Suisse) ? → ETZ (BNP STOXX 600)\nLe moins cher + zone euro pure ? → EURO STOXX 50\nLarge mais sans UK/Suisse, capitalisant français ? → PCEU (Amundi MSCI Europe)\n\nEt toi, t'as lequel dans ton PEA ?" },

  { id: 22, month: "Juillet", category: "Storytelling", formats: ["Bilan de la semaine"], text: "Ah l'épargne de précaution ! Certains disent qu'il faut 5 000€, d'autres 3 à 6 mois de salaires, d'autres de dépenses...\n\nAu final, ce qui compte, c'est que tu sois à l'aise avec la somme que tu gardes.\n\n\"Oui mais tu perds de l'argent\" — peut-être, mais la tranquilité n'a pas de prix\n\nEt le prix de ma tranquilité, c'est 10 000€ !" },
  { id: 23, month: "Juillet", category: "Engagement & débat", text: "Hier, je regardais la télé et j'ai halluciné\n\nLe meilleur candidat de l'émission \"N'oubliez pas les paroles\" a gagné plus de 700 000€\n\nJe me demande...\n\nToi, tu ferais quoi si tu gagnais 700K€ ?" },
  { id: 24, month: "Juillet", category: "Actu & humour", text: "La bulle est en train d'éclater sous nos yeux\n\nJe vends tout, all-in Livret A\n\nL'année prochaine je me ferai un restaurant avec les intérêts en pensant à vous" },
  { id: 25, month: "Juillet", category: "Bilan patrimoine", formats: ["Bilan de la semaine"], text: "\"Pourquoi tu ne prends pas juste du SP500 ?\"\n\nParce que le SP500 c'est : 10 entreprises = 40% de l'indice. Très concentré tech\n\nJ'ai fait le choix d'un PEA diversifié et équilibré, le voici\n\nRépartition par ligne\n66% MSCI World\n22% Europe (Stoxx 600)\n12% Emerging Markets\n\nRépartition sectorielle\n24% Tech\n18% Services financiers\n13% Industrie\n\nRépartition géographique\n47% États-Unis\n7% Royaume-Uni\n5% France\n\nTu connais ta répartition géographique et sectorielle ?" },
  { id: 26, month: "Juillet", category: "Engagement & débat", text: "En gagnant 700K demain, voilà comment je répartirais cette somme\n\n150K → PEA (MSCI World) — zéro dividendes, capitalisant, aucune friction fiscale.\n300K → CTO (FTSE All World) — pas de JEPQ. Le \"rendement\" c'est ton propre capital qui te revient déguisé.\n100K → SCPI — un peu d'immo passif pour diversifier et toucher des loyers réguliers.\n50K → Bitcoin (cold storage) — le pari asymétrique, ma petite conviction.\n50K → Apport immo — juste assez pour un bien à 400K.\n\nJe préfère investir le reste dans des actifs qui font 8% annualisé et utiliser l'effet de levier au maximum.\n\nTu penses quoi de cette allocation ? Qu'est-ce que tu aurais changé ?" },
  { id: 27, month: "Juillet", category: "Guide ETF", text: "Il existe 5 ETF MSCI World éligibles au PEA. Les voici, et comment faire son choix parmi eux\n\nAmundi PEA Monde — FR001400U5Q4 · 0,20% · 1 208 M\niShares MSCI World Swap PEA — IE0002XZSHO1 · 0,20% · 1 839 M\nAmundi MSCI World Swap EUR Acc — LU1681043599 · 0,38% · 6 410 M\nAmundi MSCI World Swap EUR Dist — LU2655993207 · 0,38% · 428 M\nAmundi MSCI World Swap USD Acc — LU1681043672 · 0,38% · 76 M\n\n5 critères pour choisir :\nLe TER → 0,20% vs 0,38%, ça paraît rien mais sur 20 ans ça peut peser plusieurs milliers d'€\nL'encours → sous les 100M€, risque de fermeture (donc vente forcée au pire moment fiscal). Plus d'encours = plus liquide.\nLa tracking difference → le vrai coût caché, un ETF \"pas cher\" peut sous-performer son indice bien plus que son TER affiché.\nLa devise de cotation → USD peut entraîner des frais de change.\nAcc vs Dist → même fiscalité dans le PEA, mais Acc réinvestit automatiquement (Dist te verse du cash à replacer toi-même)\n\nTu regardes lequel de ces critères en premier ?" },
  { id: 28, month: "Juillet", category: "Engagement & débat", text: "Unpopular opinion\n\nInvestir sur le SP500 est moins risqué qu'investir dans l'immobilier locatif." },
  { id: 29, month: "Juillet", category: "Bilan patrimoine", formats: ["Bilan de la semaine"], text: "Mon patrimoine est proche des 75K€\nObjectif : 100 000€ dans 2 ans\n\nVoici exactement comment c'est réparti et pourquoi\n\nLivret A : 11 300€\nLe matelas de sécurité. Une partie prête à être déployée si le marché offre une vraie opportunité, une autre paiera mes vacances en août\n\nAssurance Vie : 46 406€\nLa plus grosse poche du patrimoine. L'argent doit travailler plus que sur un livret A, tout en restant sécurisé. Elle contient l'apport de ma future résidence principale.\n\nPEA : 7 903€\nLe moteur de croissance du patrimoine. DCA à ~500€/mois désormais. C'est là que va la majorité de mon épargne mensuelle.\n\nCTO : 701€\n2 ETF sectoriels, représentent environ 10% de mon total en bourse. Mon petit pari sur l'automatisation et la cybersécurité.\n\nBitcoin : 8 162€\nMa conviction personnelle. Renfort effectué à 66K, un autre est prévu si le Bitcoin touche 50K.\n\nVous pensez quoi de cette répartition ?" },
  { id: 30, month: "Juillet", category: "Storytelling", formats: ["Bilan de la semaine"], text: "À 22 ans, j'ai arrêté mes études à cause de ma santé mentale. Je sortais tous les week-ends, je buvais, je fumais des clopes et du cannabis, je dépensais tout ce que j'avais sans penser au lendemain.\n\nPuis les choses ont changé petit à petit. J'ai trouvé un apprentissage dans une branche qui me plaisait vraiment. J'ai réussi à aller mieux et j'ai commencé à penser à mon avenir pour la première fois depuis longtemps.\n\nJ'ai commencé par mettre de côté sur mon Livret A, puis sur une assurance vie, un PEA, et j'ai appris à investir. J'ai structuré mon patrimoine étape par étape.\n\nAujourd'hui je dépasse les 74 000€, je suis propriétaire d'un appartement et j'ai un travail qui me passionne.\n\nLes choses peuvent changer.\n\nRoad to 100k. Et toi, tu en es où dans la structure de ton patrimoine ? Dis-le-moi en commentaire" },
  { id: 31, month: "Juillet", category: "Storytelling", formats: ["Bilan de la semaine"], text: "J'ai ouvert mon PEA avec 30€ en octobre 2025\n\nPas 5 000€. Pas 1 000€. 30€.\n\nPourquoi 30€ ? Parce que j'hésitais mais j'avais conscience qu'il fallait que je me lance. Et c'est sans doute la meilleure décision financière que j'ai prise. Voici pourquoi\n\nLa fiscalité du PEA se déclenche à l'ouverture, pas au montant investi. Après 5 ans, tes gains sont exonérés d'impôt (hors prélèvements sociaux). Le compteur démarre le jour où tu verses ton premier euro.\n\nRésultat concret : quelqu'un qui ouvre son PEA avec 50€ aujourd'hui et verse plus tard sera fiscalement avantagé face à quelqu'un qui attend d'avoir \"assez\" pour ouvrir le sien dans 3 ans.\n\nCe qu'il te faut pour commencer, vraiment :\nUn courtier régulé (AMF/ACPR)\n1 seul ETF large (MSCI World par exemple)\nUn virement régulier, même petit\n\nL'erreur que font la plupart des débutants : attendre le \"bon moment\" ou le \"bon montant\". Ce moment n'arrive jamais. Pendant ce temps, le compteur fiscal ne tourne pas.\n\nLe temps est le seul allié que tu ne rattrapes jamais.\n\nToi, ton PEA, tu l'as ouvert à quel âge et avec combien ? Pas un conseil financier" },
  { id: 32, month: "Juillet", category: "Guide ETF", text: "MSCI World, MSCI ACWI, FTSE All-World — tout le monde confond ces trois ETF \"Monde\". On me l'a demandé, le voici : le comparatif complet pour bien choisir son exposition entre les trois\n\nMSCI World — 1 283 valeurs · 23 pays développés\nAmundi PEA Monde \"DCAM\" (PEA) : FR001400U5Q4 · Frais : 0,20%\n\nMSCI ACWI — 2 461 valeurs · 23 développés + 24 émergents\nAmundi PEA Global (PEA) : FR0014017NX3 (nouveau, 15/07/2026) · Frais : 0,30%\niShares MSCI ACWI (CTO) : IE00B6R52259 · Frais : 0,20%\n\nFTSE All-World — ~4 200 valeurs · 45+ pays\nVanguard VWCE (CTO uniquement) : IE00BK5BQT80 · Frais : 0,19%\n\nDepuis juillet 2026, l'ACWI a enfin son ETF PEA. Seul le All-World reste hors PEA.\n\nExposition géographique détaillée\nMSCI World — US 72,5% · Japon 5,7% · UK 3,5% · Canada 3,3% · France 2,4% · Reste 12,7%\nMSCI ACWI — US 63,6% · Japon 5,0% · Taiwan 3,3% · UK 3,0% · Canada 2,9% · Reste 22,1%\nFTSE All-World — US 62,3% · Japon 5,8% · UK 3,3% · Canada 3,1% · Chine 3,0% · Reste 21,9%\n\nTop 3 secteurs\nMSCI World — Tech 30,3% · Finance 15,9% · Industrie 11,6%\nMSCI ACWI — Tech 32,1% · Finance 16,2% · Industrie 11,0%\nFTSE All-World — Tech 32,5% · Finance 15,1% · Industrie 12,9%\n\nTop 5 holdings\nMSCI World — Nvidia 5,18% · Apple 4,77% · Microsoft 2,95% · Amazon 2,59% · Alphabet A 2,33%\nMSCI ACWI — Nvidia 4,55% · Apple 4,19% · Microsoft 2,59% · Amazon 2,27% · Alphabet A 2,05%\nFTSE All-World — Nvidia 4,47% · Apple 4,00% · Microsoft 2,65% · Amazon 2,21% · Alphabet A 2,00%\n\nPerformance YTD 2026 — World +9,9% · ACWI +11,5% · All-World +12,1%\n1 an — World +21,8% · ACWI +24,2% · All-World +24,3%\n10 ans annualisé — World +13,7% · ACWI +13,3% · All-World +12,8%\n\nToi t'es sur lequel des 3 ? Pas un conseil en investissement" },

  { id: 33, month: "Août", category: "Storytelling", formats: ["Preuve vendredi soir"], text: "Je suis quelqu'un de lambda. Je touche le salaire médian, environ 2200€ par mois.\n\nMes parents m'ont toujours appris à épargner sur un Livret A. On n'a jamais parlé d'investissement, de bourse, d'inflation. Pendant longtemps j'ai fait pareil, ce que mes parents m'ont dit : mettre gentiment mon argent sur le Livret A.\n\nPuis j'ai compris que mon argent perdait de la valeur chaque année, et que ce n'est pas comme ça que je me construirais un patrimoine. Alors j'ai appris, seul dans mon coin. J'ai appris à gérer un budget, à mettre de côté chaque début de mois et à investir mon argent dans des actifs que je comprends\n\nEt cette semaine, mon patrimoine a gagné 556€, sans aucune action de ma part\n\nLa bourse, l'investissement, c'est accessible à tous, même avec peu d'argent. La seule vraie différence entre ceux qui construisent un patrimoine et les autres ? Ils ont commencé\n\nEt toi, tes parents t'ont parlé d'investissement ? Pas un conseil financier." },
  { id: 34, month: "Août", category: "Storytelling", formats: ["Preuve vendredi soir", "Bilan de la semaine"], text: "On voit souvent des comptes qui partagent leur portefeuille à 300k, 500k, parfois plus d'un million d'euros\n\nEt honnêtement, ça fait quelque chose. On se compare, on se sent tout petit, et on se dit \"moi j'en suis loin, à quoi bon continuer\"\n\nMais on oublie un truc important : ce portefeuille à 500k, il a commencé quelque part. Je me rappelle mon premier investissement sur mon PEA : 29,87€ sur un MSCI World. Sur le moment, ça paraissait ridicule. Genre \"à quoi bon investir un montant pareil\". Mais c'était ça, le vrai début. Pas impressionnant, juste un premier pas hésitant.\n\nPersonne ne montre ça ici, le premier versement sur son PEA. On montre le portefeuille à 6 chiffres, jamais le premier versement à deux chiffres.\n\nAlors si aujourd'hui ton portefeuille fait 30€, 100€ ou 500€ : tu es exactement là où j'étais, là où tout le monde a commencé un jour. La différence, elle se fera dans le temps.\n\nCette personne à plusieurs centaines de milliers d'euros, elle investit depuis combien d'années ? Elle gagne combien ? On n'en sait rien, et franchement, on s'en fiche. Se comparer pour se flageller, c'est contre-productif. Se comparer pour se projeter, c'est différent.\n\nAlors regarde ton portefeuille à 30€, 100€ ou 500€, et dis-toi une seule chose : dans 10 ans, ça peut être toi." },
  { id: 35, month: "Août", category: "Simulation & chiffres", text: "Ce que les chiffres disent sur l'achat au sommet historique\n\nLa peur intuitive : acheter à un record = acheter au pire moment\nLa réalité statistique : c'est faux dans l'immense majorité des cas\n\nVoici pourquoi :\nDepuis 1950, investir au sommet historique du S&P500 rapporte en moyenne +12,7% l'année suivante, contre +12,6% un jour \"normal\". Ok, peu de différence.\nDepuis 1928, le gain médian sur 1 an après un record est de 9,6%, contre 9,5% un jour normal.\nSur 5 ans l'écart existe (+44% vs +47%) mais reste faible : investir sur un ATH reste largement rentable, juste marginalement moins qu'un jour \"au hasard\".\nSur tous les records du S&P500 depuis 1988, environ 30% d'entre eux sont devenus des \"planchers\". L'indice redescend rarement plus de 5% en dessous.\n\nLe vrai danger n'est pas d'acheter trop haut, c'est de rester en cash. Rater seulement les 10 meilleures journées de bourse sur 20 ans fait chuter le rendement annualisé de 10,6% à 6,4%.\n\nConclusion : un marché qui bat des records le fait généralement parce que l'économie et les résultats des entreprises le justifient. Attendre \"le bon moment\" coûte historiquement plus cher que d'investir maintenant.\n\nLe \"sommet historique\" d'aujourd'hui est souvent juste... un point bas de demain\n\nPas un conseil financier." },
  { id: 36, month: "Août", category: "Simulation & chiffres", text: "300 000€ empruntés sur 25 ans.\n\nÀ 1% : tu rembourses 339 200€. Intérêts : 39 200€\nÀ 3,5% : tu rembourses 450 600€. Intérêts : 150 600€\n\nBien content d'avoir un crédit à 1,2%" },
  { id: 37, month: "Août", category: "Guide ETF", text: "Les ETF sur PEA ayant le plus performé sur un an\n\nAmundi STOXX Europe 600 Basic Resources UCITS ETF Acc — ISIN : LU1834983550 · Frais : 0,30% p.a. · Perf 1 an : +73,16%\nMines, métaux, matières premières... le pari sur les ressources naturelles européennes.\n\niShares MSCI Europe Information Technology Sector UCITS ETF Acc — ISIN : IE00BMW42413 · Frais : 0,18% p.a. · Perf 1 an : +58,24%\nLa tech européenne dans un seul ETF (SAP, ASML...).\n\niShares EURO STOXX Banks 30-15 UCITS ETF (DE) Acc — ISIN : DE000A2QP372 · Frais : 0,52% p.a. · Perf 1 an : +52,63%\nLes grandes banques de la zone euro réunies en un ETF.\n\nQui a dit que les ETF européens ne performaient pas ? Tu as l'un d'entre eux ? Pas un conseil financier." },
  { id: 38, month: "Août", category: "Storytelling", formats: ["Bilan de la semaine"], text: "Quand j'avais 20 ans, mon Livret A était à 2000€, je fumais des gros joints et je pensais que 1€ = 1€\n\nPuis j'ai compris ce qu'est l'inflation et l'importance de faire fructifier son argent.\n\n12 ans plus tard, je suis à 77 000€. Pourtant, je ne gagne pas 5000€ par mois. Honnêtement, je ne pensais pas pouvoir atteindre ce chiffre aussi vite en touchant le salaire médian\n\nL'âge auquel tu commences importe peu. Ce qui compte, c'est le jour où tu prends conscience de l'importance de faire travailler ton argent\n\nAu début je culpabilisais de ne pas avoir commencé à 20 ans. Aujourd'hui je me remercie d'avoir pris mon avenir en main à 30 ans\n\nAlors intéressez-vous : assurance vie, PEA, CTO, livret A, marchés boursiers, or, ETF, actions, SCPI, immobilier... Soyez curieux, et faites vos choix en connaissance de cause\n\nPas un conseil en investissement" },
  { id: 39, month: "Août", category: "Guide ETF", text: "L'énorme avantage du MSCI World, et pourquoi il sera sûrement encore là dans 30 ans ?\n\nIl s'auto-nettoie. Personne n'en parle jamais. Voici le secret de sa longévité\n\nCOMMENT ÇA MARCHE\nChaque trimestre, MSCI recalcule la capitalisation de chaque entreprise mondiale. Une boîte grossit → son poids augmente automatiquement. Une boîte s'effondre → elle est éjectée, remplacée\n\nLA PREUVE HISTORIQUE\nFin 1989 : le Japon est en pleine bulle. Sony, Toyota et les banques japonaises dominent. Le Japon pèse alors près de 45 % du MSCI World. Un niveau jamais revu depuis. Puis la bulle éclate, le Nikkei perd près de 80 % au plus bas. Il lui faudra 34 ans, jusqu'en février 2024, pour retrouver son niveau de 1989.\n\nDEUX INVESTISSEURS, DEUX DESTINS\nCelui qui a tout misé sur le Japon en 1989 : capital gelé pendant plus de trois décennies.\nAvec le MSCI World : rien à faire. Trimestre après trimestre, le poids du Japon a fondu tout seul, réalloué vers les US puis la tech. Aujourd'hui : 5,73 %, contre 45 % en 1989.\n\nET DEMAIN ?\nMême mécanisme avec Nvidia, Apple, Microsoft aujourd'hui. Si un autre pays ou secteur prend le relais dans 15 ans, vous n'aurez rien à changer. L'indice se réajuste seul, comme avec le Japon.\n\nLA VRAIE FORCE\nCe n'est pas \"il mise sur les US\" ou \"il mise sur la tech\". Il mise sur les gagnants du moment, quels qu'ils soient, et les remplace dès qu'ils faiblissent.\n\nPas un conseil financier." },
  { id: 40, month: "Août", category: "Bilan patrimoine", formats: ["Bilan de la semaine"], text: "Chaque fois que je partage mon PEA avec 21% de Stoxx 600 (en plus de mon MSCI World), c'est le même refrain\n\n\"L'Europe c'est nul\" \"La croissance n'est pas en Europe\" \"Tu surpondères par rapport à la capitalisation\"\n\nSauf que le MSCI World à lui seul, c'est déjà plus de 70% d'US dedans. Rajouter du Stoxx 600, c'est pas parier sur l'Europe, c'est refuser de mettre encore plus d'œufs dans le même panier.\n\nLa diversification géographique, c'est lisser le risque créé par la concentration. Un pays, une devise, une banque centrale, un cycle économique : ça fait beaucoup de risques concentrés au même endroit. Et niveau secteurs, le Stoxx 600 rééquilibre aussi un MSCI World ultra concentré en tech américaine, avec plus de banques, santé, luxe et industrie.\n\nMon allocation actuelle :\n67% MSCI World\n21% Stoxx Europe 600\n12% MSCI Emerging\n\nEt pendant que tout le monde répète \"l'Europe c'est mort\"... en euros :\n2025 : Stoxx 600 +20,17% vs S&P 500 +3,55%\n2026 (YTD) : Stoxx 600 +13,66% vs S&P 500 +13,54%\n\nLe Stoxx 600 surperforme donc depuis 2025, chiffres à l'appui.\n\nVous êtes plutôt 100% US ou vous gardez de l'Europe ?" },
  { id: 41, month: "Août", category: "Guide ETF", text: "Le meilleur MSCI World du marché coûte 0,05%/an. Le souci ? Il n'est pas éligible PEA.\n\nEst-ce qu'il est plus intéressant de prendre un ETF MSCI World sur PEA (avantage fiscal) ou sur CTO (moins de frais) ? J'ai fait le calcul avec un lump sum de 10 000€, 8%/an de performance, sur 30 ans\n\nCTO | Invesco MSCI World\nTER : 0,05%/an\nCapital après 30 ans : ~99 200€\nFlat tax 31,4% sur la plus-value : -28 000€\nNet en poche : ~71 200€\n\nPEA | WPEA (iShares) ou DCAM (Amundi)\nTER : 0,20%/an\nCapital après 30 ans : ~95 200€\nPrélèvements sociaux 18,6% uniquement : -15 800€\nNet en poche : ~79 340€\n\nRésultat : le PEA rapporte +8 100€ de plus, malgré des frais 4x plus élevés. La fiscalité écrase les frais sur le long terme.\n\nLe CTO est le seul moyen d'acheter des actions US, mais le PEA est souvent plus avantageux pour les ETF qui y sont éligibles.\n\nPas un conseil financier" },

  { id: 42, month: "Septembre", category: "Storytelling", formats: ["Preuve vendredi soir", "Bilan de la semaine"], text: "Mon patrimoine se rapproche petit à petit de la barre symbolique des 80K 📈\n\n78 002€ aujourd'hui, il y a un mois, j'étais encore sous les 76K.\n\nJe me souviens d'un temps où je regardais mon compte en banque en espérant qu'il me reste assez à la fin du mois pour m'acheter mon shit, ma bouteille pour sortir en soirée 🎉\n\nAujourd'hui, tu sais ce que je vois quand je regarde ce graphique ? Des années de discipline, des versements que j'ai jamais loupés, des baisses que j'ai laissées passer sans paniquer.\n\nJe me rappelle quand j'ai vu le Bitcoin grimper à 120K, après l'avoir acheté à 40K. L'euphorie, puis la descente aux enfers 📉\n\nJ'ai rien vendu. Parce que quand tu crois en un actif sur le long terme, sa volatilité ne devrait pas t'effrayer.\n\n80K, c'est pas un chiffre magique. C'est juste la preuve que ce qui paraît lent finit toujours par compter 👍\n\nSi toi aussi tu pars de loin, ou que t'as l'impression que ça avance trop lentement : continue. Le graphique ne ment jamais sur la durée 📊\n\n💬 C'est quoi ton prochain palier symbolique ?" },
]

export function getTweet(id) {
  return TWEETS.find((t) => t.id === id)
}
