// Version courte du registre : les seuils et restrictions qui changent le choix restent visibles.
// Les détails de procédure et références restent dans evidence.js.
export const BROKER_EDITORIAL = {
  tr: {
    frais: '1 € par ordre ponctuel, ou 2 € avec Direct Price ; plans programmés sans frais d’exécution. Spread et coûts tiers possibles.',
    dca: 'oui ✅ Plans programmés sans frais d’exécution sur les titres éligibles.',
    garde: 'aucun ✅',
    cash: 'oui ✅ Sous conditions, après activation, hors PEA.',
    cashDisponible: true, cashPrecision: 'après activation.',
    entrant: 'possible ✅ Sauf PEA contenant des titres non cotés.',
    sortant: 'transfert possible.',
    faible: 'Le PEA-PME n’est pas proposé selon les analyses consultées.',
  },
  bourso: {
    frais: 'Découverte : 1,99 € jusqu’à 500 €, puis 0,60 %, dans la limite du plafond PEA de 0,50 % pour les ordres en ligne.',
    offres: ['BoursoMarkets : une sélection d’ETF Amundi sans courtage à l’achat. Vérifie l’éligibilité de l’ISIN ; la vente suit le tarif applicable.'],
    dca: 'oui ✅ Plan d’Épargne dès 10 €/fonds/mois, sans frais de négociation. Frais propres aux fonds en supplément.',
    garde: 'aucun ✅',
    cash: 'non selon les analyses consultées ❌',
    entrant: 'possible ✅ Premier transfert total : frais remboursés au double, jusqu’à 3 000 €, sans dépasser la valeur du compte, sous conditions.',
    sortant: '15 € par ligne, maximum 150 €.',
    faible: 'Le plan automatique porte sur des fonds avec leurs propres frais. Ordre minimum ETF : 200 € ; certaines Bourses européennes : 2 500 €.',
  },
  ibkr: {
    frais: 'Actions France : 0,05 %, minimum 1,25 € en dégressif, plus frais de Bourse possibles. En fixe : minimum 3 € avec SmartRouting ; routage direct 0,10 %, minimum 4 €. Autres places : barèmes distincts, sous le plafond légal PEA.',
    dca: 'les analyses divergent sur la disponibilité des achats récurrents dans le PEA.',
    garde: 'aucun ✅',
    cash: 'oui ✅ Au-delà des premiers 10 000 € en EUR, selon la valeur du compte, hors PEA.',
    cashDisponible: true, cashPrecision: 'au-delà des premiers 10 000 € en EUR, selon la valeur du compte.',
    entrant: 'possible ✅ IBKR annonce 0 € de frais de transfert ; les frais du courtier d’origine restent distincts.',
    sortant: '0 € annoncé par IBKR.',
    faible: 'La disponibilité des achats automatiques sur PEA reste discutée. PEA-PME et PEA Jeune non proposés selon les analyses consultées.',
  },
  fortuneo: {
    frais: 'Starter sur Euronext/Equiduct : premier ordre du mois jusqu’à 500 € sans courtage, puis 0,35 %.',
    offres: ['Starter : premier ordre mensuel jusqu’à 500 € sans courtage sur Euronext/Equiduct.'],
    dca: 'pas d’achats automatiques sur PEA selon les analyses consultées ❌',
    garde: 'aucun ✅',
    cash: 'non selon les analyses consultées ❌',
    entrant: 'possible ✅ Premier transfert remboursé jusqu’à 100 € si l’encours est inférieur à 3 000 €, 150 € de 3 000 à moins de 5 000 €, ou 2 000 € à partir de 5 000 €, sous conditions.',
    sortant: '15 € par ligne cotée, 50 € pour les titres non cotés ou nominatifs hors Euroclear, maximum 150 €.',
    faible: 'Les frais sont plus élevés hors Euronext. Pas d’achats automatiques sur PEA selon les analyses consultées ; clôture du PEA : 85 €.',
  },
  xtb: {
    frais: '0 % jusqu’à 100 000 € de transactions mensuelles cumulées sur tes comptes, puis 0,20 %.',
    dca: 'pas encore ❌',
    garde: 'gratuits jusqu’à 250 000 € de portefeuille, puis 0,02 % par an sur l’excédent.',
    cash: 'oui ✅ Selon les conditions de l’offre, hors PEA.',
    cashDisponible: true,
    entrant: 'pas encore disponible ❌',
    sortant: '15 € par ligne, maximum 150 €.',
    faible: 'Tu ne peux pas encore y transférer ton PEA existant.',
  },
  caidf: {
    frais: 'Invest Store : Initial 0,50 % ; Integral 0,48 % jusqu’à 500 €, 0,18 % jusqu’à 1 000 €, puis 0,12 %. Integral : 96 €/an sous 12 ordres, gratuit dès 12 ordres ou pour les 18–30 ans.',
    dca: 'oui ✅ Plan d’Épargne Boursière sur 1 à 3 fonds éligibles au PEA, dès 45 €/mois. Frais des fonds en supplément.',
    garde: 'exonérés avec Integral. Sinon : droits fixes et 0,20 % par semestre selon le barème régional, plafonnés à 250 €/semestre.',
    cash: 'non selon les analyses consultées ❌',
    entrant: 'possible ✅ Avec conservation de l’antériorité fiscale.',
    sortant: '15 € par ligne, maximum 150 € vers un établissement hors Crédit Agricole ; frais de correspondant possibles sur les titres étrangers.',
    faible: 'Sans Integral, les droits de garde s’ajoutent au courtage. Integral coûte 96 €/an sous 12 ordres, sauf pour les 18–30 ans.',
  },
  bd: {
    frais: 'Euronext : plafond de 0,50 % jusqu’à 198 €, puis 0,99 € jusqu’à 500 €, 1,90 € jusqu’à 1 000 €, 2,90 € jusqu’à 2 000 €, 3,80 € jusqu’à 4 400 €, puis 0,09 %.',
    offres: ['Plans programmés sur une sélection d’ETF sans frais de courtage.'],
    dca: 'oui ✅ Plans programmés sur une sélection d’ETF sans courtage ; actions au tarif habituel.',
    garde: 'aucun hors Bourses étrangères ✅ Sur les Bourses étrangères : 0,036 % par an.',
    cash: 'non selon les analyses consultées ❌',
    entrant: 'possible ✅ Frais remboursés jusqu’à 150 € pour le PEA, sur justificatif.',
    sortant: '15 € par ligne, maximum 150 €.',
    faible: 'Les frais sur les Bourses étrangères, dont les droits de garde, pèsent davantage.',
  },
  saxo: {
    nom: 'Saxo',
    frais: '0,08 % sur Euronext en formule Classic, minimum 2 €, dans la limite du plafond légal de 0,50 % pour les ordres en ligne.',
    offreDate: 'Jusqu’au 31 décembre 2026 :',
    offres: ['70 actions européennes sans courtage à l’achat et à la vente pour les nouveaux PEA éligibles, ouverts ou transférés.', 'Une sélection d’ETF Amundi sans courtage à l’achat, dont certains sont éligibles au PEA. La vente reste payante selon le tarif applicable.'],
    dca: 'son plan programmé existe, mais hors PEA ❌',
    garde: 'aucun sur les titres cotés ✅',
    cash: 'oui ✅ Réservé aux clients VIP, sous conditions, hors PEA.',
    cashDisponible: true, cashPrecision: 'réservé aux clients VIP.',
    entrant: 'possible ✅ Pour un transfert total : remboursement des frais jusqu’à 150 €, sous conditions, jusqu’au 31 décembre 2026.',
    sortant: '15 € par ligne, maximum 150 €.',
    restriction: 'Attention : l’offre ETF Amundi de Saxo prévoit une restriction de transfert de six mois sur les positions achetées dans ce cadre.',
    faible: 'Hors offres gratuites, le minimum de courtage pèse davantage sur les petits ordres, malgré le plafond légal.',
  },
};
