// Registre éditorial : PDF officiels et pages publiées par les courtiers.
// Dans les PDF, la première page porte le numéro 1.
// « Non établi » ne signifie jamais « non proposé ».
export const OFFICIAL_SOURCES = {
  trInterest: { title: 'Trade Republic · Intérêts sur espèces', edition: 'page en ligne', checked: '29/09/2026', url: 'https://traderepublic.com/fr-fr/interets', kind: 'page' },
  trFees: { title: 'Trade Republic · Frais d’ordre et de garde', edition: 'page en ligne', checked: '29/09/2026', url: 'https://support.traderepublic.com/fr-fr/719-How-expensive-is-it-to-open-a-securities-account', kind: 'page' },
  trOrders: { title: 'Trade Republic · Exécution des ordres', edition: 'page en ligne', checked: '29/09/2026', url: 'https://support.traderepublic.com/fr-fr/784-Is-there-commission-for-order-execution', kind: 'page' },
  trPricing: { title: 'Trade Republic · Barème public France', edition: 'page en ligne', checked: '29/09/2026', url: 'https://traderepublic.com/fr-fr/about?openModal=pricing-scheme', kind: 'page' },
  trCustody: { title: 'Trade Republic · Frais de garde', edition: 'page d’aide France', checked: '29/09/2026', url: 'https://support.traderepublic.com/fr-fr/2847-Y-a_t_il-des-frais-de-garde-', kind: 'page' },
  trPea: { title: 'Trade Republic · PEA', edition: 'page en ligne', checked: '29/09/2026', url: 'https://traderepublic.com/fr-fr/pea', kind: 'page' },
  xtbInterest: { title: 'XTB · Intérêts sur fonds non investis', edition: 'taux variables', checked: '29/09/2026', url: 'https://www.xtb.com/fr/interets', kind: 'page' },
  xtbPea: { title: 'XTB · PEA, fonctionnement et FAQ', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.xtb.com/fr/pea', kind: 'page' },
  saxoInterest: { title: 'Saxo · Intérêts sur les espèces', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.home.saxo/fr-fr/campaigns/interest-rates-cal', kind: 'page' },
  saxoAutoinvest: { title: 'Saxo · Plan Épargne Programmé', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.home.saxo/fr-fr/products/autoinvest', kind: 'page' },
  saxoPeaPromo: { title: 'Saxo · Conditions de l’offre PEA 70 actions sans courtage', edition: '23/02–31/12/2026', checked: '30/09/2026', url: 'https://www.home.saxo/fr-fr/accounts/pea/terms-and-conditions', kind: 'page' },
  ibkrPea: { title: 'Interactive Brokers · PEA France', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.interactivebrokers.ie/fr/accounts/plan-depargne-en-action-accounts.php', kind: 'page' },
  ibkrFees: { title: 'Interactive Brokers · Commissions Europe', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.interactivebrokers.ie/fr/pricing/commissions-stocks-europe.php', kind: 'page' },
  ibkrInterest: { title: 'Interactive Brokers · Intérêts sur espèces', edition: 'taux variables', checked: '29/09/2026', url: 'https://www.interactivebrokers.ie/fr/index.php?f=47097', kind: 'page' },
  ibkrDca: { title: 'Interactive Brokers · Plan programmé', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.interactivebrokers.ie/fr/trading/recurring-investments.php', kind: 'page' },
  boursoIfu: { title: 'BoursoBank · Télécharger son IFU', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.boursobank.com/aide-en-ligne/fiscalite/ifu-imprime-fiscal-unique/qu-est-ce-qu-un-ifu-imprime-fiscal-unique/question/comment-telecharger-votre-imprime-fiscal-unique-ifu-2790948361', kind: 'page' },
  fortuneoIfu: { title: 'Fortuneo · Télécharger son IFU', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.fortuneo.fr/faq/comment-telecharger-mon-imprime-fiscal-unique-ifu', kind: 'page' },
  bdIfu: { title: 'Bourse Direct · Fiscalité du CTO', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.boursedirect.fr/fr/bourse/compte-titres', kind: 'page' },
  caPeaPme: { title: 'Crédit Agricole · PEA-PME', edition: 'page nationale', checked: '29/09/2026', url: 'https://www.credit-agricole.fr/particulier/epargne/bourse/plan-d-epargne-en-actions-pme.html', kind: 'page' },
  caIdfPea: { title: 'Crédit Agricole Île-de-France · PEA Jeune', edition: 'page régionale', checked: '30/09/2026', url: 'https://www.credit-agricole.fr/ca-paris/particulier/epargne/bourse/plan-d-epargne-en-actions.html', kind: 'page' },
  caIdfPeaPme: { title: 'Crédit Agricole Île-de-France · Compte espèces PEA-PME', edition: 'page régionale', checked: '30/09/2026', url: 'https://www.credit-agricole.fr/ca-paris/particulier/epargne/bourse/plan-d-epargne-en-actions-pme.html', kind: 'page' },
  caCtoCash: { title: 'Crédit Agricole · Fonctionnement du compte espèces CTO', edition: 'page en ligne', checked: '30/09/2026', url: 'https://www.credit-agricole.fr/particulier/conseils/magazine/tout-un-mag/les-differentes-enveloppes-fiscales.html', kind: 'page' },
  fortuneoContract: { title: 'Fortuneo · Conditions générales', edition: '01/09/2025', checked: '29/09/2026', url: 'https://www.fortuneo.fr/datas/files/fortuneo_cg.pdf' },
  bdPea: { title: 'Bourse Direct · Fonctionnement du PEA', edition: 'page en ligne', checked: '29/09/2026', url: 'https://epargne.boursedirect.fr/epargne/placements-epargne/compte-titres-dont-pea-et-pea-pme/le-pea-plan-d-epargne-en-actions', kind: 'page' },
  boursoMarkets: { title: 'BoursoBank · BoursoMarkets', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.boursobank.com/bourse/boursomarkets-courtage-bourse-gratuit', kind: 'page' },
  caInvest: { title: 'Crédit Agricole · Invest Store', edition: 'page nationale ; tarifs régionaux distincts', checked: '29/09/2026', url: 'https://www.credit-agricole.fr/particulier/epargne/bourse/service-de-bourse-en-ligne-invest-store.html', kind: 'page' },
  caPea: { title: 'Crédit Agricole · PEA et PEA Jeune', edition: 'page nationale ; conditions régionales à confirmer', checked: '29/09/2026', url: 'https://www.credit-agricole.fr/particulier/epargne/bourse/plan-d-epargne-en-actions.html', kind: 'page' },
  caPeb: { title: 'Crédit Agricole · Plan d’Épargne Boursière', edition: 'page nationale ; conditions régionales à confirmer', checked: '29/09/2026', url: 'https://www.credit-agricole.fr/particulier/epargne/bourse/plan-d-epargne-boursiere.html', kind: 'page' },
  saxoPeaHelp: { title: 'Saxo Banque · Centre d’aide PEA', edition: '29/06/2026', checked: '29/09/2026', url: 'https://www.help.saxo/hc/fr-fr/articles/4582385514781-Le-Plan-%C3%89pargne-en-Actions-PEA', kind: 'page' },
  xtbComparison: { title: 'XTB · Comparatif PEA 2026 et perspectives de son offre', edition: '2026', checked: '29/09/2026', url: 'https://www.xtb.com/fr/formation/meilleurs-PEA-2025-notre-comparatif', kind: 'page' },
  bdSupport: { title: 'Bourse Direct · FAQ transfert de compte', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.boursedirect.fr/fr/support', kind: 'page' },
  bdTariffPage: { title: 'Bourse Direct · Tarifs PEA et transfert entrant', edition: 'page en ligne', checked: '29/09/2026', url: 'https://www.boursedirect.fr/fr/bourse/tarifs', kind: 'page' },
  trContract: {
    title: 'Trade Republic · Contrat client France', edition: '09/2026', checked: '29/09/2026',
    url: 'https://assets.traderepublic.com/assets/files/CA_FR-en-fr.pdf',
  },
  boursoTariff: {
    title: 'BoursoBank · Brochure tarifaire 2026', edition: '2026', checked: '29/09/2026',
    url: 'https://www.boursobank.com/content/brochure_tarifaire/boursorama_bt.pdf',
  },
  fortuneoTariff: {
    title: 'Fortuneo · Conditions tarifaires en vigueur', edition: '06/08/2026', checked: '30/09/2026',
    url: 'https://www.fortuneo.fr/datas/files/tarifs_fortuneo.pdf',
  },
  xtbTariff: {
    title: 'XTB · Table des frais et commissions', edition: '05/2026', checked: '29/09/2026',
    url: 'https://www.xtb.com/fr/fichiers/table-des-frais-et-commissions_052026.pdf',
  },
  xtbContract: {
    title: 'XTB · Règlement des services de courtage', edition: '15/09/2023', checked: '29/09/2026',
    url: 'https://xtb.com/fr/Reglement_Portant_Sur_La_Prestation_De_Services_De_Courtage-15092023.pdf',
  },
  xtbOverview: {
    title: 'XTB · Présentation de l’offre', edition: '2026', checked: '29/09/2026',
    url: 'https://xas-new-cdn.xtb.com/file/0104/53/271ced41-db62-499b-9e83-f3b4557f9bf1/fr-meet-xtb-one-pager-2026-docx.pdf',
  },
  xtbIfu: { title: 'XTB · Informations générales et IFU', edition: '29/04/2026', checked: '29/09/2026', url: 'https://xtb.com/fr/Informations_Generales_Concernant_XTB.pdf' },
  caTariff: {
    title: 'Crédit Agricole Île-de-France · Tarifs particuliers', edition: '01/04/2026', checked: '29/09/2026',
    url: 'https://ca-paris.credit-agricole.fr/Reglementaire/Tarifs/2026/CADIF_tarif2026_PART/conditions_tarifaires_particuliers_caidf_04_2026.pdf',
  },
  bdTariff: {
    title: 'Bourse Direct · Conditions tarifaires', edition: '06/01/2026', checked: '29/09/2026',
    url: 'https://www.boursedirect.fr/pdf/tarifs_bd.pdf',
  },
  bdPlans: {
    title: 'Bourse Direct · Communiqué sur les plans programmés', edition: '11/05/2026', checked: '29/09/2026',
    url: 'https://groupe.boursedirect.fr/download/bourse-direct-lance-ses-plans-dinvestissement-programmes-sans-frais-sur-etf-a-partir-de-quelques-euros-disponibles-sur-pea-et-compte-titres?filename=2026_BD_CP_Plan-Investissement.pdf',
  },
  saxoTariff: {
    title: 'Saxo Banque · Brochure tarifaire', edition: '05/05/2026', checked: '29/09/2026',
    url: 'https://www.home.saxo/-/media/documents/regional/fr-fr/manuals/brochure-tarifaire-generale-2026.pdf?revision=2996f32d-c87a-4efc-9596-658f98c61848',
  },
  saxoContract: {
    title: 'Saxo Banque · Conditions générales', edition: '09/04/2026', checked: '29/09/2026',
    url: 'https://www.home.saxo/-/media/documents/regional/fr-fr/manuals/conditions-generales-applicables-a-partir-du-9-avril-2026.pdf?revision=3add9d56-0ee9-43ff-8c6b-b25897ebbfe8',
  },
}

// Analyses éditoriales externes : distinctes des documents des courtiers.
export const SECONDARY_SOURCES = {
  moneyvoxCaIdf: { title: 'MoneyVox · Tarifs CA Île-de-France et rémunération du compte courant', edition: 'tarifs 2026', checked: '30/09/2026', url: 'https://www.moneyvox.fr/tarif-bancaire/credit-agricole-ile-de-france/', kind: 'secondary-page' },
  moneyvoxPea2026: { title: 'MoneyVox · PEA des banques en ligne', edition: '2026', checked: '30/09/2026', url: 'https://www.moneyvox.fr/banque-en-ligne/actualites/103315/investir-en-bourse-en-2026-quelle-banque-en-ligne-offre-le-meilleur-pea', kind: 'secondary-page' },
  cafePeaPme: { title: 'Café de la Bourse · Comparatif PEA-PME', edition: '2026', checked: '30/09/2026', url: 'https://www.cafedelabourse.com/dossiers/article/osez-les-petites-valeurs-avec-le-pea-pme', kind: 'secondary-page' },
  brokerBdCash: { title: 'BrokerChooser · Cash Bourse Direct', edition: '09/2026', checked: '30/09/2026', url: 'https://brokerchooser.com/fr/broker-reviews/bourse-direct-review/bourse-direct-fees', kind: 'secondary-page' },
  sinvestirBoursoCash: { title: 'S’investir · CTO BoursoBank', edition: '2026', checked: '30/09/2026', url: 'https://sinvestir.fr/cto-boursobank-avis/', kind: 'secondary-page' },
  detectiveBdCash: { title: 'Détective Banque · Comparatif courtier', edition: '09/2026', checked: '30/09/2026', url: 'https://www.detective-banque.fr/comparatif-de-bourse-en-ligne-quelle-offre-choisir/', kind: 'secondary-page' },
  mondeDca: { title: 'Le Monde · Investissements programmés en PEA', edition: '26/09/2025', checked: '30/09/2026', url: 'https://www.lemonde.fr/argent/article/2025/09/26/comment-faire-des-investissements-programmes-sur-un-pea_6642989_1657007.html', kind: 'secondary-page' },
  starFortuneoDca: { title: 'Starfinance · PEA Fortuneo', edition: '08/2026', checked: '30/09/2026', url: 'https://starfinance.fr/pea-fortuneo-avis-avec-analyse-et-test/', kind: 'secondary-page' },
  epargnant30FortuneoDca: { title: 'Épargnant 3.0 · Comparatif PEA', edition: '2026 (offre citée expirée en août)', checked: '30/09/2026', url: 'https://www.epargnant30.fr/meilleur-courtier-pea-cto/', kind: 'secondary-page' },
  radarIbkrDca: { title: 'MoneyRadar · Test du PEA IBKR', edition: '14/09/2026', checked: '30/09/2026', url: 'https://moneyradar.org/bourse/interactive-brokers/pea/', kind: 'secondary-page' },
  financeHerosForumDca: { title: 'Finance Héros · Réponse éditoriale sur les plans PEA', edition: '19/08/2026', checked: '30/09/2026', url: 'https://forum.finance-heros.fr/t/investissement-programme-sur-pea/1515', kind: 'secondary-page' },
  financeHerosPea: { title: 'Finance Héros · Comparatif PEA', edition: '22/07/2026', checked: '30/09/2026', url: 'https://finance-heros.fr/ouvrir-meilleur-pea-comparatif/', kind: 'secondary-page' },
  peaFrIbkr: { title: 'PEA.fr · Comparatif PEA, fiche IBKR', edition: '30/07/2026', checked: '30/09/2026', url: 'https://pea.fr/comparatifs/meilleur-pea-comparatif-banques-courtiers/', kind: 'secondary-page' },
  sinvestirIbkr: { title: 'S’investir · Avis Interactive Brokers', edition: '2026', checked: '30/09/2026', url: 'https://sinvestir.fr/interactive-brokers-avis/', kind: 'secondary-page' },
  prorealtimeIbkr: { title: 'Avenant IBIE diffusé par ProRealTime', edition: '03/12/2024', checked: '30/09/2026', url: 'https://trading.prorealtime.com/fr/ib_agreement_pdf?r=ib_ie_pea_disclosures', kind: 'secondary-pdf' },
  prorealtimeDca2026: { title: 'ProRealTime · Barème des investissements récurrents IBKR', edition: '17/09/2026', checked: '30/09/2026', url: 'https://www.prorealtime.com/en/pdf/interactive-brokers-fees.pdf', kind: 'secondary-pdf' },
}

const proved = (summary, document, page) => ({ status: 'confirmé', summary, refs: [{ document, ...(page ? { page } : {}) }] })
const unknown = (summary, checked = []) => ({ status: 'non établi', summary, checked })

// Une entrée par champ affiché. « Liquidités rémunérées » signifie qu'une offre officielle
// rémunère au moins un solde d'espèces non investi ; cela ne promet rien pour tous les comptes.
export const BROKER_EVIDENCE = {
  tr: {
    boursomarkets: unknown('Offre BoursoMarkets propre à BoursoBank ; sans objet pour ce courtier.'),
    frais: { status: 'confirmé', summary: 'Les conditions PEA renvoient au barème d’ordres. Ordre ponctuel : 1 € de frais fixes de règlement ; 2 € si Direct Price est choisi. Plans programmés sans frais d’exécution ; spread, frais du produit et tiers éventuels en sus. Le tarif exact est présenté avant validation dans l’application.', refs: [{ document: 'trContract', page: 190 }, { document: 'trPricing' }, { document: 'trOrders' }] },
    dca: { status: 'confirmé', summary: 'Plans programmés prévus par contrat ; PEA sans frais sur les plans selon sa page de présentation ; titres éligibles dans l’application.', refs: [{ document: 'trContract', page: 91 }, { document: 'trPea' }] },
    garde: { status: 'confirmé', summary: 'Trade Republic indique qu’aucun frais n’est facturé pour l’administration et la conservation des titres. Son contrat décrit le compte de titres PEA détenu chez Trade Republic ; aucune exception PEA n’est annoncée dans l’aide consultée.', refs: [{ document: 'trCustody' }, { document: 'trContract', page: 189 }] },
    pea: proved('PEA prévu par les conditions France.', 'trContract', 189),
    pme: { status: 'corroboré', summary: 'PEA-PME non proposé selon MoneyVox et Café de la Bourse ; le contrat Trade Republic ne formule pas cette exclusion.', refs: [{ document: 'moneyvoxPea2026' }, { document: 'cafePeaPme' }, { document: 'trContract', page: 189 }] },
    jeune: proved('PEA ouvert sous conditions aux jeunes rattachés au foyer fiscal.', 'trContract', 190),
    ifu: proved('IFU lié à la migration vers l’offre française.', 'trContract', 3),
    cash: { status: 'confirmé', summary: 'Oui sur espèces éligibles du compte général sous conditions ; offre 3 % nouveau client jusqu’à 50 000 € après activation. Le contrat exclut les espèces PEA.', refs: [{ document: 'trInterest' }, { document: 'trContract', page: 57 }, { document: 'trContract', page: 190 }] },
    transfert: proved('Transfert entrant du PEA prévu par le contrat.', 'trContract', 189),
  },
  bourso: {
    boursomarkets: proved('ETF iShares éligibles : 0 € à l’achat ; conditions de vente selon le titre. Pastille sur chaque fiche pour établir l’éligibilité.', 'boursoMarkets'),
    frais: proved('Découverte : 1,99 € jusqu’à 500 €, puis 0,60 % ; plafond PEA à 0,5 %.', 'boursoTariff', 20),
    dca: proved('Plan d’épargne : négociation gratuite, minimum 10 € par fonds et frais de gestion selon DIC.', 'boursoTariff', 20),
    garde: proved('Droits de garde gratuits dans le barème indiqué.', 'boursoTariff', 23),
    pea: proved('Tarifs PEA prévus.', 'boursoTariff', 20),
    pme: proved('Tarifs PEA-PME prévus.', 'boursoTariff', 20),
    jeune: proved('Tarifs PEA 18-25 ans prévus.', 'boursoTariff', 20),
    ifu: proved('IFU disponible dans les documents fiscaux si revenus ou opérations à déclarer.', 'boursoIfu'),
    cash: { status: 'corroboré', summary: 'Non selon S’investir et Détective Banque pour les espèces non investies du CTO ; les livrets distincts sont exclus. La brochure officielle ne formule pas une exclusion générale.', refs: [{ document: 'sinvestirBoursoCash' }, { document: 'detectiveBdCash' }, { document: 'boursoTariff', page: 20 }] },
    transfert: proved('Transfert PEA sortant : 15 € par ligne, plafond 150 €.', 'boursoTariff', 25),
  },
  ibkr: {
    boursomarkets: unknown('Offre BoursoMarkets propre à BoursoBank ; sans objet pour ce courtier.'),
    frais: { status: 'confirmé', summary: 'PEA : à partir de 0,05 %. Pour les actions France, tarif dégressif 0,05 % et minimum 1,25 € ; tarif fixe SmartRouting 0,05 % et minimum 3 € ; routage direct 0,10 % et minimum 4 €. Frais de Bourse possibles au tarif dégressif ; autre marché ou fonds : autre barème.', refs: [{ document: 'ibkrPea' }, { document: 'ibkrFees' }] },
    dca: { status: 'corroboré', summary: 'Disponibilité PEA contestée : Finance Héros (réponse du 19/08/2026) et MoneyRadar (test du 14/09/2026) disent oui sur des titres entiers ; une analyse du 04/09/2026 non retenue comme preuve, Finance Héros (juillet) et Le Monde (2025) disent non. Le service général IBKR et le barème ProRealTime du 17/09 ne nomment pas expressément le PEA. Les sources récentes divergent ; aucun parcours PEA daté ni confirmation directe IBKR ne tranche. Analyse discordante et limites détaillées dans le document d’audit.', refs: [{ document: 'financeHerosForumDca' }, { document: 'radarIbkrDca' }, { document: 'prorealtimeDca2026', page: 29 }, { document: 'financeHerosPea' }, { document: 'mondeDca' }, { document: 'ibkrDca' }] },
    garde: proved('Aucun droit de garde ni frais de tenue de compte PEA annoncés.', 'ibkrPea'),
    pea: proved('PEA Classique commercialisé.', 'ibkrPea'),
    pme: { status: 'corroboré', summary: 'PEA-PME distinct non proposé selon Café de la Bourse. La page IBKR ne présente que le PEA classique ; l’avenant IBIE évoque un PEA-PME chez un autre courtier. Une analyse externe non retenue se contredit entre son texte (« pas de PEA-PME ») et son tableau (« oui via le même PEA »), confondant potentiellement titres PME éligibles au PEA et enveloppe PEA-PME distincte ; voir le document d’audit. Confirmation directe IBKR toujours absente.', refs: [{ document: 'cafePeaPme' }, { document: 'ibkrPea' }, { document: 'prorealtimeIbkr', page: 70 }] },
    jeune: { status: 'corroboré', summary: 'PEA Jeune non disponible selon PEA.fr (30/07/2026) et S’investir (2026). L’avenant IBIE du 03/12/2024 prévoit pourtant le plafond légal de 20 000 € pour un enfant majeur rattaché : cette clause ne démontre pas que le parcours d’ouverture actuel lui est ouvert. Sources contradictoires ; confirmation écrite IBKR nécessaire.', refs: [{ document: 'peaFrIbkr' }, { document: 'sinvestirIbkr' }, { document: 'prorealtimeIbkr', page: 70 }, { document: 'ibkrPea' }] },
    ifu: proved('IFU disponible pour le PEA.', 'ibkrPea'),
    cash: { status: 'confirmé', summary: 'Oui pour soldes éligibles : 0 % sur les premiers 10 000 € EUR, taux variable au-delà et selon valeur du compte ; PEA non documenté.', refs: [{ document: 'ibkrInterest' }] },
    transfert: proved('Transfert du PEA possible, sans frais de transfert annoncés.', 'ibkrPea'),
  },
  fortuneo: {
    boursomarkets: unknown('Offre BoursoMarkets propre à BoursoBank ; sans objet pour ce courtier.'),
    frais: proved('Starter : premier ordre mensuel ≤ 500 € gratuit sur Euronext/Equiduct, puis 0,35 %. Achat PEA/PEA-PME sur certaines autres places européennes : minimum 400 € hors courtage.', 'fortuneoTariff', 10),
    dca: { status: 'corroboré', summary: 'Non pour les achats PEA automatisés : Le Monde (09/2025), Starfinance (08/2026) et Épargnant 3.0 (2026) décrivent des ordres manuels. Le tableau MoneyRadar emploie « ordres programmés » sans documenter l’automatisation : ce terme ne suffit pas à établir un plan récurrent.', refs: [{ document: 'mondeDca' }, { document: 'starFortuneoDca' }, { document: 'epargnant30FortuneoDca' }, { document: 'radarIbkrDca' }] },
    garde: proved('Droits de garde gratuits.', 'fortuneoTariff', 10),
    pea: proved('Tarifs PEA prévus.', 'fortuneoTariff', 10),
    pme: proved('Tarifs PEA-PME prévus.', 'fortuneoTariff', 10),
    jeune: proved('PEA Jeune non commercialisé selon les conditions générales.', 'fortuneoContract', 35),
    ifu: proved('IFU disponible dans l’espace client, notamment pour le compte titres.', 'fortuneoIfu'),
    cash: { status: 'corroboré', summary: 'Non : les conditions générales Fortuneo du 01/09/2025 excluent explicitement les intérêts sur le compte espèces PEA/PEA-PME. Détective Banque étend ce constat au cash non investi du CTO en citant la brochure du 06/08/2026 ; aucune clause générale équivalente pour le CTO n’a été identifiée. Les livrets distincts ne comptent pas.', refs: [{ document: 'fortuneoContract', page: 35 }, { document: 'detectiveBdCash' }, { document: 'fortuneoTariff', page: 10 }] },
    transfert: proved('Transfert PEA sortant 15 € par ligne, plafond 150 € ; clôture distincte à 85 €.', 'fortuneoTariff', 13),
  },
  xtb: {
    boursomarkets: unknown('Offre BoursoMarkets propre à BoursoBank ; sans objet pour ce courtier.'),
    frais: proved('0 % avant 100 000 € de volume mensuel ; 0,20 % ensuite ; minimum 10 € non appliqué au PEA.', 'xtbTariff', 4),
    dca: proved('XTB présente les plans programmés sur PEA comme une extension à venir ; disponibilité actuelle non annoncée.', 'xtbComparison'),
    garde: proved('0,02 % annuel sur la part du portefeuille au-delà de 250 000 €.', 'xtbTariff', 6),
    pea: proved('Tarif applicable au PEA mentionné.', 'xtbTariff', 4),
    pme: proved('XTB indique « Non » pour son PEA-PME et décrit ce volet comme à venir en 2026.', 'xtbComparison'),
    jeune: proved('PEA non ouvert aux personnes majeures fiscalement rattachées à leurs parents chez XTB.', 'xtbPea'),
    ifu: proved('XTB déclare fournir un IFU pour les opérations sur valeurs mobilières.', 'xtbIfu', 7),
    cash: { status: 'confirmé', summary: 'Oui pour fonds non investis du compte de trading, sans minimum ni maximum ; taux préférentiel 90 jours jusqu’à 100 000 €, puis standard, variables. PEA sans intérêts.', refs: [{ document: 'xtbInterest' }, { document: 'xtbPea' }] },
    transfert: proved('Transfert entrant PEA actuellement indisponible ; tarif du transfert sortant documenté séparément.', 'xtbPea'),
  },
  caidf: {
    boursomarkets: unknown('Offre BoursoMarkets propre à BoursoBank ; sans objet pour ce courtier.'),
    frais: proved('Île-de-France, ordre en ligne Euronext : Invest Store Initial 0,50 % ; Intégral PEA/PEA-PME 0,48 % jusqu’à 500 €, 0,18 % de 500 à 1 000 €, 0,12 % au-delà. Intégral coûte 96 €/an sous 12 ordres, gratuit dès 12 ordres ou de 18 à 30 ans. Frais de marché et TTF en sus.', 'caTariff', 28),
    dca: { status: 'confirmé', summary: 'Plan d’Épargne Boursière : investissements automatiques dès 45 €/mois sur 1 à 3 SICAV/FCP éligibles PEA/PEA-PME selon la page nationale ; mise en place gratuite dans le tarif Île-de-France. Frais propres aux fonds selon leur DIC.', refs: [{ document: 'caPeb' }, { document: 'caTariff', page: 27 }] },
    garde: proved('Île-de-France : exonération avec Invest Store Intégral, gestion conseillée ou mandat ; autrement 2,50 €/semestre/compte, 12,50 €/semestre sur certaines lignes, 0,20 %/semestre de valorisation, maximum 250 €/semestre. Voir détails et exemptions au barème.', 'caTariff', 29),
    pea: proved('PEA proposé par Invest Store ; barème régional Île-de-France publié.', 'caTariff', 28),
    pme: proved('PEA-PME proposé ; barème régional Île-de-France publié.', 'caTariff', 28),
    jeune: proved('La page de la caisse Île-de-France annonce le PEA Jeune pour un majeur rattaché, avec un plafond de 20 000 €.', 'caIdfPea'),
    ifu: { status: 'confirmé', summary: 'La brochure Île-de-France 2026 tarifie explicitement la réédition de l’IFU ; Invest Store indique que l’IFU est consultable. La production du document dépend des opérations à déclarer.', refs: [{ document: 'caTariff', page: 8 }, { document: 'caInvest' }] },
    cash: { status: 'corroboré', summary: 'Non selon les sources consultées : la page régionale exclut les intérêts sur le cash PEA-PME ; MoneyVox (tarifs CA Île-de-France 2026) indique que la rémunération du compte courant n’est pas proposée. Le CTO s’appuie sur un compte espèces bancaire classique selon le Crédit Agricole. Aucun taux du cash non investi relevé ; les livrets et dépôts à terme sont des placements distincts.', refs: [{ document: 'caIdfPeaPme' }, { document: 'moneyvoxCaIdf' }, { document: 'caCtoCash' }] },
    transfert: proved('Transfert sortant de compte-titres ou PEA hors Crédit Agricole : 15 €/ligne, maximum 150 €/compte ; frais du correspondant possibles pour titres étrangers.', 'caTariff', 31),
  },
  bd: {
    boursomarkets: unknown('Offre BoursoMarkets propre à BoursoBank ; sans objet pour ce courtier.'),
    frais: proved('PEA ≤ 198 € : 0,5 % ; puis paliers à partir de 0,99 €.', 'bdTariff', 2),
    dca: proved('Plans automatiques PEA et CTO ; ETF éligibles sans courtage, actions aux frais habituels.', 'bdPlans', 1),
    garde: proved('0 € hors bourses étrangères ; 0,036 % annuel sur bourses étrangères.', 'bdTariff', 2),
    pea: proved('PEA prévu dans le barème.', 'bdTariff', 2),
    pme: proved('PEA-PME prévu dans le barème.', 'bdTariff', 2),
    jeune: proved('PEA Jeunes prévu dans le barème.', 'bdTariff', 2),
    ifu: proved('IFU mis à disposition pour la déclaration du compte titres.', 'bdIfu'),
    cash: { status: 'corroboré', summary: 'Non selon BrokerChooser et Détective Banque pour les espèces du CTO et du PEA ; la page PEA officielle précise aussi l’absence d’intérêt. Les brochures consultées ne formulent pas une exclusion globale.', refs: [{ document: 'brokerBdCash' }, { document: 'detectiveBdCash' }, { document: 'bdPea' }] },
    transfert: { status: 'confirmé', summary: 'Transfert PEA sortant : 15 € par ligne, plafond 150 €. Pour un transfert entrant, la page tarifaire actuelle prévoit un remboursement jusqu’à 150 € pour PEA/PEA-PME/PEA Jeune (200 € pour CTO), sur justificatif ; la FAQ générique non ventilée annonce 200 € par compte.', refs: [{ document: 'bdTariff', page: 4 }, { document: 'bdTariffPage' }, { document: 'bdSupport' }] },
  },
  saxo: {
    boursomarkets: unknown('Offre BoursoMarkets propre à BoursoBank ; sans objet pour ce courtier.'),
    frais: { status: 'confirmé', summary: 'Classic Euronext : 0,08 % avec minimum de 2 € (plafond réglementaire PEA). Jusqu’au 31/12/2026, achats et ventes sans courtage sur 70 actions européennes sélectionnées pour les PEA nouvellement ouverts ou transférés remplissant les conditions Saxo ; autres frais possibles, notamment change.', refs: [{ document: 'saxoTariff', page: 5 }, { document: 'saxoPeaPromo' }] },
    dca: proved('Plan Épargne Programmé sans commission d’achat ni frais mensuels ; actuellement indisponible dans le PEA.', 'saxoAutoinvest'),
    garde: proved('0 € sur titres cotés ; exception pour non cotés en PEA.', 'saxoTariff', 3),
    pea: proved('PEA couvert par le barème.', 'saxoTariff', 16),
    pme: proved('PEA-PME couvert par le barème.', 'saxoTariff', 16),
    jeune: proved('Saxo Banque indique explicitement ne pas proposer de PEA Jeune.', 'saxoPeaHelp'),
    ifu: proved('IFU en ligne gratuit dans la brochure.', 'saxoTariff', 3),
    cash: { status: 'confirmé', summary: 'Oui pour espèces éligibles en EUR/USD selon solde et niveau de compte ; taux variable. PEA exclu de cette offre.', refs: [{ document: 'saxoContract', page: 24 }, { document: 'saxoInterest' }] },
    transfert: proved('Transfert PEA/PEA-PME sortant à 15 € par ligne, plafond 150 €.', 'saxoTariff', 16),
  },
}

export const EVIDENCE_FIELDS = [
  ['frais', 'Ordres PEA'], ['boursomarkets', 'BoursoMarkets'], ['dca', 'Investissement programmé'], ['garde', 'Frais de garde'],
  ['pea', 'PEA'], ['pme', 'PEA-PME'], ['jeune', 'PEA Jeune'], ['ifu', 'IFU'],
  ['cash', 'Liquidités rémunérées'], ['transfert', 'Transfert PEA'],
]
