// Chaque côté : une base ETF, un complément facultatif, une thématique facultative.
const row = (id, pct) => ({ id, pct })
export const DUELS = [
 { id: 'emergents-chine', title: 'Émergents avec ou sans Chine ?', hook: 'Même socle World à 70 % : EM IMI ou EM ex-China pour les 30 % restants ? Le second retire aussi les petites capitalisations.', left: [row('msci_world_ishares',70),row('msci_em',30)], right: [row('msci_world_ishares',70),row('em_ex_china',30)], labels: ['World + EM IMI','World + EM hors Chine'], question: 'Tu retirerais la Chine en acceptant aussi un univers de tailles différent ?' },
 { id: 'world-jeux-video', title: 'World seul ou poche jeux vidéo ?', hook: 'Une base mondiale identique : qu’aurait changé une poche de 10 % en jeux vidéo ?', left: [row('msci_world_ishares',100)], right: [row('msci_world_ishares',90),row('gaming_vaneck',10)], labels: ['World seul','World + jeux vidéo'], question: 'Tu garderais cette conviction dans une petite poche ?' },
 { id: 'world-innovation-medicale', title: 'World seul ou innovation médicale ?', hook: 'Une poche de 10 % dédiée à l’innovation dans les soins : quel résultat ?', left: [row('msci_world_ishares',100)], right: [row('msci_world_ishares',90),row('medical_innovation_ishares',10)], labels: ['World seul','World + innovation'], question: 'L’innovation médicale mérite-t-elle une poche à part ?' },
 { id: 'sante-innovation-biotech', title: 'Innovation médicale ou biotech ?', hook: 'Même socle World à 90 %, mais une poche spécialisée différente à 10 %.', left: [row('msci_world_ishares',90),row('medical_innovation_ishares',10)], right: [row('msci_world_ishares',90),row('sect_biotech_ishares',10)], labels: ['World + innovation','World + biotech'], question: 'Tu choisirais l’innovation dans les soins ou les biotechnologies du Nasdaq ?' },
 { id: 'world-immo-infrastructure', title: 'Immobilier coté ou infrastructures ?', hook: 'Même socle mondial de 80 % : deux activités différentes pour les 20 % restants.', left: [row('msci_world_ishares',80),row('immo_ishares_yield',20)], right: [row('msci_world_ishares',80),row('infrastructure_ishares',20)], labels: ['World + immobilier','World + infrastructures'], question: 'Tu renforcerais quelle activité ?' },
 { id: 'world-em-ou-acwi-imi', title: 'World + émergents ou ACWI IMI ?', hook: 'Deux lignes pour le monde, ou une seule qui inclut aussi les petites entreprises ?', left: [row('msci_world_ishares',85),row('msci_em',15)], right: [row('acwi_imi_spdr',100)], labels: ['World + émergents','ACWI IMI'], question: 'Tu choisirais les poids toi-même, ou la répartition de l’ACWI IMI ?' },
 { id: 'world-small-monde', title: 'World seul ou petites mondiales ?', hook: 'Les petites entreprises sont absentes de ton World. Qu’aurait changé une poche de 20 % ?', left: [row('msci_world_ishares',100)], right: [row('msci_world_ishares',80),row('smallcap_monde',20)], question: 'Tu ferais une place aux petites entreprises de plusieurs pays ?' },
{ id: 'sp500-pondere-ou-equal', title: 'S&P 500 classique ou équipondéré ?', hook: 'Les mêmes entreprises, mais une autre pondération : quel résultat ?', left: [row('sp500_ishares',100)], right: [row('sp500_equal_weight',100)], question: 'Tu laisserais les géants peser davantage ?' },
 { id: 'world-ou-exusa', title: 'World classique ou moins d’USA ?', hook: 'Tu gardes un World, ou tu donnes davantage de place aux autres marchés développés ?', left: [row('msci_world_ishares',100)], right: [row('msci_world_ishares',70),row('world_ex_usa',30)], question: 'Tu choisirais toi-même le poids des États-Unis ?' },
 { id: 'pea-global-ou-deux-lignes', title: 'Global PEA ou World + émergents ?', hook: 'Investir dans le monde : une seule ligne ou deux poids à régler ?', left: [row('pea_global_amundi',100)], right: [row('msci_world_ishares',85),row('msci_em',15)], question: 'Tu préfères suivre le poids de l’indice ou choisir celui des émergents ?' },
 { id: 'world-small-us', title: 'World seul ou petites américaines ?', hook: 'Ton World laisse les petites entreprises à part. Tu leur ferais une place ?', left: [row('msci_world_ishares',100)], right: [row('msci_world_ishares',80),row('russell2000_spdr',20)], question: 'Tu aurais ajouté des petites capitalisations américaines ?' },
 { id: 'em-bond-local-usd', title: 'Dette émergente : dollars ou monnaies locales ?', hook: 'Les mêmes marchés émergents, mais une autre monnaie d’emprunt : qu’est-ce que ça change ?', left: [row('msci_world_ishares',70),row('oblig_em_local_ishares_acc',30)], right: [row('msci_world_ishares',70),row('oblig_em_usd_ishares',30)], question: 'Pour les coupons émergents, quelle monnaie choisirais-tu ?' },
 { id: 'oblig-courtes-longues', title: 'Obligations euro : courtes ou longues ?', hook: 'Tu ajoutes des obligations d’État. Mais de quelle durée ?', left: [row('msci_world_ishares',70),row('oblig_0_1_ishares',30)], right: [row('msci_world_ishares',70),row('oblig_eur_long_ishares',30)], question: 'Tu accepterais la sensibilité des obligations longues ?' },
  { id: 'world-avec-world_momentum_ishares', title: 'World seul ou World + Momentum ?', hook: 'Tu gardes 100 % de World, ou tu consacres 20 % à Momentum ?', left: [row('msci_world_ishares', 100)], right: [row('msci_world_ishares', 80), row('world_momentum_ishares', 20)], labels: ['World seul', 'World + Momentum'], question: 'Tu suivrais davantage les gagnants récents ou tu garderais ton World seul ?' },
  { id: 'world-avec-strat_dividendes', title: 'World seul ou World + Global Dividend Aristocrats ?', hook: 'Tu gardes 100 % de World, ou tu consacres 20 % à Global Dividend Aristocrats ?', left: [row('msci_world_ishares', 100)], right: [row('msci_world_ishares', 80), row('strat_dividendes', 20)], labels: ['World seul', 'World + Global Dividend Aristocrats'], question: 'Tu donnerais une place particulière aux entreprises qui versent des dividendes ?' },
  { id: 'world-avec-high_dividend', title: 'World seul ou World + High Dividend ?', hook: 'Tu gardes 100 % de World, ou tu consacres 20 % à High Dividend ?', left: [row('msci_world_ishares', 100)], right: [row('msci_world_ishares', 80), row('high_dividend', 20)], labels: ['World seul', 'World + High Dividend'], question: 'Les dividendes changent-ils ta façon de choisir un ETF ?' },
  { id: 'world-avec-quality_dividend', title: 'World seul ou World + Quality Dividend ?', hook: 'Tu gardes 100 % de World, ou tu consacres 20 % à Quality Dividend ?', left: [row('msci_world_ishares', 100)], right: [row('msci_world_ishares', 80), row('quality_dividend', 20)], labels: ['World seul', 'World + Quality Dividend'], question: 'Tu privilégies les dividendes ou un indice mondial sans ce filtre ?' },
  { id: 'world-avec-monetaire_xeon', title: 'World seul ou World + XEON ?', hook: 'Tu gardes 100 % de World, ou tu consacres 40 % à XEON ?', left: [row('msci_world_ishares', 100)], right: [row('msci_world_ishares', 60), row('monetaire_xeon', 40)], labels: ['World seul', 'World + XEON'], question: 'Tu accepterais moins d’actions pour garder une poche monétaire ?' },
  { id: 'world-avec-oblig_0_1_ishares', title: 'World seul ou World + obligations 0–1 an ?', hook: 'Tu gardes 100 % de World, ou tu consacres 40 % à obligations 0–1 an ?', left: [row('msci_world_ishares', 100)], right: [row('msci_world_ishares', 60), row('oblig_0_1_ishares', 40)], labels: ['World seul', 'World + obligations 0–1 an'], question: 'Tu préfères rester entièrement en actions ou ajouter des obligations courtes ?' },
  { id: 'world-avec-oblig_global_agg_eur_hedged', title: 'World seul ou World + obligations mondiales couvertes EUR ?', hook: 'Tu gardes 100 % de World, ou tu consacres 40 % à obligations mondiales couvertes EUR ?', left: [row('msci_world_ishares', 100)], right: [row('msci_world_ishares', 60), row('oblig_global_agg_eur_hedged', 40)], labels: ['World seul', 'World + obligations mondiales couvertes EUR'], question: 'Quelle place donnerais-tu aux obligations dans ton portefeuille ?' },
  { id: 'sect_tech_world_ishares-contre-sect_financieres', title: 'World + technologie ou financières américaines ?', hook: 'Tu gardes la même base mondiale. Pour les 10 % restants, tu choisirais technologie ou financières américaines ?', left: [row('msci_world_ishares', 90), row('sect_tech_world_ishares', 10)], right: [row('msci_world_ishares', 90), row('sect_financieres', 10)], question: 'Tu prendrais lequel, et pourquoi ?' },
  { id: 'sect_financieres-contre-financieres_monde', title: 'World + financières américaines ou mondiales ?', hook: 'Tu gardes la même base mondiale. Pour les 10 % restants, tu choisirais financières américaines ou mondiales ?', left: [row('msci_world_ishares', 90), row('sect_financieres', 10)], right: [row('msci_world_ishares', 90), row('financieres_monde', 10)], question: 'Tu prendrais lequel, et pourquoi ?' },
  { id: 'semiconducteurs_monde-contre-blockchain_ishares', title: 'World + semi-conducteurs ou blockchain ?', hook: 'Tu gardes la même base mondiale. Pour les 10 % restants, tu choisirais semi-conducteurs ou blockchain ?', left: [row('msci_world_ishares', 90), row('semiconducteurs_monde', 10)], right: [row('msci_world_ishares', 90), row('blockchain_ishares', 10)], question: 'Tu prendrais lequel, et pourquoi ?' },
  {
    id: 'world-em-ou-acwi', title: 'World + émergents ou ACWI ?',
    hook: 'Pour investir dans le monde, tu prends un seul ETF ou tu fais ta répartition toi-même ?',
    left: [row('msci_world_ishares', 80), row('msci_em', 20)], right: [row('msci_acwi_ishares', 100)],
    labels: ['World + émergents', 'ACWI seul'],
    question: 'Tu préfères fixer le poids des émergents ou suivre leur place dans l’indice ?',
  },
  {
    id: 'world-ou-acwi', title: 'World ou ACWI ?',
    hook: 'Un ETF mondial, oui. Mais tu veux les marchés émergents dedans ou pas ?',
    left: [row('msci_world_ishares', 100)], right: [row('msci_acwi_ishares', 100)],
    labels: ['World seul', 'ACWI seul'], question: 'Ton ETF mondial inclut les émergents ?',
  },
  {
    id: 'acwi-ou-allworld', title: 'ACWI ou FTSE All-World ?',
    hook: 'ACWI ou FTSE All-World : pour ton ETF mondial, tu aurais pris lequel ?',
    left: [row('msci_acwi_ishares', 100)], right: [row('ftse_allworld_vanguard', 100)],
    labels: ['ACWI seul', 'FTSE All-World seul'], question: 'Tu as choisi quel indice pour ta base mondiale ?',
  },
  {
    id: 'sp500-europe-ou-acwi', title: 'S&P 500 + Europe ou ACWI ?',
    hook: 'Tu répartis toi-même entre les États-Unis et l’Europe, ou tu prends un ETF mondial ?',
    left: [row('sp500_ishares', 80), row('msci_europe', 20)], right: [row('msci_acwi_ishares', 100)],
    labels: ['S&P 500 + Europe', 'ACWI seul'], question: 'Tu choisis le poids de chaque zone ou tu suis l’indice mondial ?',
  },
  {
    id: 'world-stoxx-ou-acwi', title: 'World + STOXX 600 ou ACWI ?',
    hook: 'Ton ETF World contient déjà de l’Europe. Tu en ajouterais quand même ?',
    left: [row('msci_world_ishares', 80), row('stoxx600_bnp', 20)], right: [row('msci_acwi_ishares', 100)],
    labels: ['World + Europe', 'ACWI seul'], question: 'Tu renforces l’Europe dans ton portefeuille ?',
  },
  {
    id: 'usa-europe-sante-ou-acwi-tech', title: 'USA, Europe et santé ou ACWI et tech ?',
    hook: 'Une base américaine avec Europe et santé, ou une base mondiale avec davantage de tech ?',
    left: [row('sp500_ishares', 70), row('msci_europe', 20), row('sect_sante', 10)],
    right: [row('msci_acwi_ishares', 80), row('sect_tech_world_ishares', 20)],
    labels: ['USA + Europe + santé', 'ACWI + tech'], question: 'Tu aurais construit lequel de ces deux portefeuilles ?',
  },
  {
    id: 'allworld-cyber-ou-world-em', title: 'All-World + cyber ou World + émergents ?',
    hook: 'Tu ajouterais une thématique à ton ETF mondial, ou tu renforcerais les émergents ?',
    left: [row('ftse_allworld_vanguard', 90), row('sect_cyber_lg', 10)],
    right: [row('msci_world_ishares', 80), row('msci_em', 20)],
    labels: ['All-World + cyber', 'World + émergents'], question: 'Tu as une poche thématique dans ton portefeuille ?',
  },
  {
    id: 'world-smallcap-ou-acwi', title: 'World + petites capitalisations ou ACWI ?',
    hook: 'Pour élargir ton World, tu choisirais les petites capitalisations ou les marchés émergents ?',
    left: [row('msci_world_ishares', 80), row('smallcap_monde', 20)], right: [row('msci_acwi_ishares', 100)],
    labels: ['World + petites caps', 'ACWI seul'], question: 'Petites capitalisations ou émergents : quelle place leur donnes-tu ?',
  },
  {
    id: 'world-em-energie-ou-allworld-tech', title: 'World, émergents et énergie ou All-World et tech ?',
    hook: 'Un portefeuille mondial avec de l’énergie, ou un portefeuille mondial avec davantage de tech ?',
    left: [row('msci_world_ishares', 80), row('msci_em', 10), row('sect_energy_spdr', 10)],
    right: [row('ftse_allworld_vanguard', 90), row('sect_tech_world_ishares', 10)],
    labels: ['World + émergents + énergie', 'All-World + tech'], question: 'Tu renforces un secteur en particulier ?',
  },
  {
    id: 'world-value-ou-world-quality', title: 'World + Value ou World + Quality ?',
    hook: 'Tu gardes ton World. À côté, tu privilégies les entreprises peu chères ou leurs critères de qualité ?',
    left: [row('msci_world_ishares', 80), row('actions_value', 20)],
    right: [row('msci_world_ishares', 80), row('world_quality_ishares', 20)],
    labels: ['World + Value', 'World + Quality'], question: 'Tu ajouterais un filtre Value ou Quality à ton portefeuille ?',
  },
  {
    id: 'sp500-japon-ou-acwi-inde', title: 'S&P 500 + Japon ou ACWI + Inde ?',
    hook: 'Une base américaine complétée par le Japon, ou une base mondiale avec plus d’Inde ?',
    left: [row('sp500_ishares', 80), row('actions_japon', 20)],
    right: [row('msci_acwi_ishares', 80), row('actions_india_ishares', 20)],
    labels: ['S&P 500 + Japon', 'ACWI + Inde'], question: 'Tu donnerais davantage de place au Japon ou à l’Inde ?',
  },
  {
    id: 'world-energie-propre-ou-allworld-infrastructure', title: 'World + énergies propres ou All-World + infrastructures ?',
    hook: 'Pour ta poche thématique, tu choisirais les énergies propres ou les infrastructures ?',
    left: [row('msci_world_ishares', 90), row('sect_energie_propre', 10)],
    right: [row('ftse_allworld_vanguard', 90), row('infrastructure_ishares', 10)],
    labels: ['World + énergies propres', 'All-World + infrastructures'], question: 'Lequel de ces deux portefeuilles te correspondrait le mieux ?',
  },
]
