// Quatre duels pilotes : une ligne de 70 % identique et une seule décision sur les 30 % restants.
// Les parts et leurs rendements proviennent du Générateur, les devises sont contrôlées dans lib.js.
export const DUELS = [
  {
    id: 'energie-ou-tech',
    title: 'Énergie ou technologie ?',
    hook: 'Énergie ou technologie : laquelle aurait mieux servi ton portefeuille ?',
    common: 'msci_acwi_ishares',
    left: 'sect_energy_spdr',
    right: 'sect_tech_world_ishares',
    labels: ['Énergie', 'Technologie'],
    question: 'En connaissant aussi la chute de la tech en 2022, tu prends A ou B ? 👇',
  },
  {
    id: 'dividendes-ou-momentum',
    title: 'Dividendes ou momentum ?',
    hook: 'Actions à dividendes ou momentum : tu aurais misé sur quoi ?',
    common: 'msci_acwi_ishares',
    left: 'dividend_aristocrats_us_spdr',
    right: 'world_momentum_ishares',
    labels: ['Dividendes US', 'Momentum mondial'],
    question: 'Le résultat final ou la pire année : qu’est-ce qui pèse le plus dans ton choix ? 👇',
  },
  {
    id: 'em-actions-ou-obligations',
    title: 'Émergents : actions ou obligations ?',
    hook: 'Marchés émergents : tu préfères les actions ou les obligations ?',
    common: 'msci_acwi_ishares',
    left: 'msci_em',
    right: 'oblig_em_local_ishares_acc',
    labels: ['Actions émergentes', 'Dette émergente'],
    question: 'Pour cette part du portefeuille, tu aurais choisi A ou B ? 👇',
  },
  {
    id: 'qualite-ou-faible-volatilite',
    title: 'Qualité ou faible volatilité ?',
    hook: 'Actions de qualité ou faible volatilité : quel choix aurait payé ?',
    common: 'ftse_allworld_vanguard',
    left: 'world_quality_ishares',
    right: 'world_minvol_ishares',
    labels: ['Qualité', 'Faible volatilité'],
    question: 'Tu privilégies le capital final ou la pire année ? 👇',
  },
  // Séries 2020–2025 : parts exactes du registre ETF et même devise USD ;
  // buildDuel contrôle les ISIN, les six années et les liens vers les émetteurs.
  {
    id: 'monde-large-ou-emergents',
    title: 'Monde large ou émergents ?',
    hook: 'Pour compléter un portefeuille mondial, tu aurais renforcé le monde entier ou les émergents ?',
    common: 'msci_acwi_ishares',
    left: 'ftse_allworld_vanguard',
    right: 'msci_em',
    labels: ['Monde large', 'Émergents'],
    question: 'Tu préfères renforcer les pays déjà dominants ou ajouter davantage d’émergents ? 👇',
  },
  {
    id: 'biotech-ou-technologie',
    title: 'Biotechnologie ou technologie mondiale ?',
    hook: 'Biotechnologies ou technologie mondiale : où aurais-tu mis tes 30 % thématiques ?',
    common: 'msci_acwi_ishares',
    left: 'sect_biotech_ishares',
    right: 'sect_tech_world_ishares',
    labels: ['Biotechnologie', 'Technologie'],
    question: 'Tu choisirais le secteur le plus spécialisé ou la technologie au sens large ? 👇',
  },
  {
    id: 'faible-volatilite-ou-dividendes-us',
    title: 'Faible volatilité ou dividendes US ?',
    hook: 'Faible volatilité mondiale ou dividendes américains : quel complément aurais-tu choisi ?',
    common: 'msci_acwi_ishares',
    left: 'world_minvol_ishares',
    right: 'dividend_aristocrats_us_spdr',
    labels: ['Faible volatilité', 'Dividendes US'],
    question: 'Quel risque te paraît le plus acceptable dans ces deux approches ? 👇',
  },
  {
    id: 'immobilier-ou-qualite',
    title: 'Immobilier coté ou qualité ?',
    hook: 'Immobilier coté ou actions de qualité : quel pari aurait changé ton résultat ?',
    common: 'ftse_allworld_vanguard',
    left: 'immo_ishares_yield',
    right: 'world_quality_ishares',
    labels: ['Immobilier coté', 'Qualité mondiale'],
    question: 'Tu diversifies par secteur immobilier ou par critère de qualité ? 👇',
  },
  {
    id: 'ia-ou-cybersecurite',
    title: 'Intelligence artificielle ou cybersécurité ?',
    hook: 'IA ou cybersécurité : quel thème aurais-tu choisi pour compléter un ETF mondial ?',
    common: 'ftse_allworld_vanguard',
    left: 'sect_ai_lg',
    right: 'sect_cyber_lg',
    labels: ['Intelligence artificielle', 'Cybersécurité'],
    question: 'Entre ces deux thèmes, lequel conserverais-tu sur la durée ? 👇',
  },
]
