// Rédaction réservée au tweet : les images et les registres financiers restent indépendants.
export const COMPARISON_EDITORIAL = {
  monde: {
    hook: '🌍 Tu cherches un ETF mondial pour ton portefeuille. Mais entre World, ACWI et All-World, lequel correspond à ce que tu veux acheter ?',
    focus: 'pays couverts, frais et accès au PEA',
    conclusion: 'iShares WPEA suit le MSCI World : les pays développés, sans les émergents. Amundi PEA Global suit le MSCI ACWI et ajoute les émergents. Ces deux ETF sont éligibles au PEA.\n\nVanguard suit le FTSE All-World sur un CTO : un univers proche de l’ACWI, avec des règles et des pondérations différentes.',
  },
  usa: { hook: '🇺🇸 Tu veux un ETF sur les actions américaines. S&P 500, Nasdaq-100 et Dow Jones ne sélectionnent pas les mêmes entreprises : lequel correspond à ce que tu recherches ?', focus: 'indice suivi, frais et accès au PEA' },
  europe: { hook: '🇪🇺 Tu veux investir en Europe avec un ETF. Mais choisir la zone euro ou plusieurs marchés européens ne te donne pas les mêmes entreprises.', focus: 'marchés couverts, frais et accès au PEA' },
  'tech-europe': { hook: '💻 Deux ETF suivent la technologie européenne et le même indice. Alors, qu’est-ce qui peut faire pencher ton choix ?', focus: 'frais et accès au PEA' },
  emergents: { hook: '🌏 Tu veux ajouter les marchés émergents à ton portefeuille. Mais tes ETF incluent-ils les petites entreprises et appliquent-ils les mêmes filtres ?', focus: 'entreprises couvertes, filtres ESG et accès au PEA' },
  luxe: { hook: '💎 Tu veux un ETF sur le luxe. Entre ces deux fonds Amundi, que change le choix du PEA ou du CTO ?', focus: 'indice suivi, frais et accès au PEA' },
  'ia-robotique': { hook: '🤖 Tu veux investir dans l’IA avec un ETF. Mais IA, big data et robotique ne désignent pas le même panier d’entreprises.', focus: 'thème réellement suivi, indice et frais' },
  sante: {
    hook: '🩺 Tu veux un ETF sur la santé. Préfères-tu des entreprises de plusieurs pays ou une exposition européenne dans ton PEA ?',
    focus: 'activités couvertes, exclusions et accès au PEA',
    conclusion: 'Les ETF iShares et Xtrackers couvrent la santé des pays développés. Le fonds Amundi cible la santé européenne et permet d’investir via le PEA.\n\nL’indice Advanced d’iShares applique des exclusions : même secteur ne signifie donc pas même panier d’entreprises.',
  },
  renouvelables: { hook: '⚡ Tu cherches un ETF sur les énergies propres. Trois fonds portent ce thème, mais ils ne sélectionnent pas les entreprises avec le même indice.', focus: 'indice suivi, frais et versement des revenus' },
  dividendes: { hook: '💰 Tu cherches un ETF à dividendes. Mais veux-tu recevoir les revenus, les réinvestir ou privilégier les entreprises qui les augmentent ?', focus: 'sélection des entreprises, revenus versés ou réinvestis et frais' },
  japon: { hook: '🇯🇵 Tu veux un ETF sur le Japon. TOPIX ou Nikkei 225, avec ou sans couverture du yen : lequel correspond à l’exposition que tu recherches ?', focus: 'indice suivi, couverture de change et accès au PEA' },
  defense: { hook: '🛡️ Tu veux un ETF sur la défense. Mais veux-tu inclure les entreprises américaines ou te concentrer sur l’Europe ?', focus: 'zone couverte et frais' },
  quantique: { hook: '⚛️ Tu veux investir dans l’informatique quantique avec un ETF. Ces trois fonds portent le même thème : suivent-ils pour autant le même indice ?', focus: 'indice suivi et frais' },
  spatial: { hook: '🚀 Tu veux investir dans le spatial avec un ETF. Voici ce que suit VanEck Space Innovators et les frais de ce fonds.', focus: 'indice suivi, réplication et frais' },
  'ressources-naturelles': {
    hook: '⛏️ Tu veux investir dans les ressources naturelles. Mais entre les entreprises minières, la chimie et les gaz industriels, ces ETF ne te donnent pas la même exposition.',
    focus: 'activités couvertes, zone et accès au PEA',
    conclusion: 'VanEck cible les minières et inclut les marchés émergents. Xtrackers couvre les matériaux des pays développés.\n\nLes deux Amundi ciblent l’Europe et permettent d’investir via le PEA. Basic Materials élargit l’exposition à des activités comme la chimie et les gaz industriels.\n\nCes quatre ETF donnent une exposition aux actions d’entreprises. Leur performance dépend aussi des coûts de production, des marges et de la gestion de ces sociétés, pas seulement du prix des métaux.',
  },
  'etc-metaux': { hook: '🥇 Tu veux acheter de l’or, de l’argent ou du cuivre en Bourse. Ces trois ETC ne suivent pas tous le métal de la même façon.', focus: 'métal suivi, structure et coûts' },
  financieres: { hook: '🏦 Tu veux ajouter un ETF sur les financières. Seulement les entreprises américaines ou celles de plusieurs pays développés ?', focus: 'activités couvertes, zone et versement des revenus' },
  'semiconducteurs-tech': { hook: '💻 Tu hésites entre un ETF sur les semi-conducteurs et un ETF technologique plus large. Qu’est-ce que tu changes dans ton portefeuille ?', focus: 'industrie ou secteur couvert et frais' },
  blockchain: { hook: '🔗 Tu veux un ETF blockchain. Mais ce fonds achète des actions d’entreprises, pas directement du Bitcoin : voici ce que tu détiens.', focus: 'exposition réelle et frais' },
}

// Une phrase utile par produit, fondée sur les caractéristiques déjà documentées.
export const FUND_EXPOSURES = {
  IE00BD4TXV59: 'Des actions de pays développés, sans les marchés émergents.',
  IE00BK5BQT80: 'Des actions de pays développés et émergents dans une seule ligne.',
  IE00B44Z5B48: 'Des pays développés et émergents également, avec un indice construit par MSCI plutôt que FTSE.',
  IE0002XZSHO1: 'Le MSCI World dans ton PEA, grâce à une réplication synthétique.',
  IE000XZSV718: 'Les grandes entreprises du S&P 500, avec une réplication physique.',
  FR0011871128: 'Un large panier de grandes entreprises américaines via le S&P 500, accessible dans le PEA.',
  FR0007056841: 'Le Dow Jones : 30 grandes sociétés américaines, pondérées par le prix de leurs actions, sur un CTO.',
  FR0014017NX3: 'Le MSCI ACWI dans le PEA : grandes et moyennes entreprises des pays développés et émergents.',
  FR0013412038: 'Le MSCI Europe dans le PEA : grandes et moyennes entreprises de plusieurs marchés européens.',
  IE000DQLYVB9: 'Le S&P 500 dans le PEA, avec une part créée en 2025.',
  FR0011871110: 'Le Nasdaq-100 dans le PEA, avec une exposition concentrée.',
  IE00B4K48X80: 'Les grandes et moyennes entreprises de plusieurs marchés européens, via le MSCI Europe.',
  IE00B53L3W79: 'Cinquante grandes valeurs de la zone euro, via l’EURO STOXX 50.',
  FR0011550193: 'Le STOXX Europe 600 : un panier européen plus étendu que les seules grandes valeurs de la zone euro.',
  LU1834988518: 'Le secteur technologique du STOXX Europe 600, accessible dans le PEA.',
  DE000A0H08Q4: 'Le même indice STOXX Europe 600 Technology, sur un compte-titres.',
  IE00BKM4GZ66: 'Les marchés émergents, petites capitalisations comprises, via le MSCI EM IMI.',
  FR0013412020: 'Les marchés émergents dans le PEA, avec des filtres ESG.',
  IE00BTJRMP35: 'Les marchés émergents avec une réplication physique par échantillonnage.',
  LU1681048630: 'Les entreprises du luxe sélectionnées par l’indice S&P Global Luxury.',
  FR001400S9V0: 'Une exposition au luxe mondial accessible dans le PEA.',
  IE00BGV5VN51: 'Des entreprises liées à l’intelligence artificielle et au big data.',
  IE00BK5BCD43: 'L’intelligence artificielle selon la sélection de ROBO Global.',
  IE00BYZK4552: 'Des entreprises de l’automatisation et de la robotique.',
  IE00BJ5JNZ06: 'La santé des pays développés : notamment pharmacie, équipements et services de soins, avec les exclusions de l’indice Advanced.',
  IE00BM67HK77: 'La santé des pays développés, des laboratoires aux équipements et services de soins, avec les revenus réinvestis.',
  LU1834986900: 'Les entreprises européennes de la santé : notamment pharmacie, équipements et services de soins.',
  IE00B1XNHC34: 'Les entreprises retenues par l’indice Global Clean Energy Transition.',
  FR0010524777: 'Les nouvelles énergies selon un indice MSCI filtré, avec les revenus distribués.',
  IE00BK5BCH80: 'Les entreprises retenues par l’indice Solactive Clean Energy.',
  IE00B8GKDB10: 'Des entreprises sélectionnées pour le rendement de leurs dividendes, avec les revenus distribués.',
  IE00B9CQXS71: 'Des entreprises ayant maintenu ou augmenté leurs dividendes pendant au moins dix ans, avec les revenus distribués.',
  IE00BZ56SW52: 'Une sélection fondée sur la qualité et la croissance des dividendes, avec les revenus réinvestis.',
  LU2089238385: 'Les grandes et moyennes entreprises japonaises.',
  FR0013411980: 'Le TOPIX dans le PEA, sans couverture du yen.',
  FR0013411998: 'Le TOPIX dans le PEA, avec une couverture du yen en euros.',
  LU1875395870: 'Le Nikkei 225 avec une couverture en euros et les revenus distribués.',
  IE000YYE6WK5: 'La défense mondiale, entreprises américaines comprises.',
  IE0002Y8CX98: 'Les entreprises de la défense européenne.',
  LU3038520774: 'Une autre sélection d’entreprises de la défense européenne.',
  IE0007Y8Y157: 'Le thème quantique selon l’indice MarketVector Global Quantum Leaders.',
  IE000C6ITGC8: 'Une autre sélection d’entreprises sur le thème de l’informatique quantique.',
  IE000W8WMSL2: 'Le thème quantique selon un indice développé avec Classiq.',
  IE000YU9K6K2: 'L’industrie spatiale selon l’indice MarketVector Global Space Industry Screened.',
  IE00BDFBTQ78: 'Des entreprises minières des pays développés et émergents : extraction d’or, de cuivre, de minerai de fer et d’autres métaux.',
  LU1834983550: 'Les ressources de base européennes : entreprises minières, sidérurgie, papier et produits forestiers.',
  LU1834983634: 'Une exposition européenne plus large : les ressources de base, mais aussi la chimie et les gaz industriels.',
  IE00BM67HS53: 'Les matériaux dans les pays développés : entreprises minières, chimie, gaz industriels et autres activités du secteur.',
  IE00B4ND3602: 'Un titre adossé à de l’or physique.',
  FR0013416716: 'Un autre produit adossé à de l’or physique, avec un émetteur de droit irlandais.',
  IE00B4NCWG09: 'Un titre adossé à de l’argent physique.',
  GB00B15KXQ89: 'Des contrats à terme sur le cuivre via swap ; taux de swap annuel : 0,45 % en plus des frais de gestion.',
  IE00B4JNQZ49: 'Les financières américaines : notamment banques, assurances et services financiers, avec une exposition concentrée sur un pays.',
  IE00BJ5JP097: 'Les banques, assurances et autres services financiers de plusieurs pays développés, avec les revenus distribués.',
  IE000I8KRLL9: 'Une industrie précise : les entreprises mondiales des semi-conducteurs, de la conception des puces aux équipements de production.',
  IE00BJ5JNY98: 'La technologie des pays développés : logiciels, matériel informatique et semi-conducteurs, avec une exposition plus large que les seules puces.',
  IE000RDRMSD1: 'Des actions d’entreprises liées à la blockchain, sans détention directe de Bitcoin.',
}
