// Sources primaires de référence pour les définitions du lexique.
// Une URL seule ne valide pas tous les chiffres et toutes les exceptions de la fiche.
const SP = 'https://www.service-public.fr/particuliers/vosdroits/'
const AMF = 'https://www.amf-france.org/fr/espace-epargnants/'
export const LEXICON_SOURCES = {
  pea: 'https://www.impots.gouv.fr/particulier/questions/jai-un-plan-depargne-en-actions-pea-les-retraits-sont-ils-imposables',
  cto: 'https://www.impots.gouv.fr/particulier/les-cessions-mobilieres',
  'assurance-vie': 'https://www.impots.gouv.fr/particulier/lassurance-vie-et-le-pea-0',
  per: SP + 'F34982', 'livret-a': SP + 'F2365', ldds: SP + 'F2368',
  'pee-perco': SP + 'F2142',
  etf: AMF + 'comprendre-les-produits-financiers/placements-collectifs/trackers-etf',
  trackers: AMF + 'comprendre-les-produits-financiers/placements-collectifs/trackers-etf',
  action: AMF + 'comprendre-les-produits-financiers/actions-obligations/actions/investir-en-actions-cotees-en-bourse',
  obligation: AMF + 'comprendre-les-produits-financiers/actions-obligations/obligations/comprendre-les-obligations-avant-dinvestir',
  fcp: AMF + 'comprendre-les-produits-financiers/placements-collectifs/ce-quil-faut-savoir-sur-les-placements-collectifs-fonds-et-sicav',
  scpi: AMF + 'comprendre-les-produits-financiers/placements-collectifs/scpiopci-un-placement-non-garanti-soumis-aux-fluctuations-du-marche-immobilier',
  opci: AMF + 'comprendre-les-produits-financiers/placements-collectifs/opci-siic-les-autres-produits-de-la-pierre-papier',
  diversification: AMF + 'savoir-bien-investir/conseils-pratiques/diversifier-ses-placements',
  volatilite: AMF + 'savoir-bien-investir/cadrer-son-projet/volatilite-des-placements-ce-quil-faut-savoir-0',
  'effet-levier': 'https://www.amf-france.org/fr/effet-de-levier',
  'vente-a-decouvert': 'https://www.amf-france.org/fr/vente-decouvert',
  blockchain: 'https://developer.bitcoin.org/devguide/block_chain.html',
  'cold-hot-wallet': AMF + 'proteger-son-epargne/crypto-actifs-bitcoin-etc/investir-en-crypto-actifs-les-precautions-pratiques',
  ter: AMF + 'les-frais-des-placements-financiers/comprendre-les-frais-des-placements-financiers',
  'taux-sans-risque': 'https://www.ecb.europa.eu/stats/euro-short-term-rates/interest_rate_benchmarks/WG_euro_risk-free_rates/html/index.en.html',
  lmnp: SP + 'F10864',
  stablecoin: 'https://www.amf-france.org/fr/crypto-actif-ou-crypto-monnaie',
  'indice-boursier': AMF + 'comprendre-les-marches-financiers/les-marches-dactions-et-les-principaux-indices-en-france',
  'reinvestissement-dividendes': AMF + 'comprendre-les-produits-financiers/placements-collectifs/trackers-etf',
  'rendement-vs-performance': AMF + 'savoir-bien-investir/cadrer-son-projet/rendement-et-risque-des-placements-en-actions-0',
  dca: 'https://corporate.vanguard.com/content/dam/corp/research/pdf/cost_averaging_invest_now_or_temporarily_hold_your_cash.pdf',
  reequilibrage: 'https://investor.vanguard.com/investor-resources-education/portfolio-management/rebalancing-your-portfolio',
  'dca-vs-lumpsum': 'https://corporate.vanguard.com/content/dam/corp/research/pdf/cost_averaging_invest_now_or_temporarily_hold_your_cash.pdf',
  dividende: 'https://www.amf-france.org/fr/le-mediateur-de-lamf/journal-de-bord-du-mediateur/dossiers-du-mois/quelle-date-sapprecie-la-qualite-dactionnaire-permettant-de-beneficier-du-droit-au-dividende-qui-y',
  'rendement-locatif': 'https://www.anil.org/outil-mise-en-location-simulation-investissement-immobilier-rendement/',
  'effet-levier-immo': 'https://www.anil.org/votre-besoin/gerer-un-bien/bailleur/investissement-locatif/',
  drawdown: 'https://www.msci.com/documents/10199/54361618-43c2-878f-eeaa-0b237a13ce6d',
  'ratio-sharpe': 'https://www.amf-france.org/sites/institutionnel/files/contenu_simple/rapport_annuel/rapport_annuel_amf/Rapport%20annuel%20AMF%202008%20-%20Chapitre%208%20-%20L%27AMF%20et%20les%20professionnels.pdf',
  'capitalisation-boursiere': 'https://www.amf-france.org/fr/capitalisation-boursiere',
  inflation: 'https://www.insee.fr/fr/metadonnees/definition/c1557',
  'taux-interet': 'https://data.ecb.europa.eu/methodology/what-are-interest-rates',
  halving: 'https://bitcoin.org/fr/vocabulaire',
  'flat-tax': 'https://www.impots.gouv.fr/particulier/les-cessions-mobilieres',
  'abattement-pea': 'https://www.impots.gouv.fr/particulier/questions/jai-un-plan-depargne-en-actions-pea-les-retraits-sont-ils-imposables',
  'prelevements-sociaux': 'https://www.impots.gouv.fr/particulier/lassurance-vie-et-le-pea-0',
  'plus-value-imposable': 'https://bofip.impots.gouv.fr/bofip/3648-PGP.html/identifiant=BOI-RPPM-PVBMI-20-10-20-10-20191220',
  'plus-value-immobiliere': SP + 'F10864',
}
