import assert from 'node:assert/strict'
import { chromium } from 'playwright'
import { spawn } from 'node:child_process'
import { mkdir, readFile } from 'node:fs/promises'
const output='/tmp/wealth-qa'
await mkdir(output,{recursive:true})
const server=process.env.WEALTH_TEST_URL ? null : spawn('node',['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4326'],{stdio:'ignore'})
const url=process.env.WEALTH_TEST_URL ?? 'http://127.0.0.1:4326/shinny-potato/'
let browser
try {
 for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{}),args:['--no-sandbox']})
 const page=await browser.newPage({viewport:{width:1440,height:1000}}), errors=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.goto(url)
 await page.getByRole('link',{name:/Simulateur de patrimoine/}).first().click()
 await page.getByRole('heading',{name:'Simulateur de patrimoine',exact:true}).waitFor()
 await page.getByRole('button',{name:'Charger un exemple',exact:true}).click()
 await page.getByRole('button',{name:'Sauvegarder sur cet appareil',exact:true}).click()
 await page.screenshot({path:`${output}/desktop.png`,fullPage:true})
 await page.getByRole('button',{name:'Comparaison pour X',exact:true}).click()
 await page.getByRole('button',{name:'Publication X',exact:true}).click()
 assert.match(await page.getByRole('textbox',{name:'Brouillon de publication'}).inputValue(),/Patrimoine B/)
 await page.getByRole('textbox',{name:'Brouillon de publication'}).fill('Brouillon personnalisé')
 await page.getByRole('button',{name:'Rétablir le texte',exact:true}).click()
 assert.match(await page.getByRole('textbox',{name:'Brouillon de publication'}).inputValue(),/simulation/i)
 const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Télécharger l’image',exact:true}).click()])
 await download.saveAs(`${output}/projection.png`)
 const png=await readFile(`${output}/projection.png`);assert.equal(png.readUInt32BE(16),1600);assert.ok(png.readUInt32BE(20)>1000)
 const [json]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Exporter JSON',exact:true}).click()]);await json.saveAs(`${output}/plan.json`)
 const saved=JSON.parse(await readFile(`${output}/plan.json`,'utf8'));assert.equal(saved.mode,'compare');assert.equal(saved.portfolios.a.pockets[0].initial,15000)
 await page.getByRole('button',{name:'Projection',exact:true}).click()
 const [csv]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Exporter les projections CSV',exact:true}).click()]);await csv.saveAs(`${output}/projection.csv`)
 assert.equal((await readFile(`${output}/projection.csv`,'utf8')).split('\n').length,43)
 await page.getByRole('button',{name:'Répartition par enveloppe',exact:true}).click();await page.getByRole('heading',{name:'Répartition de Patrimoine A'}).waitFor()
 await page.getByRole('button',{name:'Projection',exact:true}).click()
 await page.getByRole('button',{name:'Charger ma sauvegarde',exact:true}).click()
 assert.equal(await page.getByRole('button',{name:'Mon patrimoine',exact:true}).getAttribute('aria-pressed'),'true')
 await page.getByText('Durée (années)',{exact:true}).locator('..').getByRole('spinbutton').fill('10')
 await page.getByRole('button',{name:'Projection',exact:true}).click();await page.getByRole('columnheader',{name:'À 10 ans'}).waitFor()
 await page.getByRole('button',{name:'Ajouter un changement',exact:true}).click()
 await page.getByRole('group',{name:'Type événement 1'}).getByRole('button',{name:'Retirer du capital'}).click()
 await page.getByText('Retrait demandé (€)',{exact:true}).locator('..').getByRole('spinbutton').fill('5000')
 await page.getByText('À partir du mois',{exact:true}).locator('..').getByRole('spinbutton').fill('60')
 await page.getByRole('button',{name:'Publication X',exact:true}).click()
 assert.match(await page.getByRole('textbox',{name:'Brouillon de publication'}).inputValue(),/retrait.*mois 60/)
 await page.getByText('Durée (années)',{exact:true}).locator('..').getByRole('spinbutton').fill('0')
 await page.getByRole('alert').waitFor();assert.equal(await page.getByRole('button',{name:'Télécharger l’image',exact:true}).isDisabled(),true)
 await page.getByText('Durée (années)',{exact:true}).locator('..').getByRole('spinbutton').fill('10')
 await page.locator('input[type=file]').setInputFiles(`${output}/plan.json`)
 await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Comparaison pour X'&&b.getAttribute('aria-pressed')==='true'))
 await page.locator('input[type=file]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')})
 await page.getByRole('status').filter({hasText:'non reconnu'}).waitFor()
 const mobile=await browser.newPage({viewport:{width:390,height:844}})
 mobile.on('pageerror',e=>errors.push(e.message))
 await mobile.goto(`${url}simulateur-patrimoine`)
 await mobile.getByRole('heading',{name:'Simulateur de patrimoine',exact:true}).waitFor()
 await mobile.getByRole('button',{name:'Charger un exemple',exact:true}).click()
 await mobile.getByRole('button',{name:'Aperçu',exact:true}).click()
 await mobile.getByRole('button',{name:'Projection',exact:true}).click()
 await mobile.screenshot({path:`${output}/mobile.png`,fullPage:true})
 assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Débordement mobile')
 await mobile.getByRole('tab',{name:'Image',exact:true}).click()
 await mobile.getByRole('img',{name:'Projection de patrimoine avec hypothèses'}).waitFor()
 await mobile.screenshot({path:`${output}/mobile-image.png`,fullPage:true})
 assert.deepEqual(errors,[])
 console.log('Navigateur : saisie, comparaison, brouillon, PNG/CSV/JSON, sauvegarde, import invalide et mobile validés.')
} finally {await browser?.close();server?.kill()}
