// Relevé de fiches officielles, figé au 31 août 2026 (au 30 juin pour deux fonds).
// Composition = indice sous-jacent, jamais les titres détenus par le fonds synthétique.
// Les rendements du fonds sont les lignes « Portefeuille » des tableaux Amundi.
const world = 'https://www.msci.com/documents/10199/255599/msci-world-index.pdf'
const europe = 'https://www.msci.com/documents/10199/255599/msci-europe-index-eur-net.pdf'
const em = 'https://www.msci.com/documents/10199/255599/msci-em-ex-egypt-esg-leaders-select-issuer-capped-index-usd-net.pdf'
const emFund = 'https://www.amundietf.fr/pdfDocuments/monthly-factsheet/FR0013412020/FRA/FRA/INSTITUTIONNEL/ETF/20260630'
const spFund = 'https://www.amundietf.fr/pdfDocuments/monthly-factsheet/FR0011871128/FRA/FRA/RETAIL/ETF/20260630'
const nasFund = 'https://www.amundietf.fr/pdfDocuments/monthly-factsheet/FR0011871110/FRA/FRA/RETAIL/ETF/20260831'
const acwi = 'https://www.msci.com/documents/10199/255599/msci-acwi.pdf'
const allWorld = 'https://research.ftserussell.com/Analytics/FactSheets/Home/DownloadSingleIssue?isManual=False&issueName=AWORLDS&openfile=open'
const smallCap = 'https://www.msci.com/documents/10199/255599/msci-world-small-cap-index.pdf'
const exUsa = 'https://www.msci.com/documents/10199/255599/msci-world-ex-usa-index.pdf'

export const SHEETS = [
  {
    id: 'acwi', title: 'MSCI ACWI', index: 'MSCI ACWI', snapshot: '31 août 2026', source: [{ label: 'Composition et performances, MSCI', url: acwi }],
    intro: 'Tu connais le MSCI World. Le MSCI ACWI va plus loin en ajoutant les marchés émergents 🌍',
    constituents: 2458, markets: '23 pays développés et 24 marchés émergents', marketCap: '104 043 milliards $ de capitalisation ajustée du flottant',
    countries: [['🇺🇸 États-Unis', 63.59], ['🇯🇵 Japon', 5.09], ['🇹🇼 Taïwan', 3.25], ['🇬🇧 Royaume-Uni', 3.11], ['🇨🇦 Canada', 3.05], ['🌍 Autres', 21.91]],
    sectors: [['💻 Technologie', 31.20], ['🏦 Finance', 16.95], ['🏭 Industrie', 10.59], ['🛍️ Consommation discrétionnaire', 8.72], ['🏥 Santé', 8.49], ['📡 Communication', 7.69], ['🛒 Consommation de base', 4.65], ['⚡ Énergie', 4.01], ['🪨 Matériaux', 3.80], ['💡 Services publics', 2.33], ['🏠 Immobilier', 1.56]],
    holdings: [['Nvidia', 4.90], ['Apple', 4.47], ['Microsoft', 3.44], ['Amazon', 2.42], ['Alphabet A', 1.90], ['TSMC', 1.80], ['Broadcom', 1.60], ['Alphabet C', 1.49], ['Meta', 1.21], ['Micron', 1.04]], topWeight: 24.26,
    returns: [[2025, 22.87], [2024, 18.02], [2023, 22.81], [2022, -17.96], [2021, 19.04]], performance: { kind: 'indice', detail: 'MSCI ACWI, rendement brut en dollars, dividendes réinvestis', date: '31 août 2026', tenYear: 13.12 },
    insight: 'Les émergents entrent dans le panier, mais les États-Unis représentent encore près de 64 % de l’indice.',
    takeaway: 'Le MSCI ACWI couvre davantage de marchés que le MSCI World. « Tous pays » ne signifie pas « tous les titres » : les petites capitalisations restent à part.',
  },
  {
    id: 'ftse-all-world', title: 'FTSE All-World', index: 'FTSE All-World', snapshot: '31 août 2026', source: [{ label: 'Composition et performances, FTSE Russell', url: allWorld }],
    intro: 'Un autre indice permet de suivre les marchés développés et émergents : le FTSE All-World 🌍',
    constituents: 4264, markets: 'marchés développés et émergents', marketCap: '107 192 milliards $ de capitalisation flottante nette',
    countries: [['🇺🇸 États-Unis', 61.71], ['🇯🇵 Japon', 5.98], ['🇹🇼 Taïwan', 3.30], ['🇬🇧 Royaume-Uni', 3.20], ['🇨🇦 Canada', 3.00], ['🌍 Autres', 22.81]],
    sectors: [['💻 Technologie', 34.09], ['🏦 Finance', 15.49], ['🏭 Industrie', 12.31], ['🛍️ Consommation discrétionnaire', 11.04], ['🏥 Santé', 7.98], ['⚡ Énergie', 4.15], ['🛒 Consommation de base', 3.89], ['🪨 Matériaux de base', 3.44], ['📡 Télécommunications', 3.33], ['💡 Services publics', 2.55], ['🏠 Immobilier', 1.74]],
    holdings: [['Nvidia', 4.79], ['Apple', 4.26], ['Microsoft', 3.51], ['Amazon', 2.35], ['Alphabet A', 1.84], ['TSMC', 1.72], ['Broadcom', 1.60], ['Alphabet C', 1.48], ['Meta', 1.17], ['Micron', 1.01]], topWeight: 23.73,
    returns: [[2025, 23.1], [2024, 17.7], [2023, 22.6], [2022, -17.7], [2021, 18.9]], performance: { kind: 'indice', detail: 'FTSE All-World, rendement total en dollars, dividendes réinvestis ; secteurs selon la classification ICB de FTSE', date: '31 août 2026', annualizedFiveYear: 11.4 },
    insight: 'Plus de 4 200 valeurs, mais les États-Unis pèsent toujours près de 62 %. Le nombre de titres ne dit pas tout de leur poids.',
    takeaway: 'Il inclut les marchés émergents et les grandes et moyennes capitalisations. Ses secteurs ICB ne sont pas directement comparables aux secteurs GICS des fiches MSCI.',
  },
  {
    id: 'world-small-cap', title: 'MSCI World Small Cap', index: 'MSCI World Small Cap', snapshot: '31 août 2026', source: [{ label: 'Composition et performances, MSCI', url: smallCap }],
    intro: 'Le MSCI World laisse de côté les petites capitalisations. Le MSCI World Small Cap leur est consacré 🔎',
    constituents: 3866, markets: '23 pays développés, petites capitalisations', marketCap: '10 840 milliards $ de capitalisation ajustée du flottant',
    countries: [['🇺🇸 États-Unis', 61.76], ['🇯🇵 Japon', 12.58], ['🇬🇧 Royaume-Uni', 4.57], ['🇨🇦 Canada', 4.29], ['🇦🇺 Australie', 3.51], ['🌍 Autres', 13.29]],
    sectors: [['🏭 Industrie', 19.31], ['🏦 Finance', 14.68], ['💻 Technologie', 14.33], ['🏥 Santé', 11.11], ['🛍️ Consommation discrétionnaire', 10.11], ['🪨 Matériaux', 8.31], ['🏠 Immobilier', 7.51], ['⚡ Énergie', 5.08], ['🛒 Consommation de base', 4.00], ['📡 Communication', 3.04], ['💡 Services publics', 2.52]],
    holdings: [['Sandisk', 2.08], ['Moderna', 0.43], ['ATI', 0.26], ['nVent Electric', 0.22], ['Tenet Healthcare', 0.21], ['US Foods', 0.21], ['Carpenter Technology', 0.21], ['Royal Gold', 0.20], ['Roku A', 0.19], ['Woodward', 0.19]], topWeight: 4.21,
    returns: [[2025, 20.44], [2024, 8.65], [2023, 16.34], [2022, -18.37], [2021, 16.18]], performance: { kind: 'indice', detail: 'MSCI World Small Cap, rendement brut en dollars, dividendes réinvestis', date: '31 août 2026', tenYear: 10.80 },
    insight: 'Les dix premières valeurs ne pèsent que 4,21 % : le profil est bien différent de celui du MSCI World classique.',
    takeaway: '« Small Cap » décrit un segment de taille, pas une liste d’entreprises nécessairement petites en valeur absolue. L’indice exclut les émergents.',
  },
  {
    id: 'world-ex-usa', title: 'MSCI World ex USA', index: 'MSCI World ex USA', snapshot: '31 août 2026', source: [{ label: 'Composition et performances, MSCI', url: exUsa }],
    intro: 'Et si tu retirais les États-Unis du MSCI World ? C’est le principe du MSCI World ex USA 🌍',
    constituents: 755, markets: '22 pays développés, hors États-Unis', marketCap: '25 547 milliards $ de capitalisation ajustée du flottant',
    countries: [['🇯🇵 Japon', 20.73], ['🇬🇧 Royaume-Uni', 12.67], ['🇨🇦 Canada', 12.41], ['🇫🇷 France', 8.46], ['🇨🇭 Suisse', 8.09], ['🌍 Autres', 37.64]],
    sectors: [['🏦 Finance', 28.01], ['🏭 Industrie', 17.79], ['💻 Technologie', 10.10], ['🏥 Santé', 8.89], ['🛍️ Consommation discrétionnaire', 7.67], ['🪨 Matériaux', 7.52], ['🛒 Consommation de base', 6.13], ['⚡ Énergie', 5.41], ['📡 Communication', 3.57], ['💡 Services publics', 3.55], ['🏠 Immobilier', 1.37]],
    holdings: [['ASML', 2.56], ['HSBC', 1.39], ['Roche', 1.20], ['Royal Bank of Canada', 1.12], ['Novartis', 1.09], ['Shell', 1.00], ['Nestlé', 0.98], ['Siemens', 0.96], ['Mitsubishi UFJ', 0.96], ['AstraZeneca', 0.96]], topWeight: 12.24,
    returns: [[2025, 32.55], [2024, 5.26], [2023, 18.60], [2022, -13.82], [2021, 13.17]], performance: { kind: 'indice', detail: 'MSCI World ex USA, rendement brut en dollars, dividendes réinvestis', date: '31 août 2026', tenYear: 10.33 },
    insight: 'Le Japon passe en tête avec plus de 20 %. La finance devient le premier secteur, devant l’industrie et la technologie.',
    takeaway: 'Retirer les États-Unis modifie toute la répartition. Ce n’est pas pour autant un indice « tout sauf États-Unis » : seuls les marchés développés restent inclus.',
  },
  {
    id: 'world', title: 'MSCI World', index: 'MSCI World', snapshot: '31 août 2026', source: [{ label: 'Composition et performances, MSCI', url: world }],
    intro: 'Tout le monde connaît le MSCI World. Mais connais-tu vraiment ce qu’il y a dedans ? 🌍',
    constituents: 1280, markets: '23 pays développés', marketCap: '91 705 milliards $ de capitalisation ajustée du flottant',
    countries: [['🇺🇸 États-Unis', 72.14], ['🇯🇵 Japon', 5.78], ['🇬🇧 Royaume-Uni', 3.53], ['🇨🇦 Canada', 3.46], ['🇫🇷 France', 2.36], ['🌍 Autres', 12.74]],
    sectors: [['💻 Technologie', 29.81], ['🏦 Finance', 16.58], ['🏭 Industrie', 11.13], ['🏥 Santé', 9.27], ['🛍️ Consommation discrétionnaire', 8.82], ['📡 Communication', 7.9], ['🛒 Consommation de base', 4.91], ['⚡ Énergie', 4.09], ['🪨 Matériaux', 3.47], ['💡 Services publics', 2.39], ['🏠 Immobilier', 1.64]],
    holdings: [['Nvidia', 5.56], ['Apple', 5.07], ['Microsoft', 3.90], ['Amazon', 2.74], ['Alphabet A', 2.15], ['Broadcom', 1.82], ['Alphabet C', 1.69], ['Meta', 1.37], ['Micron', 1.18], ['Tesla', 1.13]], topWeight: 26.61,
    returns: [[2025, 21.60], [2024, 19.19], [2023, 24.42], [2022, -17.73], [2021, 22.35]], performance: { kind: 'indice', detail: 'MSCI World, rendement brut en dollars, dividendes réinvestis', date: '31 août 2026', tenYear: 13.56 },
    insight: 'Le nom dit « World ». Les États-Unis pèsent pourtant plus de 72 % : ce n’est pas une répartition égale entre les pays.',
    takeaway: 'Une seule ligne peut donner accès à 1 280 entreprises, mais les dix premières représentent déjà plus d’un quart de l’indice.',
  },
  {
    id: 'stoxx600', title: 'STOXX Europe 600', index: 'STOXX Europe 600', snapshot: '31 août 2026', source: [{ label: 'Factsheet STOXX, version EUR Price Return', url: 'https://stoxx.com/index/sxxp/?factsheet=true' }],
    intro: 'Le STOXX Europe 600 rassemble 600 entreprises européennes. Mais comment le poids se partage-t-il entre les pays ? 🇪🇺',
    constituents: 600, markets: '17 pays européens développés', marketCap: '13 481 milliards € de capitalisation flottante',
    countries: [['🇬🇧 Royaume-Uni', 22.9], ['🇫🇷 France', 15.0], ['🇨🇭 Suisse', 13.7], ['🇩🇪 Allemagne', 13.4], ['🇳🇱 Pays-Bas', 7.9], ['🇪🇸 Espagne', 6.0], ['🇮🇹 Italie', 5.7], ['🌍 Autres', 15.4]],
    sectors: [['🏦 Banques', 15.7], ['🏭 Biens et services industriels', 15.4], ['🏥 Santé', 12.3], ['💻 Technologie', 8.9], ['⚡ Énergie', 6.5], ['🛡️ Assurance', 6.0], ['🛒 Alimentation et boissons', 4.9], ['💡 Services publics', 4.4], ['🛍️ Produits et services de consommation', 4.2], ['💰 Services financiers', 4.2]],
    holdings: [['ASML', 4.180], ['HSBC', 2.274], ['Roche', 1.959], ['Novartis', 1.855], ['Shell', 1.634], ['AstraZeneca', 1.607], ['Nestlé', 1.605], ['Siemens', 1.555], ['SAP', 1.432], ['Banco Santander', 1.380]],
    returns: [[2025, 16.94], [2024, 6.05], [2023, 12.94], [2022, -13.04], [2021, 22.44]], performance: { kind: 'indice', detail: 'STOXX Europe 600, en EUR, hors dividendes (Price Return)', date: '31 août 2026', trailingOneYear: 18.4, annualizedFiveYear: 6.8 },
    insight: 'Le Royaume-Uni arrive devant la France et l’Allemagne. « Europe » ne signifie pas uniquement zone euro.',
    takeaway: 'Les banques et l’industrie pèsent chacun environ 15 % : la technologie n’est pas le moteur dominant ici.',
  },
  {
    id: 'eurostoxx50', title: 'EURO STOXX 50', index: 'EURO STOXX 50', snapshot: '31 août 2026', source: [{ label: 'Factsheet STOXX, version EUR Price Return', url: 'https://stoxx.com/index/sx5e/?factsheet=true' }],
    intro: 'L’EURO STOXX 50 tient en 50 entreprises de la zone euro. Voici ce que cela donne dans la composition 🇪🇺',
    constituents: 50, markets: 'grandes entreprises de la zone euro', marketCap: '4 461 milliards € de capitalisation flottante',
    countries: [['🇫🇷 France', 31.7], ['🇩🇪 Allemagne', 30.2], ['🇳🇱 Pays-Bas', 13.5], ['🇪🇸 Espagne', 11.6], ['🇮🇹 Italie', 8.9], ['🇧🇪 Belgique', 2.8], ['🇫🇮 Finlande', 1.3]],
    sectors: [['🏦 Banques', 19.7], ['🏭 Biens et services industriels', 17.4], ['💻 Technologie', 15.8], ['⚡ Énergie', 7.5], ['🛡️ Assurance', 7.0], ['🛍️ Produits et services de consommation', 6.4], ['🏥 Santé', 5.4], ['💡 Services publics', 4.5], ['🧪 Chimie', 3.5], ['🚘 Automobiles', 2.6]],
    holdings: [['ASML', 8.689], ['Siemens', 4.699], ['SAP', 4.329], ['Banco Santander', 4.170], ['TotalEnergies', 3.854], ['Allianz', 3.844], ['Schneider Electric', 3.811], ['BBVA', 3.161], ['UniCredit', 2.844], ['Iberdrola', 2.830]],
    returns: [[2025, 18.60], [2024, 8.38], [2023, 19.51], [2022, -11.87], [2021, 21.17]], performance: { kind: 'indice', detail: 'EURO STOXX 50, en EUR, hors dividendes (Price Return)', date: '31 août 2026', trailingOneYear: 20.0, annualizedFiveYear: 9.0 },
    insight: 'France et Allemagne réunies : près de 62 % de l’indice. C’est une exposition à la zone euro, pas à toute l’Europe.',
    takeaway: 'ASML pèse presque 9 % à elle seule. Avec 50 valeurs, le poids de chaque grande entreprise se voit vite.',
  },
  {
    id: 'mscieurope', title: 'MSCI Europe', index: 'MSCI Europe', snapshot: '31 août 2026', source: [{ label: 'Composition et performances, MSCI', url: europe }],
    intro: 'Il existe un indice européen que peu de gens connaissent : le MSCI Europe 🇪🇺',
    constituents: 396, markets: '15 pays développés en Europe', marketCap: '12 453 milliards € de capitalisation ajustée du flottant',
    countries: [['🇬🇧 Royaume-Uni', 22.38], ['🇫🇷 France', 14.93], ['🇨🇭 Suisse', 14.29], ['🇩🇪 Allemagne', 13.99], ['🇳🇱 Pays-Bas', 8.79], ['🌍 Autres', 25.61]],
    sectors: [['🏦 Finance', 25.76], ['🏭 Industrie', 18.87], ['🏥 Santé', 12.70], ['💻 Technologie', 9.0], ['🛒 Consommation de base', 8.29], ['🛍️ Consommation discrétionnaire', 6.31], ['🪨 Matériaux', 5.55], ['⚡ Énergie', 4.96], ['💡 Services publics', 4.71], ['📡 Communication', 3.27], ['🏠 Immobilier', 0.60]],
    holdings: [['ASML', 4.53], ['HSBC', 2.46], ['Roche', 2.12], ['Novartis', 1.93], ['Shell', 1.76], ['Nestlé', 1.74], ['Siemens', 1.70], ['AstraZeneca', 1.70], ['SAP', 1.60], ['Banco Santander', 1.45]], topWeight: 20.99,
    returns: [[2025, 19.39], [2024, 8.59], [2023, 15.83], [2022, -9.49], [2021, 25.13]], performance: { kind: 'indice', detail: 'MSCI Europe, rendement net en euros, dividendes réinvestis', date: '31 août 2026', tenYear: 9.31 },
    insight: 'Royaume-Uni et Suisse figurent parmi les premiers poids : ici, « Europe » dépasse la seule zone euro.',
    takeaway: 'La finance pèse plus d’un quart. Ce n’est pas le même équilibre sectoriel que dans le MSCI World.',
  },
  {
    id: 'em-esg', title: 'Émergents ESG (Amundi PEA)', index: 'MSCI EM ex-Egypt ESG Broad CTB Select', snapshot: '31 août 2026 (indice) · 30 juin 2026 (ETF)',
    source: [{ label: 'Composition de l’indice, MSCI', url: em }, { label: 'Performances de l’ETF, Amundi', url: emFund }, { label: 'Changement d’indice en 2023, Amundi', url: 'https://www.amundietf.fr/pdfDocuments/download/863110a3-3a8e-43e7-ac7c-eb509bd2b05f/NoticeToShareholders_FR0013412020_FRA_FRA_20230825.pdf' }], isin: 'FR0013412020',
    intro: 'Cet ETF émergent éligible au PEA suit un indice ESG. Mais trois marchés y concentrent l’essentiel 🌏',
    constituents: 1048, markets: '23 marchés émergents, Égypte exclue',
    countries: [['🇹🇼 Taïwan', 27.75], ['🇰🇷 Corée du Sud', 20.83], ['🇨🇳 Chine', 20.71], ['🇮🇳 Inde', 11.15], ['🇧🇷 Brésil', 3.76], ['🌍 Autres', 15.80]],
    sectors: [['💻 Technologie', 41.72], ['🏦 Finance', 20.30], ['🛍️ Consommation discrétionnaire', 8.17], ['🏭 Industrie', 6.36], ['📡 Communication', 6.04], ['🪨 Matériaux', 5.77], ['🛒 Consommation de base', 3.22], ['⚡ Énergie', 3.08], ['🏥 Santé', 2.59], ['💡 Services publics', 1.45], ['🏠 Immobilier', 1.31]],
    holdings: [['TSMC', 15.22], ['Samsung Electronics', 7.16], ['SK Hynix', 5.55], ['Tencent', 2.79], ['Alibaba', 1.94], ['MediaTek', 1.42], ['Samsung Electronics Pref.', 1.03], ['China Construction Bank', 1.01], ['Delta Electronics', 1.00], ['Reliance Industries', 0.84]], topWeight: 37.96,
    returns: [[2025, 21.04], [2024, 13.39], [2023, 3.66], [2022, -15.01], [2021, 4.45]], performance: { kind: 'ETF', detail: 'Amundi PEA Emergent ESG Transition, performances nettes de la part en EUR', date: '30 juin 2026', historyNote: 'L’indice de référence a changé le 27 septembre 2023 : les années antérieures reflètent l’historique réel du fonds, pas celui de l’indice actuel.' },
    insight: 'Taïwan, Corée du Sud et Chine pèsent près de 70 %. Le poids de TSMC dépasse à lui seul 15 %.',
    takeaway: 'L’étiquette ESG modifie la sélection, mais elle n’efface pas la concentration géographique et technologique.',
  },
  {
    id: 'sp500-pea', title: 'S&P 500 (Amundi PEA)', index: 'S&P 500', snapshot: '30 juin 2026',
    source: [{ label: 'Composition et performances de l’ETF, Amundi', url: spFund }, { label: 'Méthodologie de l’indice, S&P DJI', url: 'https://www.spglobal.com/spdji/en/indices/equity/sp-500/' }], isin: 'FR0011871128',
    intro: 'Cet ETF S&P 500 est éligible au PEA. Voici la composition de l’indice qu’il suit 🇺🇸',
    constituents: 504, markets: 'États-Unis, selon la classification de la fiche Amundi',
    countries: [['🇺🇸 États-Unis', 100]],
    sectors: [['💻 Technologie', 37.37], ['🏦 Finance', 11.87], ['📡 Communication', 9.76], ['🛍️ Consommation discrétionnaire', 9.38], ['🏥 Santé', 9.07], ['🏭 Industrie', 8.88], ['🛒 Consommation de base', 4.68], ['⚡ Énergie', 3.02], ['💡 Services publics', 2.25], ['🏠 Immobilier', 1.88], ['🪨 Matériaux', 1.84]],
    holdings: [['Nvidia', 7.38], ['Apple', 6.47], ['Microsoft', 4.28], ['Amazon', 3.68], ['Alphabet A', 3.24], ['Broadcom', 2.76], ['Alphabet C', 2.60], ['Micron', 2.02], ['Meta', 1.93], ['Tesla', 1.81]], topWeight: 36.17,
    returns: [[2025, 3.45], [2024, 32.85], [2023, 21.68], [2022, -13.00], [2021, 38.23]], performance: { kind: 'ETF', detail: 'Amundi PEA S&P 500 UCITS ETF Acc, rendements nets de la part en EUR', date: '30 juin 2026' },
    insight: 'Les dix premières lignes pèsent plus de 36 %. Les 504 titres ne représentent pas 504 parts égales.',
    takeaway: 'La technologie pèse plus du tiers de l’indice : le S&P 500 a aussi un fort biais sectoriel.',
  },
  {
    id: 'nasdaq-pea', title: 'Nasdaq 100 (Amundi PEA)', index: 'NASDAQ-100 Notional Net Total Return', snapshot: '31 août 2026',
    source: [{ label: 'Composition et performances de l’ETF, Amundi', url: nasFund }], isin: 'FR0011871110',
    intro: 'Un ETF Nasdaq 100 éligible au PEA, mais quelle place prennent réellement ses premières entreprises ? 💻',
    constituents: 102, markets: 'grandes sociétés non financières cotées au Nasdaq',
    countries: [['🇺🇸 États-Unis', 94.78], ['🇮🇪 Irlande', 1.82], ['🇳🇱 Pays-Bas', 1.32], ['🇨🇦 Canada', 1.00], ['🇬🇧 Royaume-Uni', 0.66], ['🌍 Autres', 0.42]],
    sectors: [['💻 Technologie', 58.27], ['📡 Communication', 13.89], ['🛍️ Consommation discrétionnaire', 11.13], ['🛒 Consommation de base', 6.22], ['🏥 Santé', 4.01], ['🏭 Industrie', 3.62], ['💡 Services publics', 1.14], ['🪨 Matériaux', 1.00], ['⚡ Énergie', 0.52], ['🏦 Finance', 0.21]],
    holdings: [['Nvidia', 8.41], ['Apple', 7.50], ['Microsoft', 6.09], ['Micron', 4.64], ['Amazon', 4.58], ['AMD', 3.35], ['Alphabet A', 3.22], ['Alphabet C', 2.99], ['Broadcom', 2.79], ['Tesla', 2.78]], topWeight: 46.35,
    returns: [[2025, 6.01], [2024, 33.58], [2023, 49.32], [2022, -28.35], [2021, 36.59]], performance: { kind: 'ETF', detail: 'Amundi PEA Nasdaq-100 UCITS ETF Acc, rendements nets de la part en EUR', date: '31 août 2026' },
    insight: 'Près de 58 % en technologie et plus de 46 % dans les dix premières lignes : le pari est assumé.',
    takeaway: 'Ce n’est pas un indice qui couvre toutes les entreprises américaines : la finance en est pratiquement absente.',
  },
]
