// Registre central des outils : source unique pour le dashboard, la nav et les routes.
// status: 'disponible' une fois l'outil migré et branché, 'bientot' tant qu'il affiche un écran d'attente.
// Les couleurs historiques servent aux contenus exportés ; l’accueil emploie des icônes sobres.
export const TOOLS = [
  { to: '/presentation-scpi', navLabel: 'SCPI', title: 'Présentation de SCPI',
    publicationDay: 'Publication ponctuelle', icon: '🏢', accent: '#65d5b0',
    description: 'Patrimoine, distributions et frais des SCPI : sources officielles et texte modifiable.', status: 'disponible' },
  {
    to: '/analyse-entreprise', navLabel: 'Entreprises', title: 'Analyse d’entreprise',
    publicationDay: 'Mercredi midi', icon: '🏭', accent: '#7bd8bd',
    description: 'Activité, résultats publiés et valorisation disponible : texte et image actualisés automatiquement.', status: 'disponible',
  },
  {
    to: '/portefeuilles-investisseurs', navLabel: 'Investisseurs', title: "Portefeuille d’investisseur",
    publicationDay: 'Dimanche midi', icon: '👤', accent: '#d5ad65',
    description: 'Positions 13F de fonds connus : tweet, répartition et export PNG actualisés depuis Tracefour.', status: 'disponible',
  },
  {
    to: '/france-100-menages', navLabel: '100 ménages', title: 'La France en 100 ménages',
    publicationDay: 'Mardi midi',
    icon: '🇫🇷', accent: '#e7c97c', description: '29 sujets Insee sur le patrimoine, les salaires et le niveau de vie. Repères documentés, tweets prêts à copier et export PNG.', status: 'disponible',
  },
  {
    to: '/donnees-a-revoir', navLabel: 'À revoir', title: 'Données à revoir',
    icon: '🗓️', accent: '#fbbf24', description: 'Réserves ouvertes, échéances des offres et contrôles de sources à prévoir.', status: 'disponible',
  },
  {
    to: '/bibliotheque-donnees', navLabel: 'Données', title: 'Bibliothèque de données',
    icon: '🔎', accent: '#2dd4bf', description: 'Recherche par ISIN, ticker, nom ou indice. Sources, historiques, outils consommateurs et export JSON.', status: 'disponible',
  },
  {
    to: '/calculateur-investissement',
    navLabel: 'Calculateur',
    title: 'Et si tu avais investi ?',
    publicationDay: 'Mercredi soir',
    icon: '💰',
    accent: '#2dd4bf',
    description: "Simule la valeur d'un investissement passé, comparé au Livret A et à l'inflation.",
    status: 'disponible',
  },
  {
    to: '/generateur-portefeuilles',
    navLabel: 'Générateur portefeuilles',
    title: 'Générateur de portefeuilles',
    publicationDay: 'Mardi soir',
    icon: '🧭',
    accent: '#818cf8',
    description: "Portefeuilles illustratifs par profil d'investisseur et niveau de risque.",
    status: 'disponible',
  },
  {
    to: '/duels-portefeuilles',
    navLabel: 'Duels portefeuilles',
    title: 'Duel de portefeuilles',
    publicationDay: 'Jeudi midi',
    icon: '⚔️',
    description: 'Compare deux constructions : une base ETF, un complément et une thématique facultatifs. Duels préparés, génération, texte et image.',
    status: 'disponible',
  },
  {
    to: '/fiches-etf',
    navLabel: 'Fiches ETF',
    title: "Présentation d'ETF",
    publicationDay: 'Jeudi soir',
    icon: '📋',
    accent: '#fb923c',
    description: 'Fiches détaillées par ETF, texte prêt à publier + image téléchargeable.',
    status: 'disponible',
  },
  {
    to: '/comparatif-courtiers',
    navLabel: 'Comparatif courtiers',
    title: 'Comparatif courtiers',
    publicationDay: 'Publication ponctuelle',
    icon: '⚖️',
    accent: '#f472b6',
    description: 'Duels de courtiers en bourse (frais, PEA, DCA) prêts à publier.',
    status: 'disponible',
  },
  {
    to: '/fiche-lexique', navLabel: 'Fiche lexique', title: 'Fiche lexique',
    format: 'fiche-lexique', bundle: '/tweet-midi', publicationDay: 'Lundi midi · alternance',
    icon: '🕐', accent: '#a78bfa',
    description: 'Un terme financier expliqué avec un texte prêt à publier.', status: 'disponible',
  },
  {
    to: '/comparatif-etf', navLabel: 'Comparatif ETF', title: 'Comparatif ETF',
    format: 'comparatif-etf', bundle: '/tweet-midi', publicationDay: 'Lundi midi · alternance',
    icon: '🕐', accent: '#a78bfa',
    description: 'Compare les expositions, frais et performances de deux ETF.', status: 'disponible',
  },
  {
    to: '/il-y-a-x-ans', navLabel: 'Il y a X ans', title: 'Il y a X ans',
    format: 'anniversaire', bundle: '/tweet-midi', publicationDay: 'Publication ponctuelle',
    icon: '🕐', accent: '#a78bfa',
    description: 'Compare un prix historique au niveau actuel que tu renseignes.', status: 'disponible',
  },
  {
    to: '/performance-depuis', navLabel: 'Performance depuis', title: 'Performance depuis',
    format: 'performance-depuis', bundle: '/tweet-midi', publicationDay: 'Publication ponctuelle',
    icon: '🕐', accent: '#a78bfa',
    description: 'Les performances annuelles d’un actif sur la période choisie.', status: 'disponible',
  },
  {
    to: '/pouvoir-achat', navLabel: 'Pouvoir d’achat', title: 'Pouvoir d’achat',
    format: 'pouvoir-achat', bundle: '/tweet-midi', publicationDay: 'Publication ponctuelle',
    icon: '🕐', accent: '#a78bfa',
    description: 'Mesure l’évolution du pouvoir d’achat sur la période choisie.', status: 'disponible',
  },
  {
    to: '/dilemme', navLabel: 'Dilemme', title: 'Dilemme',
    format: 'dilemme', bundle: '/tweet-midi', publicationDay: 'Publication ponctuelle',
    icon: '🕐', accent: '#a78bfa',
    description: 'Deux choix de placement pour ouvrir la discussion.', status: 'disponible',
  },
  {
    to: '/vrai-faux', navLabel: 'Vrai ou faux', title: 'Vrai ou faux',
    format: 'vrai-faux', bundle: '/tweet-midi', publicationDay: 'Publication ponctuelle',
    icon: '🕐', accent: '#a78bfa',
    description: 'Des affirmations financières à expliquer et vérifier.', status: 'disponible',
  },
  {
    to: '/comparateur-indices',
    navLabel: 'Comparateur indices',
    title: "Comparateur d'indices",
    publicationDay: 'Vendredi midi',
    icon: '📐',
    accent: '#38bdf8',
    description: "Compare les indices concurrents d'une même famille : exposition, ETF PEA/CTO, diversification, performance.",
    status: 'disponible',
  },
  {
    to: '/impact-frais',
    navLabel: 'Impact des frais',
    title: "Calculateur d'impact des frais",
    publicationDay: 'Publication ponctuelle',
    icon: '🧮',
    accent: '#fbbf24',
    description: "Compare le capital final entre deux niveaux de frais de gestion (TER), en euros, sur simulation d'intérêts composés — hypothèse pédagogique, pas une donnée de marché.",
    status: 'disponible',
  },
  {
    to: '/faits-marquants-marches',
    navLabel: 'Faits marquants',
    title: 'Faits marquants des marchés',
    publicationDay: 'Dimanche soir',
    icon: '📚',
    accent: '#34d399',
    description: "Statistiques historiques sourcées sur les indices et calculs de baisse, récupération et versements sur huit actions sur les chocs, corrections et séquences des marchés, prêtes à publier en format \"le saviez-vous\".",
    status: 'disponible',
  },
  {
    to: '/cas-concrets',
    navLabel: 'Cas concrets',
    title: 'Cas concrets pour investir',
    publicationDay: 'Publication ponctuelle',
    icon: '🧩',
    accent: '#fb7185',
    description: 'Des situations pour comprendre ce que change réellement un choix de placement, avec sources et texte prêt à copier.',
    status: 'disponible',
  },
  {
    to: '/banque-tweets',
    navLabel: 'Banque de tweets',
    title: 'Banque de tweets à recycler',
    icon: '🗄️',
    accent: '#22d3ee',
    description: "Recycle tes meilleurs tweets déjà écrits : filtre par mois/catégorie/format, recherche libre, et repos de 45 jours après chaque publication pour épuiser le stock avant de répéter.",
    status: 'disponible',
  },
  {
    to: '/tweets-factsheets',
    navLabel: 'Décryptage indices',
    title: 'Dans les coulisses des indices',
    publicationDay: 'Lundi soir',
    icon: '🔎',
    description: 'Onze indices et ETF décortiqués à partir de leurs fiches officielles, avec un texte modifiable avant publication.',
    status: 'disponible',
  },
]

const TOOL_SUMMARIES = {
  '/presentation-scpi': 'Ce qu’elle détient, ce qu’elle verse et ce qu’elle coûte.',
  '/analyse-entreprise': 'Son activité, ses résultats et sa valorisation disponible.',
  '/comparateur-indices': 'Expositions, diversification et performances des indices.',
  '/comparatif-courtiers': 'Frais, PEA et services des courtiers en face à face.',
  '/calculateur-investissement': 'Ce que serait devenu ton investissement au fil du temps.',
  '/impact-frais': 'Mesure ce que les frais changent à ton capital final.',
  '/generateur-portefeuilles': 'Explore des allocations selon le profil et le risque.',
  '/duels-portefeuilles': 'Deux portefeuilles, deux façons d’investir.',
  '/portefeuilles-investisseurs': 'Les positions déclarées de grands investisseurs.',
  '/fiche-lexique': 'Un terme financier expliqué avec un texte prêt à publier.',
  '/comparatif-etf': 'Compare les expositions, frais et performances de deux ETF.',
  '/il-y-a-x-ans': 'Compare un prix historique au niveau actuel que tu renseignes.',
  '/performance-depuis': 'Les performances annuelles d’un actif sur la période choisie.',
  '/pouvoir-achat': 'Mesure l’évolution du pouvoir d’achat sur la période choisie.',
  '/dilemme': 'Deux choix de placement pour ouvrir la discussion.',
  '/vrai-faux': 'Des affirmations financières à expliquer et vérifier.',
  '/fiches-etf': 'Un ETF expliqué, avec son texte et ses visuels.',
  '/tweets-factsheets': 'Décrypte la composition et les caractéristiques des indices.',
  '/faits-marquants-marches': 'Des faits historiques pour raconter les marchés.',
  '/cas-concrets': 'Des situations concrètes pour comprendre un choix de placement.',
  '/france-100-menages': 'Le patrimoine et les revenus en chiffres et en images.',
  '/banque-tweets': 'Retrouve tes publications et prépare leur réutilisation.',
  '/bibliotheque-donnees': 'Recherche un actif, ses chiffres et ses sources.',
  '/donnees-a-revoir': 'Les données à actualiser et leurs prochaines échéances.',
}

// Les mêmes groupes alimentent l’accueil et la navigation.
export const TOOL_GROUPS = [
  { id: 'compare', title: 'Comparer et simuler', description: 'Mettre les placements et leurs résultats en perspective.', paths: ['/comparateur-indices', '/comparatif-courtiers', '/calculateur-investissement', '/impact-frais'] },
  { id: 'portfolio', title: 'Construire un portefeuille', description: 'Explorer des allocations et les choix des investisseurs.', paths: ['/generateur-portefeuilles', '/duels-portefeuilles', '/portefeuilles-investisseurs'] },
  { id: 'publish', title: 'Préparer une publication', description: 'Choisir un sujet, préparer son texte et ses visuels.', paths: ['/presentation-scpi', '/analyse-entreprise', '/fiche-lexique', '/comparatif-etf', '/il-y-a-x-ans', '/performance-depuis', '/pouvoir-achat', '/dilemme', '/vrai-faux', '/fiches-etf', '/tweets-factsheets', '/faits-marquants-marches', '/cas-concrets', '/france-100-menages', '/banque-tweets'] },
  { id: 'data', title: 'Gérer les données', description: 'Retrouver les sources et les prochaines mises à jour.', paths: ['/bibliotheque-donnees', '/donnees-a-revoir'] },
].map(group => ({ ...group, tools: group.paths.map(path => ({ ...TOOLS.find(tool => tool.to === path), summary: TOOL_SUMMARIES[path] })) }))

// Publication order for the home screen, followed by occasional and maintenance tools.
export const WEEKLY_ORDER = [
  '/comparatif-etf', '/fiche-lexique', '/tweets-factsheets',
  '/france-100-menages', '/generateur-portefeuilles',
  '/analyse-entreprise', '/calculateur-investissement',
  '/duels-portefeuilles', '/fiches-etf',
  '/comparateur-indices',
  '/portefeuilles-investisseurs', '/faits-marquants-marches',
  '/il-y-a-x-ans', '/performance-depuis', '/pouvoir-achat',
  '/dilemme', '/vrai-faux', '/comparatif-courtiers', '/cas-concrets', '/presentation-scpi',
  '/impact-frais', '/banque-tweets', '/bibliotheque-donnees', '/donnees-a-revoir',
]
export const HOME_TOOLS = TOOL_GROUPS.flatMap(group => group.tools.map(tool => ({ ...tool, group: group.id })))
  .sort((a, b) => WEEKLY_ORDER.indexOf(a.to) - WEEKLY_ORDER.indexOf(b.to))
