// Registre central des outils : source unique pour le dashboard, la nav et les routes.
// status: 'disponible' une fois l'outil migré et branché, 'bientot' tant qu'il affiche un écran d'attente.
// accent : couleur de la tuile d'icône sur le dashboard (ToolCard) — une teinte distincte par
// outil pour la repérabilité visuelle, cf. maquette validée le 25/09/2026 (option "tuile icône
// colorée, disposition horizontale"), seule des 3 options à rester lisible en largeur mobile réelle.
export const TOOLS = [
  {
    to: '/calculateur-investissement',
    navLabel: 'Calculateur',
    title: 'Et si tu avais investi ?',
    icon: '💰',
    accent: '#2dd4bf',
    description: "Simule la valeur d'un investissement passé, comparé au Livret A et à l'inflation.",
    status: 'disponible',
  },
  {
    to: '/generateur-portefeuilles',
    navLabel: 'Générateur portefeuilles',
    title: 'Générateur de portefeuilles',
    icon: '🧭',
    accent: '#818cf8',
    description: "Portefeuilles illustratifs par profil d'investisseur et niveau de risque.",
    status: 'disponible',
  },
  {
    to: '/duels-portefeuilles',
    navLabel: 'Duels portefeuilles',
    title: 'Duel de portefeuilles',
    icon: '⚔️',
    description: 'Compare deux portefeuilles : duels préparés, compositions manuelles ou idées générées, avec texte et image prêts à publier.',
    status: 'disponible',
  },
  {
    to: '/fiches-etf',
    navLabel: 'Fiches ETF',
    title: "Présentation d'ETF",
    icon: '📋',
    accent: '#fb923c',
    description: 'Fiches détaillées par ETF, texte prêt à publier + image téléchargeable.',
    status: 'disponible',
  },
  {
    to: '/comparatif-courtiers',
    navLabel: 'Comparatif courtiers',
    title: 'Comparatif courtiers',
    icon: '⚖️',
    accent: '#f472b6',
    description: 'Duels de courtiers en bourse (frais, PEA, DCA) prêts à publier.',
    status: 'disponible',
  },
  {
    to: '/tweet-midi',
    navLabel: 'Tweet Midi',
    title: 'Tweet Midi',
    icon: '🕐',
    accent: '#a78bfa',
    description: "Vrai ou Faux, Dilemmes, Fiches lexique, Comparatifs ETF, Anniversaires de prix, Performances historiques et Pouvoir d'achat, prêts à publier pour le créneau midi — sans dépendre de l'actualité.",
    status: 'disponible',
  },
  {
    to: '/comparateur-indices',
    navLabel: 'Comparateur indices',
    title: "Comparateur d'indices",
    icon: '📐',
    accent: '#38bdf8',
    description: "Compare les indices concurrents d'une même famille : exposition, ETF PEA/CTO, diversification, performance.",
    status: 'disponible',
  },
  {
    to: '/impact-frais',
    navLabel: 'Impact des frais',
    title: "Calculateur d'impact des frais",
    icon: '🧮',
    accent: '#fbbf24',
    description: "Compare le capital final entre deux niveaux de frais de gestion (TER), en euros, sur simulation d'intérêts composés — hypothèse pédagogique, pas une donnée de marché.",
    status: 'disponible',
  },
  {
    to: '/faits-marquants-marches',
    navLabel: 'Faits marquants',
    title: 'Faits marquants des marchés',
    icon: '📚',
    accent: '#34d399',
    description: "Statistiques historiques sourcées (S&P 500, Nasdaq, Dow Jones, CAC 40) sur les chocs, corrections et séquences des marchés, prêtes à publier en format \"le saviez-vous\".",
    status: 'disponible',
  },
  {
    to: '/cas-concrets',
    navLabel: 'Cas concrets',
    title: 'Cas concrets pour investir',
    icon: '🧩',
    accent: '#fb7185',
    description: 'Des situations pour comprendre ce que change réellement un choix de placement, avec sources et texte prêt à copier.',
    status: 'disponible',
  },
  {
    to: '/banque-tweets',
    navLabel: 'Banque de tweets',
    title: 'Banque de tweets à recycler',
    icon: '🗄️',
    accent: '#22d3ee',
    description: "Recycle tes meilleurs tweets déjà écrits : filtre par mois/catégorie/format, recherche libre, et repos de 45 jours après chaque publication pour épuiser le stock avant de répéter.",
    status: 'disponible',
  },
  {
    to: '/tweets-factsheets',
    navLabel: 'Décryptage indices',
    title: 'Dans les coulisses des indices',
    icon: '🔎',
    description: 'Sept indices et ETF décortiqués à partir de leurs fiches officielles, avec un texte modifiable avant publication.',
    status: 'disponible',
  },
]
